INSERT INTO Bijwerking(soort, beschrijving_bijwerking)
VALUES
("Leverbeschadiging", "Hoog gebruik of overdosering kan leiden tot ernstige leverbeschadiging."),
("Allergische Reacties", "Huiduitslag, jeuk of ernstigere reacties zoals anafylaxie."),
("Maagdarmklachten", "Misselijkheid, braken of diarree kunnen voorkomen."),
("Maagklachten", "Kan maagpijn, misselijkheid of zelfs maagzweren veroorzaken, vooral bij langdurig gebruik."),
("Nierproblemen", "Langdurig gebruik kan de nierfunctie beïnvloeden."),
("Hoofdpijn", "Kan hoofdpijn veroorzaken bij sommige gebruikers."),
("Candida-infecties", "Overgroei van gist zoals Candida kan optreden."),
("Geestelijke Verwarring", "Zelden kan metformine leiden tot mentale verwarring."),
("Vitamine B12 Deficiëntie", "Langdurig gebruik kan leiden tot een tekort aan vitamine B12."),
("Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Leverfunctie Verhoging", "Verhoogde leverenzymen kunnen voorkomen, wat leverfunctiestoornissen kan aangeven."),
("Duizeligheid", "Kan duizeligheid of flauwvallen veroorzaken."),
("Zwelling", "Voeten of enkels kunnen opzwellen door vochtretentie."),
("Verhoogde Kaliumspiegels", "Kan hyperkaliëmie veroorzaken."),
("Hartkloppingen", "Kan leiden tot een snelle hartslag of hartkloppingen."),
("Gewichtsverlies", "Kan leiden tot ongewenst gewichtsverlies."),
("Slaapproblemen", "Kan slapeloosheid of andere slaapproblemen veroorzaken."),
("Verhoogde Suikerspiegels", "Kan leiden tot hyperglykemie, vooral bij langdurig gebruik."),
("Gewichtstoename", "Kan leiden tot ongewenst gewichtsverlies of -toename."),
("Verhoogde Immuniteit", "Kan het immuunsysteem onderdrukken, waardoor infecties makkelijker voorkomen."),
("Misselijkheid", "Veelvoorkomende bijwerking, vooral bij het starten van de behandeling."),
("Slaperigheid", "Kan leiden tot vermoeidheid of slaperigheid."),
("Sexuele Dysfunctie", "Kan libido verminderen of seksuele disfunctie veroorzaken."),
("Trillen", "Kan leiden tot trillen van handen of andere lichaamsdelen."),
("Snelle Hartslag", "Kan tachycardie veroorzaken, vooral bij overmatig gebruik."),
("Spijsverteringsstoornissen", "Misselijkheid, braken of diarree kunnen voorkomen."),
("Rash", "Kan huiduitslag of jeuk veroorzaken."),
("Angst", "Kan angstgevoelens of nervositeit verergeren."),
("Verhoogde Leverenzymen", "Kan leiden tot verhoogde leverenzymwaarden bij langdurig gebruik."),
("Bloedingen", "Verhoogd risico op bloedingen, zoals neusbloedingen of tandvleesbloedingen."),
("Huiduitslag", "Kan huiduitslag of jeuk veroorzaken."),
("Elektrolytenonbalans", "Kan natrium- en kaliumtekorten veroorzaken."),
("Rouge", "Geelverkleuring van het gezicht of nek kan optreden."),
("Vermoeidheid", "Kan leiden tot vermoeidheid of slaperigheid."),
("Draagtijd Verlenging", "Kan de draagtijd van medicijnen verlengen door het beïnvloeden van de metabolisatie."),
("Afhankelijkheid", "Langdurig gebruik kan leiden tot fysieke en psychologische afhankelijkheid."),
("Bloedarmoede", "Zelden kan ibuprofen bloedarmoede veroorzaken."),
("Spierzwakte", "Kan spierzwakte of spierspasmen veroorzaken."),
("Dizziness", "Kan duizeligheid of licht gevoel in het hoofd veroorzaken."),
("Indigestion", "Kan maagpijn of indigestie veroorzaken."),
("Droge Mond", "Kan een droge mond veroorzaken."),
("Gynaecomastie", "Ontwikkeling van borstweefsel bij mannen."),
("Seksuele Dysfunctie", "Kan libido verminderen of seksuele disfunctie veroorzaken."),
("Hyperkaliëmie", "Verhoogde kaliumspiegels in het bloed."),
("Geheugenproblemen", "Kan geheugenproblemen of verwarring veroorzaken."),
("Verhoogde Hartslag", "Kan tachycardie of een snelle hartslag veroorzaken."),
("Verwardheid", "Kan leiden tot mentale verwarring of desoriëntatie."),
("Irritatie", "Kan leiden tot prikkelbaarheid of stemmingswisselingen."),
("Constipatie", "Kan leiden tot obstipatie of moeilijkheden bij de stoelgang."),
("Verstopping", "Kan leiden tot obstipatie."),
("Verhoogde Cholesterolspiegels", "Kan leiden tot hypercholesterolemie."),
("Verhoogd Risiko op Verslaving", "Kan leiden tot afhankelijkheid bij langdurig gebruik."),
("Maagzweren", "Kan leiden tot de vorming van maagzweren bij langdurig gebruik."),
("Tendinitis", "Kan leiden tot ontsteking van pezen, vooral bij oudere volwassenen."),
("Zenuwschade", "Kan perifere neuropathie of andere zenuwproblemen veroorzaken."),
("Verminderde Appetiet", "Kan leiden tot gewichtsverlies of verminderde eetlust."),
("Tremor", "Kan trillingen of tremoren veroorzaken."),
("Gewichtsverandering", "Kan leiden tot gewichtsverlies of -toename."),
("Keelpijn", "Kan keelpijn of irritatie veroorzaken."),
("Stemmingswisselingen", "Kan leiden tot stemmingswisselingen of prikkelbaarheid."),
("Verhoogde Transpiratie", "Kan overmatig zweten veroorzaken."),
("Moeilijkheden bij Plassen", "Kan leiden tot moeilijkheden bij het plassen of zwakke urinestroom."),
("Psychische Stoornissen", "Zelden kunnen psychische stoornissen zoals depressie of angst optreden."),
("Bruising", "Kan leiden tot gemakkelijk blauwe plekken."),
("Diarree", "Kan diarree of andere spijsverteringsproblemen veroorzaken."),
("Verlies van Water en Zouten", "Kan leiden tot uitdroging en verlies van essentiële zouten."),
("Bloeddrukverlaging", "Kan leiden tot een verlaging van de bloeddruk."),
("Bradycardie", "Kan leiden tot een trage hartslag."),
("Braken", "Kan leiden tot braken of andere spijsverteringsproblemen."),
("Hypotensie", "Kan leiden tot abnormaal lage bloeddruk."),
("Indigestie", "Kan maagpijn of indigestie veroorzaken."),
("Slaapwandelen", "Kan leiden tot slaapwandelen of andere ongewone slaapgedragingen."),
("Verminderde Eetlust", "Kan leiden tot gewichtsverlies of verminderde eetlust."),
("Verhoogde Nierenzymen", "Zeer zelden kan paracetamol de nierfunctie beïnvloeden."),
("Verhoogde Bloeddruk", "Kan leiden tot een lichte verhoging van de bloeddruk."),
("Gevoeligheid voor Zonlicht", "Kan gevoeligheid voor zonlicht vergroten."),
("Laag Bloedglucose", "Zelden kan metformine hypoglykemie veroorzaken, vooral bij combinatie met andere diabetesmedicatie."),
("Acidose", "Zeer zelden kan metformine een metabole acidose veroorzaken."),
("Angio-oedeem", "Zeer zelden kan lisinopril leiden tot angio-oedeem, wat zwelling van gezicht, lippen, tong of keel inhoudt."),
("Hyperkalemie", "Kan leiden tot verhoogde kaliumspiegels in het bloed."),
("Bottenverzwakking", "Langdurig gebruik kan het risico op botbreuken verhogen."),
("Overmatige Blootstelling aan Zonlicht", "Kan gevoeligheid voor zonlicht vergroten.");
("Koorts", "Een lichte tot matige verhoging van de lichaamstemperatuur."),
("Pijn op de Injectieplaats", "Lokale pijn, roodheid of zwelling op de plek van injectie."),
("Anaphylaxie", "Een ernstige, levensbedreigende allergische reactie."),
("Neurologische Symptomen", "Verwarring, hoofdpijn, of andere neurologische klachten."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Overmatig Zweten", "Kan leiden tot overmatig zweten (hyperhidrose)."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Verhoogde Spierpijn", "Kan spierpijn of zwakte veroorzaken."),
("Verhoogde Nierenenzymen", "Kan leiden tot verhoogde nierenenzymwaarden, wat nierfunctiestoornissen kan aangeven."),
("Verhoogde Ziektegevoelens", "Kan leiden tot een algemeen ziek gevoel of malaise."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Verminderde Transpiratie", "Kan overmatig zweten verminderen of stoppen."),
("Roodheid", "Roodheid of irritatie op de injectieplaats."),
("Flauwvallen", "Kan leiden tot flauwvallen of bewustzijnsverlies.");
