INSERT INTO Diagnose(diagnose_code, diagnose_naam, diagnose_datum, diagnose_beschrijving, diagnose_status, Arts_arts_code)
VALUES
(0, "Hypertensie", "2023-04-19", "Een chronische aandoening waarbij de bloeddruk in de slagaders verhoogd is, wat kan leiden tot hartziekten, nierproblemen en beroertes.", "voorlopig", 86),
(1, "Diabetes Mellitus Type 2", "2023-07-06", "Een stofwisselingsziekte waarbij het lichaam weerstand heeft tegen insuline of onvoldoende insuline produceert, resulterend in verhoogde bloedsuikerspiegels.", "voorlopig", 30),
(2, "Astma", "2022-06-08", "Een chronische ontstekingsziekte van de luchtwegen die leidt tot piepende ademhaling, kortademigheid, benauwdheid op de borst en hoesten.", "uitgesloten", 131),
(3, "Depressie", "2023-05-25", "Een stemmingsstoornis gekenmerkt door aanhoudende gevoelens van verdriet, verlies van interesse in dagelijkse activiteiten en verminderde energie.", "chronisch", 141),
(4, "Osteoarthritis", "2023-05-14", "Een degeneratieve gewrichtsaandoening waarbij het kraakbeen in de gewrichten slijt, wat leidt tot pijn, stijfheid en verminderde mobiliteit.", "uitgesloten", 138),
(5, "Coronair Hartziekte", "2022-12-05", "Een aandoening waarbij de kransslagaders vernauwd of geblokkeerd zijn door plaque-opbouw, wat kan leiden tot angina pectoris of hartaanvallen.", "herstellend", 119),
(6, "Chronische Obstructieve Longziekte (COPD)", "2023-03-05", "Een progressieve longaandoening die de luchtstroom belemmert en ademnood veroorzaakt, vaak veroorzaakt door langdurige blootstelling aan irriterende stoffen zoals sigarettenrook.", "uitgesloten", 80),
(7, "Migraine", "2023-05-10", "Een type hoofdpijn gekenmerkt door intense, pulserende pijn, vaak aan één kant van het hoofd, en kan gepaard gaan met misselijkheid, braken en gevoeligheid voor licht en geluid.", "uitgesloten", 90),
(8, "Reumatoïde Artritis", "2022-04-18", "Een auto-immuunziekte die ontsteking van de gewrichten veroorzaakt, wat leidt tot pijn, zwelling, stijfheid en uiteindelijk gewrichtsdeformatie.", "herstellend", 119),
(9, "Gastro-oesofageale Refluxziekte (GERD)", "2023-12-15", "Een spijsverteringsstoornis waarbij maagzuur terugvloeit naar de slokdarm, wat brandend maagzuur en andere ongemakken veroorzaakt.", "in afwachting", 144),
(10, "Hypothyreoïdie", "2023-03-09", "Een aandoening waarbij de schildklier niet genoeg schildklierhormonen produceert, wat kan leiden tot vermoeidheid, gewichtstoename, koude intolerantie en depressie.", "voorlopig", 144),
(11, "Alzheimer", "2024-06-04", "Een progressieve neurologische aandoening die geheugenverlies, verwarring en veranderingen in gedrag en persoonlijkheid veroorzaakt.", "chronisch", 90),
(12, "Anemie", "2024-06-06", "Een bloedziekte waarbij het aantal rode bloedcellen of het hemoglobinegehalte laag is, wat leidt tot vermoeidheid, zwakte en bleekheid.", "herstellend", 80),
(13, "Psoriasis", "2022-11-07", "Een chronische auto-immuunziekte die de huidcellen versnelt, wat resulteert in dikke, rode, schilferige plekken op de huid.", "bevestigd", 30),
(14, "Hartfalen", "2022-10-07", "Een ernstige aandoening waarbij het hart niet in staat is voldoende bloed te pompen om aan de behoeften van het lichaam te voldoen.", "bevestigd", 87),
(15, "Influenza (Griep)", "2022-05-19", "Een virale infectie van de luchtwegen die koorts, hoesten, keelpijn, spierpijn en vermoeidheid veroorzaakt.", "voorlopig", 44),
(16, "Bacteriële Pneumonie", "2023-08-06", "Een longinfectie veroorzaakt door bacteriën, gekenmerkt door koorts, hoesten, kortademigheid en pijn op de borst.", "herstellend", 81),
(17, "Schildklierkanker", "2024-02-10", "Een vorm van kanker die ontstaat in de schildklier, vaak gepaard gaand met knobbels in de hals, moeite met slikken en veranderingen in stem.", "voorlopig", 110),
(18, "Eczema (Atopisch Eczeem)", "2024-04-05", "Een huidziekte die jeukende, ontstoken en rode plekken veroorzaakt, vaak geassocieerd met een familiegeschiedenis van allergieën.", "herstellend", 132),
(19, "Kanker van de Dikke Darm", "2022-11-10", "Een vorm van kanker die begint in de dikke darm of endeldarm, vaak gekenmerkt door veranderingen in stoelgang, bloed in de ontlasting en buikpijn.", "bevestigd", 59),
(20, "Multiple Sclerose (MS)", "2023-12-25", "Een auto-immuunziekte waarbij het immuunsysteem de beschermende myelineschede rond zenuwvezels in de hersenen en het ruggenmerg aanvalt, wat leidt tot spierzwakte, coördinatieproblemen en andere neurologische symptomen.", "voorlopig", 86),
(21, "Bipolaire Stoornis", "2023-01-25", "Een stemmingsstoornis gekenmerkt door afwisselende periodes van manie (extreem hoge stemming) en depressie.", "in afwachting", 118),
(22, "Epilepsie", "2022-12-12", "Een neurologische aandoening die wordt gekenmerkt door terugkerende epileptische aanvallen, veroorzaakt door abnormale elektrische activiteit in de hersenen.", "in afwachting", 86),
(23, "Chronic Kidney Disease (CKD)", "2023-12-08", "Een progressieve afname van de nierfunctie, wat kan leiden tot ophoping van afvalstoffen in het lichaam en uiteindelijk nierfalen.", "voorlopig", 81),
(24, "Hepatitis C", "2024-01-13", "Een virale infectie die de lever aantast en kan leiden tot leverontsteking, cirrose en leverkanker.", "uitgesloten", 59),
(25, "Parkinson", "2022-09-15", "Een progressieve neurologische aandoening die beweging coördineert, gekenmerkt door tremoren, stijfheid, traagheid van beweging en balansproblemen.", "chronisch", 87),
(26, "Lupus (Systemische Lupus Erythematosus)", "2022-06-22", "Een auto-immuunziekte waarbij het immuunsysteem de eigen weefsels en organen aanvalt, wat kan leiden tot ontstekingen en schade aan de huid, gewrichten, nieren, hersenen en andere organen.", "voorlopig", 81),
(27, "Schizofrenie", "2023-01-20", "Een ernstige psychische stoornis die wordt gekenmerkt door vervormde gedachten, wanen, hallucinaties en verminderd functioneren in het dagelijks leven.", "in afwachting", 16),
(28, "Cystic Fibrosis", "2023-08-05", "Een erfelijke aandoening die de longen en het spijsverteringsstelsel aantast, gekenmerkt door dikke slijmen die luchtwegen en organen kunnen verstoppen.", "bevestigd", 81),
(29, "HIV/AIDS", "2023-12-19", "Een virale infectie die het immuunsysteem aantast, waardoor het lichaam vatbaarder wordt voor opportunistische infecties en bepaalde vormen van kanker.", "bevestigd", 80),
(30, "Graves' Disease", "2022-04-12", "Een auto-immuunziekte die hyperthyreoïdie veroorzaakt, wat leidt tot symptomen zoals gewichtsverlies, snelle hartslag, zweten en nervositeit.", "voorlopig", 81),
(31, "Meniscusletsel", "2022-05-13", "Een scheur in de meniscus van de knie, vaak veroorzaakt door draaibewegingen of plotselinge belasting, resulterend in pijn, zwelling en beperkte beweging.", "in afwachting", 53),
(32, "Fibromyalgie", "2022-10-17", "Een chronische aandoening gekenmerkt door wijdverspreide pijn in spieren en bindweefsel, evenals vermoeidheid, slaapstoornissen en cognitieve problemen.", "voorlopig", 50),
(33, "Gout (Jicht)", "2023-07-17", "Een vorm van artritis veroorzaakt door de ophoping van urinezuurkristallen in de gewrichten, wat leidt tot plotselinge, hevige pijn, roodheid en zwelling.", "herstellend", 131),
(34, "Cirrhose", "2022-06-10", "Een ernstige leveraandoening waarbij gezond leverweefsel wordt vervangen door littekenweefsel, wat de leverfunctie belemmert en kan leiden tot leverfalen.", "bevestigd", 145),
(35, "Pancreatitis", "2023-06-06", "Ontsteking van de alvleesklier, vaak veroorzaakt door galstenen of overmatig alcoholgebruik, wat leidt tot buikpijn, misselijkheid en braken.", "uitgesloten", 131),
(36, "Bipolair II", "2022-12-11", "Een subtype van de bipolaire stoornis gekenmerkt door afwisselende perioden van depressie en hypomanie (minder ernstige manische episodes).", "herstellend", 131),
(37, "Narcolepsie", "2023-07-20", "Een chronische slaapstoornis die plotselinge en oncontroleerbare episodes van slaap uitlokken, vaak vergezeld van kataplexie (plotseling verlies van spiercontrole).", "voorlopig", 145),
(38, "Schildklierknobbels", "2024-04-16", "Goedaardige of kwaadaardige gezwellen in de schildklier, die kunnen leiden tot veranderingen in de schildklierfunctie en soms zichtbaar zijn als een knobbel in de hals.", "chronisch", 44),
(39, "Pneumothorax", "2023-02-08", "Een aandoening waarbij lucht zich ophoopt in de pleuraholte, waardoor het long gedeeltelijk of volledig kan samenvallen, wat leidt tot ademnood en pijn op de borst.", "voorlopig", 118),
(40, "Endometriose", "2024-02-03", "Een chronische aandoening waarbij weefsel dat lijkt op het baarmoederslijmvlies buiten de baarmoeder groeit, wat pijn, onregelmatige menstruatie en vruchtbaarheidsproblemen kan veroorzaken.", "chronisch", 138),
(41, "Leukemie", "2024-01-31", "Een type kanker van de bloedcellen die begint in het beenmerg en zich verspreidt naar het bloed, wat leidt tot symptomen zoals vermoeidheid, infecties en bloedingsneigingen.", "in afwachting", 81),
(42, "Acuut Myocardinfarct", "2024-05-09", "Een hartaanval die ontstaat door een plotselinge blokkade van een kransslagader, wat leidt tot beschadiging van de hartspier door zuurstoftekort.", "uitgesloten", 81),
(43, "Celiac Disease (Coeliakie)", "2024-04-09", "Een auto-immuunziekte waarbij de inname van gluten leidt tot schade aan de dunne darm, resulterend in malabsorptie van voedingsstoffen.", "voorlopig", 16),
(44, "Hemofilie", "2023-12-23", "Een erfelijke bloedziekte die de bloedstolling belemmert, wat leidt tot overmatige bloedingen bij verwondingen of zelfs spontane bloedingen.", "voorlopig", 92),
(45, "Pneumoconiose", "2023-12-14", "Een groep longaandoeningen veroorzaakt door langdurige blootstelling aan stofdeeltjes, wat leidt tot littekenvorming in de longen en ademnood.", "uitgesloten", 144),
(46, "Sjogren's Syndroom", "2023-12-26", "Een auto-immuunziekte die voornamelijk de speeksel- en traanklieren aantast, wat leidt tot droge mond en droge ogen.", "bevestigd", 118),
(47, "Hernia (Hernia Lumbaris)", "2023-05-29", "Een aandoening waarbij een deel van een orgaan of weefsel uitpuilt door een verzwakte plek in de omliggende spieren, vaak leidend tot pijn en ongemak.", "chronisch", 90),
(48, "Acute Lymfoblastaire Leukemie (ALL)", "2022-11-05", "Een snel voortschrijdende vorm van leukemie die voornamelijk kinderen treft, gekenmerkt door de overproductie van abnormale lymfoblasten.", "voorlopig", 110),
(49, "Multiple Myeloom", "2023-09-11", "Een type kanker van de plasmacellen in het beenmerg, wat leidt tot botpijn, verhoogd calciumgehalte en nierproblemen.", "voorlopig", 132),
(50, "Polymyalgia Rheumatica", "2023-05-09", "Een ontstekingsaandoening die spierpijn en stijfheid veroorzaakt, vooral in de schouders en heupen, vaak geassocieerd met reumatoïde artritis.", "in afwachting", 44),
(51, "Systemische Sclerosis (Sclerodermie)", "2022-05-31", "Een auto-immuunziekte die leidt tot verharding en verstrakking van de huid en bindweefsel, wat de interne organen kan aantasten.", "uitgesloten", 141),
(52, "Pernicieuze Anemie", "2023-11-30", "Een vorm van anemie veroorzaakt door een tekort aan vitamine B12, wat leidt tot vermoeidheid, zwakte en neurologische symptomen.", "bevestigd", 145),
(53, "Myasthenia Gravis", "2023-04-25", "Een auto-immuunziekte die de signaaloverdracht tussen zenuwen en spieren verstoort, resulterend in spierzwakte en vermoeidheid.", "uitgesloten", 145),
(54, "Kanker van de Alvleesklier", "2023-06-13", "Een agressieve vorm van kanker die in de alvleesklier ontstaat, vaak laat gediagnosticeerd en geassocieerd met buikpijn, gewichtsverlies en geelzucht.", "herstellend", 86),
(55, "Beroerte (CVA)", "2022-07-01", "Een plotselinge onderbreking van de bloedtoevoer naar de hersenen, wat leidt tot hersenbeschadiging, verlamming en cognitieve stoornissen.", "uitgesloten", 92),
(56, "Hartaandoeningen", "2022-12-16", "Een breed scala aan aandoeningen die het hart betreffen, waaronder hartaanvallen, hartfalen en hartritmestoornissen.", "bevestigd", 53),
(57, "Polycysteus Ovarium Syndroom (PCOS)", "2023-01-25", "Een hormonale aandoening bij vrouwen die wordt gekenmerkt door onregelmatige menstruatie, overmatige haargroei en cysten in de eierstokken.", "herstellend", 87),
(58, "Autisme Spectrum Stoornis (ASS)", "2024-04-15", "Een ontwikkelingsstoornis die sociale interactie, communicatie en gedrag beïnvloedt, vaak met repetitieve gedragingen en beperkte interesses.", "bevestigd", 59),
(59, "Longfibrose", "2022-10-28", "Een aandoening waarbij littekenweefsel zich in de longen vormt, wat leidt tot verminderde longfunctie en ademnood.", "voorlopig", 138),
(60, "Achalasie", "2023-07-23", "Een zeldzame slokdarmstoornis waarbij de onderste slokdarmsfincter niet goed ontspant, wat leidt tot moeite met slikken en voedselophoping in de slokdarm.", "in afwachting", 92),
(61, "Borstkanker", "2022-04-08", "Een vorm van kanker die begint in de borstweefsels, vaak gekenmerkt door een knobbel, veranderingen in de borstvorm of huid en afscheiding uit de tepel.", "herstellend", 53),
(62, "Cushing Syndroom", "2022-04-08", "Een hormonale aandoening veroorzaakt door langdurige blootstelling aan hoge niveaus van cortisol, wat leidt tot gewichtstoename, dunne huid en hoge bloeddruk.", "voorlopig", 30),
(63, "Endocriene Hygiëne (Cushing's Disease)", "2023-04-23", "Een specifieke vorm van het Cushing syndroom veroorzaakt door een tumor in de hypofyse die overmatige productie van ACTH stimuleert.", "uitgesloten", 59),
(64, "Schildkliervergroting (Struma)", "2022-05-04", "Een vergroting van de schildklier, die kan worden veroorzaakt door jodiumtekort, auto-immuunziekten of schildklierkanker.", "bevestigd", 44),
(65, "Epiglottitis", "2022-10-01", "Een ontsteking van de epiglottis, vaak veroorzaakt door een bacteriële infectie, wat kan leiden tot ademhalingsproblemen en vereist onmiddellijke medische aandacht.", "uitgesloten", 30),
(66, "Pericarditis", "2023-12-20", "Ontsteking van het pericardium (de buitenste laag van het hart), wat pijn op de borst en koorts kan veroorzaken.", "in afwachting", 90),
(67, "Chondrose", "2024-03-03", "Degeneratie van het kraakbeen in de tussenwervelschijven van de wervelkolom, wat leidt tot rugpijn en bewegingsbeperkingen.", "in afwachting", 70),
(68, "Lyme Disease (Ziekte van Lyme)", "2024-02-22", "Een bacteriële infectie overgedragen door tekenbeten, gekenmerkt door huiduitslag, koorts, hoofdpijn en gewrichtspijn.", "uitgesloten", 53),
(69, "Tendinitis", "2023-03-06", "Ontsteking van een pees, vaak veroorzaakt door overbelasting, wat leidt tot pijn en beperkte beweging in het getroffen gebied.", "bevestigd", 81),
(70, "Obstructieve Slaapapneu", "2022-10-18", "Een slaapstoornis waarbij de luchtwegen herhaaldelijk worden geblokkeerd tijdens de slaap, wat leidt tot ademstilstanden en vermoeidheid overdag.", "chronisch", 110),
(71, "Hemorroïden", "2022-08-22", "Vergrote en ontstoken aderen in het onderste deel van de dikke darm en anus, wat pijn, jeuk en bloedingen kan veroorzaken.", "herstellend", 16),
(72, "Osteoporose", "2023-09-20", "Een aandoening waarbij de botdichtheid vermindert, waardoor de botten broos en breekbaar worden, wat het risico op fracturen verhoogt.", "uitgesloten", 53),
(73, "Diverticulitis", "2024-03-02", "Ontsteking of infectie van divertikels in de dikke darm, wat leidt tot buikpijn, koorts en veranderingen in de stoelgang.", "chronisch", 118),
(74, "Menstruatiestoornissen", "2023-04-29", "Abnormale patronen in de menstruatiecyclus, zoals onregelmatige menstruatie, hevige bloedingen of het uitblijven van menstruatie.", "chronisch", 145),
(75, "Prostaatkanker", "2023-04-06", "Een vorm van kanker die ontstaat in de prostaat, een klier die deel uitmaakt van het mannelijk voortplantingssysteem, vaak gekenmerkt door moeite met plassen en bloed in de urine.", "voorlopig", 138),
(76, "Dermatitis", "2024-04-16", "Ontsteking van de huid die roodheid, jeuk, zwelling en blaarvorming kan veroorzaken, vaak veroorzaakt door allergieën of irritanten.", "herstellend", 50),
(77, "Borstpijn (Angina Pectoris)", "2023-11-14", "Pijn of ongemak op de borst veroorzaakt door onvoldoende bloedtoevoer naar het hart, vaak een symptoom van coronair hartziekte.", "bevestigd", 80),
(78, "Schildklieritis", "2024-04-30", "Ontsteking van de schildklier, wat kan leiden tot tijdelijke veranderingen in de schildklierfunctie en symptomen zoals pijn in de hals en koorts.", "chronisch", 86),
(79, "Bursitis", "2024-03-03", "Ontsteking van een slijmbeurs (bursa), meestal in een gewricht, wat leidt tot pijn en beperkte beweging.", "voorlopig", 119),
(80, "Pancreasinsufficiëntie", "2022-10-21", "Een aandoening waarbij de alvleesklier niet genoeg enzymen produceert om voedsel goed te verteren, wat leidt tot gewichtsverlies en malabsorptie.", "voorlopig", 53),
(81, "Migraine zonder Aura", "2022-12-06", "Een type migraine waarbij de hoofdpijn niet voorafgegaan wordt door neurologische symptomen zoals visuele verstoringen.", "uitgesloten", 16),
(82, "Spina Bifida", "2022-09-12", "Een aangeboren defect waarbij de wervelkolom en het ruggenmerg zich niet volledig ontwikkelen, wat kan leiden tot fysieke en neurologische complicaties.", "in afwachting", 50),
(83, "Aangeboren Hartafwijking", "2023-08-10", "Een structurele afwijking van het hart die aanwezig is bij de geboorte, wat kan variëren van mild tot levensbedreigend.", "voorlopig", 90),
(84, "Glaucoom", "2023-01-26", "Een oogziekte die schade toebrengt aan de oogzenuw, vaak geassocieerd met verhoogde oogdruk, wat kan leiden tot verlies van gezichtsvermogen.", "herstellend", 138),
(85, "Cystitis", "2022-04-16", "Een ontsteking van de blaas, meestal veroorzaakt door een bacteriële infectie, wat leidt tot pijn bij het plassen en frequente aandrang om te plassen.", "voorlopig", 92),
(86, "Spierziekten", "2023-10-01", "Een groep aandoeningen die de spieren aantasten, wat leidt tot spierzwakte, spasticiteit en verminderde spierfunctie.", "bevestigd", 86),
(87, "Migraine met Aura", "2023-08-25", "Een type migraine waarbij de hoofdpijn voorafgegaan wordt door neurologische symptomen zoals visuele verstoringen, tintelingen of spraakproblemen.", "voorlopig", 138),
(88, "Morbus Crohn", "2023-04-21", "Een chronische inflammatoire darmziekte die elke laag van het maagdarmkanaal kan aantasten, wat leidt tot buikpijn, diarree en gewichtsverlies.", "voorlopig", 138),
(89, "Cushing's Disease", "2023-11-24", "Een specifieke vorm van het Cushing-syndroom veroorzaakt door een tumor in de hypofyse die overmatige productie van ACTH stimuleert.", "in afwachting", 44),
(90, "Gastritis", "2022-12-18", "Ontsteking van het maagslijmvlies, vaak veroorzaakt door infecties, overmatig alcoholgebruik of langdurig gebruik van NSAID's, wat leidt tot maagpijn en misselijkheid.", "in afwachting", 59),
(91, "Diverticulose", "2023-09-29", "De aanwezigheid van divertikels (kleine uitstulpingen) in de dikke darm zonder ontsteking, vaak asymptomatisch maar kan leiden tot diverticulitis.", "voorlopig", 90),
(92, "Hartklepaandoeningen", "2022-11-10", "Aandoeningen die de hartkleppen aantasten, wat kan leiden tot problemen zoals lekkende of vernauwde kleppen en verminderde hartfunctie.", "chronisch", 138),
(93, "Spina Ventosa", "2022-06-28", "Een vorm van tuberculose die de botten aantast, vaak leidend tot zwelling en vervorming van de aangetaste botten.", "in afwachting", 80),
(94, "Genu Valgum (Knock-Knees)", "2023-06-24", "Een standafwijking van de knieën waarbij de knieën naar elkaar toe buigen en de enkels uit elkaar staan.", "voorlopig", 141),
(95, "Hyperlipidemie", "2024-03-06", "Een aandoening gekenmerkt door verhoogde niveaus van lipiden (zoals cholesterol en triglyceriden) in het bloed, wat het risico op hartziekten verhoogt.", "bevestigd", 50),
(96, "Epilepsie (Absence Seizures)", "2023-10-21", "Een subtype van epilepsie gekenmerkt door korte periodes van bewusteloosheid of 'afwezigheid', vaak zonder convulsies.", "chronisch", 144),
(97, "Acuut Renale Insufficiëntie", "2023-09-10", "Een plotselinge daling van de nierfunctie, wat leidt tot ophoping van afvalstoffen en vocht in het lichaam.", "uitgesloten", 80),
(98, "Cholesterol Gallstones", "2024-02-17", "Stenen die zich vormen in de galblaas uit cholesterol, wat kan leiden tot pijn, infecties en obstructie van de galwegen.", "bevestigd", 119),
(99, "Vasculitis", "2023-01-21", "Ontsteking van bloedvaten, wat kan leiden tot beschadiging van de vaatwanden en verminderde bloedstroom naar organen en weefsels.", "herstellend", 86),
(100, "Periode pijn (Dysmenorroe)", "2022-07-10", "Pijn en krampen in de onderbuik voorafgaand aan of tijdens de menstruatie, variërend van mild tot ernstig.", "bevestigd", 144),
(101, "Appendicitis", "2023-05-26", "Ontsteking van de appendix, wat leidt tot acute buikpijn, meestal vereist het chirurgisch verwijderen van de appendix.", "in afwachting", 30),
(102, "Ziekte van Huntington", "2023-06-03", "Een erfelijke neurodegeneratieve aandoening die leidt tot progressieve motorische, cognitieve en psychiatrische symptomen.", "chronisch", 131),
(103, "Herniated Disc", "2023-11-14", "Een aandoening waarbij de gelachtige kern van een tussenwervelschijf door de buitenste vezelring breekt, wat druk kan uitoefenen op zenuwen en pijn veroorzaakt.", "herstellend", 110),
(104, "Acuut Pancreasinsufficiëntie", "2022-10-18", "Een plotselinge vermindering van de alvleesklierfunctie, wat leidt tot problemen met de spijsvertering en absorptie van voedingsstoffen.", "bevestigd", 138),
(105, "Cystitis Interstitialis", "2023-10-26", "Een chronische ontsteking van de blaaswand zonder infectie, wat leidt tot frequente en pijnlijke aandrang om te plassen.", "herstellend", 80),
(106, "Narcolepsie met Kataplexie", "2024-04-19", "Een type narcolepsie waarbij episodes van spierzwakte of -verlamming optreden als reactie op sterke emoties.", "herstellend", 119),
(107, "Herpes Simplex", "2022-12-08", "Een virale infectie die huid- en slijmvlieslaesies veroorzaakt, vaak rond de mond of geslachtsdelen.", "bevestigd", 144),
(108, "Anorexia Nervosa", "2024-05-10", "Een eetstoornis gekenmerkt door een intense angst om aan te komen, wat leidt tot extreme gewichtsverlies en gevaarlijke gewoonten om gewicht te verliezen.", "uitgesloten", 80),
(109, "Bulimia Nervosa", "2022-09-16", "Een eetstoornis gekenmerkt door herhaalde episodes van eetbuien gevolgd door compensatoire gedragingen zoals braken, vasten of overmatige lichaamsbeweging.", "bevestigd", 141),
(110, "Bronchiolitis", "2023-11-05", "Een ontsteking van de kleine luchtwegen in de longen, vaak veroorzaakt door virale infecties, wat leidt tot hoesten, piepende ademhaling en ademhalingsmoeilijkheden.", "herstellend", 50),
(111, "Hernia Diaphragma", "2023-03-28", "Een aandoening waarbij een deel van de maag of andere organen omhoog schuiven naar de borstholte door een opening in het middenrif.", "uitgesloten", 141),
(112, "Chondrosarcoom", "2023-10-27", "Een type botkanker dat ontstaat in het kraakbeen, wat leidt tot pijn en zwelling in het aangetaste gebied.", "bevestigd", 92),
(113, "Discus Hernia", "2023-12-26", "Een aandoening waarbij de tussenwervelschijf uitpuilt en druk uitoefent op zenuwen, wat leidt tot rugpijn en mogelijk uitstralende pijn naar de ledematen.", "herstellend", 110),
(114, "Leber's Hereditary Optic Neuropathy", "2024-02-02", "Een mitochondriale aandoening die leidt tot plotseling verlies van centrale visie door schade aan de oogzenuw.", "in afwachting", 87),
(115, "Osteomyelitis", "2023-12-09", "Een botinfectie die kan leiden tot pijn, zwelling, roodheid en soms koorts, vaak veroorzaakt door bacteriën.", "in afwachting", 81),
(116, "Amyotrofische Laterale Sclerose (ALS)", "2023-07-01", "Een progressieve neurodegeneratieve ziekte die de zenuwcellen in de hersenen en het ruggenmerg aantast, wat leidt tot spierzwakte en verlamming.", "uitgesloten", 16),
(117, "Chronic Fatigue Syndrome (CFS)", "2023-04-29", "Een complexe aandoening gekenmerkt door extreme vermoeidheid die niet verbetert met rust en die verergert bij fysieke of mentale activiteit.", "herstellend", 119),
(118, "Idiopathische Longfibrose", "2023-01-02", "Een progressieve longaandoening zonder bekende oorzaak, gekenmerkt door littekenvorming in de longen en ademnood.", "voorlopig", 90),
(119, "Acute Bronchitis", "2023-09-05", "Een tijdelijke ontsteking van de luchtwegen in de longen, vaak veroorzaakt door virale infecties, wat leidt tot hoesten en ademhalingsproblemen.", "chronisch", 138),
(120, "Vitiligo", "2023-10-27", "Een huidziekte waarbij pigmentcellen worden vernietigd, wat leidt tot witte vlekken op de huid.", "in afwachting", 110),
(121, "Lymfomen", "2023-08-11", "Een groep van bloedkankers die ontstaan in het lymfestelsel, wat leidt tot symptomen zoals gezwollen lymfeklieren, koorts en gewichtsverlies.", "voorlopig", 16),
(122, "Chondromalacie Patellae", "2023-02-14", "Verslapping of beschadiging van het kraakbeen onder de knieschijf, wat leidt tot kniepijn en knarsende geluiden bij beweging.", "bevestigd", 92),
(123, "Kataract", "2024-03-03", "Een vertroebeling van de ooglens, wat leidt tot verminderde gezichtshelderheid en, indien niet behandeld, blindheid.", "uitgesloten", 80),
(124, "Endocarditis", "2023-11-03", "Een infectie van het binnenste membraan van het hart (endocardium), vaak veroorzaakt door bacteriën, wat leidt tot koorts, hartgeruis en vermoeidheid.", "in afwachting", 44),
(125, "Pneumothorax Spontaan", "2023-09-28", "Een plotselinge inzakking van de long zonder duidelijke oorzaak, wat leidt tot ademhalingsproblemen en pijn op de borst.", "in afwachting", 30),
(126, "Schildklierectomie Complicaties", "2023-04-04", "Complicaties na chirurgische verwijdering van de schildklier, zoals hypocalciëmie, schade aan de stembanden en infecties.", "voorlopig", 132),
(127, "Dermatofytose (Ringworm)", "2023-12-16", "Een schimmelinfectie van de huid, haar of nagels, gekenmerkt door ronde, jeukende, rode plekken.", "in afwachting", 86),
(128, "Incontinentie Urinair", "2023-05-05", "Onvrijwillig verlies van urine, wat kan variëren van subtiele lekkages tot volledige controleverlies over de blaas.", "chronisch", 80),
(129, "Systemische Aspergillose", "2024-02-01", "Een ernstige schimmelinfectie die verschillende organen kan aantasten, vaak bij mensen met een verzwakt immuunsysteem.", "herstellend", 110),
(130, "Tourette Syndroom", "2022-11-05", "Een neurologische aandoening gekenmerkt door onvrijwillige bewegingen en vocalisaties, bekend als tics.", "herstellend", 59),
(131, "Hartaandoeningen bij Sporters", "2022-06-07", "Aandoeningen zoals hypertrofische cardiomyopathie die risico's met zich meebrengen bij fysieke inspanning.", "herstellend", 138),
(132, "Cervicale Spondylose", "2024-03-13", "Degeneratieve veranderingen in de nekwervels en tussenwervelschijven, wat leidt tot nekpijn en soms zenuwcompressie.", "in afwachting", 87),
(133, "Cervicitis", "2023-03-24", "Ontsteking van de baarmoederhals, vaak veroorzaakt door infecties zoals chlamydia of gonorroe.", "in afwachting", 145),
(134, "Laryngitis", "2023-02-25", "Ontsteking van het strottenhoofd, wat leidt tot heesheid, verlies van stem en keelpijn.", "herstellend", 131),
(135, "Cholecystitis", "2023-08-31", "Ontsteking van de galblaas, vaak veroorzaakt door galstenen, wat leidt tot buikpijn, koorts en misselijkheid.", "voorlopig", 144),
(136, "Hemolytische Anemie", "2023-02-04", "Een type anemie waarbij rode bloedcellen sneller worden afgebroken dan ze worden aangemaakt, wat leidt tot vermoeidheid en bleekheid.", "herstellend", 87),
(137, "Bronchiectasis", "2024-02-02", "Een aandoening waarbij de luchtwegen permanent verwijden en ontstoken raken, wat leidt tot chronische hoest en sputumproductie.", "chronisch", 16),
(138, "Acuut Lymfatisch Leukemie", "2024-02-03", "Een snelle vorm van leukemie die zich ontwikkelt vanuit onrijpe lymfocyten, vaak bij kinderen.", "bevestigd", 16),
(139, "Hypoglykemie", "2023-08-16", "Een aandoening waarbij de bloedglucosewaarden te laag zijn, wat leidt tot symptomen zoals zweten, beven, verwarring en in ernstige gevallen bewusteloosheid.", "chronisch", 59),
(140, "Chondroepifysitis", "2022-06-30", "Ontsteking van de groeischijven in de botten, vaak voorkomend bij adolescenten en leidend tot pijn en groei-gerelateerde klachten.", "uitgesloten", 131),
(141, "Cervicale Radiculopathie", "2023-09-30", "Compressie of irritatie van een zenuwwortel in de nek, wat leidt tot pijn, gevoelloosheid of zwakte in de armen.", "herstellend", 141),
(142, "Kanker van de Luchtpijp", "2022-09-15", "Een zeldzame vorm van kanker die ontstaat in de luchtpijp, gekenmerkt door hoesten, ademnood en gewichtsverlies.", "uitgesloten", 110),
(143, "Multiple Endocrine Neoplasia", "2022-05-16", "Een groep erfelijke aandoeningen die leiden tot tumoren in verschillende endocriene klieren, zoals de schildklier, bijnieren en alvleesklier.", "herstellend", 92),
(144, "Pancreaskanker", "2023-01-03", "Een agressieve vorm van kanker die in de alvleesklier ontstaat, vaak laat gediagnosticeerd en geassocieerd met buikpijn, gewichtsverlies en geelzucht.", "chronisch", 30),
(145, "Rectale Prolaps", "2022-11-02", "Een aandoening waarbij het rectum uit de anus uitpuilt, wat leidt tot ongemak, pijn en mogelijke incontinentie.", "in afwachting", 110),
(146, "Spina Bifida", "2023-02-15", "Een aangeboren defect waarbij de wervelkolom en het ruggenmerg zich niet volledig ontwikkelen, wat kan leiden tot fysieke en neurologische complicaties.", "voorlopig", 59),
(147, "Morbus Parkinson", "2022-11-05", "Een progressieve neurologische aandoening die beweging coördineert, gekenmerkt door tremoren, stijfheid, traagheid van beweging en balansproblemen.", "uitgesloten", 141),
(148, "Hypogonadisme", "2023-02-11", "Een aandoening waarbij de geslachtsklieren niet voldoende geslachtshormonen produceren, wat leidt tot verminderde seksuele functie en ontwikkeling.", "herstellend", 87),
(149, "Retinitis Pigmentosa", "2023-03-28", "Een groep erfelijke oogziekten die leiden tot degeneratie van het netvlies, wat resulteert in geleidelijk verlies van gezichtsvermogen.", "bevestigd", 144),
(150, "Cervicale Myelopathie", "2022-06-14", "Compressie van het ruggenmerg in de nek, wat leidt tot symptomen zoals zwakte, gevoelloosheid en verminderde coördinatie in de ledematen.", "herstellend", 44),
(151, "Adrenocorticotropin (ACTH) Overproductie", "2022-05-27", "Een hormonale aandoening waarbij de hypofyse te veel ACTH produceert, wat kan leiden tot Cushing-syndroom.", "voorlopig", 53),
(152, "Acuut Gynaecologische Infecties", "2023-06-28", "Snelle ontwikkeling van infecties in het vrouwelijke voortplantingssysteem, wat leidt tot pijn, koorts en andere systemische symptomen.", "bevestigd", 141),
(153, "Postpartum Depressie", "2023-12-24", "Een ernstige vorm van depressie die optreedt na de bevalling, gekenmerkt door intense verdriet, angst en verminderde functionaliteit.", "herstellend", 86),
(154, "Hypopituitarisme", "2022-08-27", "Een aandoening waarbij de hypofyse niet genoeg van één of meer van haar hormonen produceert, wat leidt tot diverse hormonale tekorten.", "chronisch", 87),
(155, "Atopische Dermatitis", "2024-06-04", "Een vorm van eczeem die wordt gekenmerkt door chronische, jeukende, ontstoken huiduitslag, vaak geassocieerd met allergieën.", "chronisch", 92),
(156, "Myocarditis", "2023-10-30", "Ontsteking van de hartspier, vaak veroorzaakt door virale infecties, wat kan leiden tot hartfalen en hartritmestoornissen.", "uitgesloten", 30),
(157, "Scoliose", "2022-05-30", "Een abnormale kromming van de wervelkolom, wat kan leiden tot rugpijn, verminderde longfunctie en esthetische veranderingen.", "bevestigd", 119),
(158, "Kanker van de Lever", "2022-09-05", "Een vorm van kanker die begint in de lever, vaak geassocieerd met levercirrose en hepatitis-infecties.", "voorlopig", 16),
(159, "Interstitiële Longziekte", "2022-09-11", "Een groep longaandoeningen die het interstitium van de longen aantasten, wat leidt tot littekenvorming en ademnood.", "voorlopig", 138),
(160, "Acuut Gastro-enteritis", "2023-12-15", "Een plotselinge ontsteking van de maag en darmen, meestal veroorzaakt door virale of bacteriële infecties, wat leidt tot braken en diarree.", "herstellend", 50),
(161, "Hemochromatose", "2024-04-30", "Een erfelijke aandoening waarbij het lichaam te veel ijzer absorbeert, wat leidt tot ijzeroverbelasting en schade aan organen zoals de lever en het hart.", "uitgesloten", 131),
(162, "Sjogren's Syndrome", "2022-08-21", "Een auto-immuunziekte die voornamelijk de speeksel- en traanklieren aantast, wat leidt tot droge mond en droge ogen.", "voorlopig", 138),
(163, "Bursitis Olecrani", "2023-08-27", "Ontsteking van de slijmbeurs bij de elleboog, wat leidt tot pijn en zwelling aan de achterkant van de elleboog.", "chronisch", 59),
(164, "Cervicale Hernia", "2022-08-19", "Een aandoening waarbij een tussenwervelschijf in de nek uitpuilt, wat kan leiden tot pijn, gevoelloosheid en zwakte in de armen.", "bevestigd", 145),
(165, "Anterieure Meningitis", "2023-08-17", "Ontsteking van de hersenvliezen aan de voorkant, vaak veroorzaakt door bacteriële infecties, wat leidt tot hoofdpijn, koorts en nekstijfheid.", "bevestigd", 145),
(166, "Spleenfunctiestoornis", "2022-04-25", "Een aandoening waarbij de milt niet goed functioneert, wat kan leiden tot verhoogde vatbaarheid voor infecties en bloedafwijkingen.", "uitgesloten", 145),
(167, "Acuut Otitis Media", "2022-10-13", "Een plotselinge ontsteking van het middenoor, vaak veroorzaakt door bacteriële infecties, wat leidt tot oorpijn en soms koorts.", "bevestigd", 81),
(168, "Disautonomia", "2023-09-10", "Een groep aandoeningen waarbij het autonome zenuwstelsel niet goed functioneert, wat leidt tot problemen met hartslag, bloeddruk en spijsvertering.", "in afwachting", 81),
(169, "Cushing's Syndrome", "2022-08-24", "Een hormonale aandoening veroorzaakt door langdurige blootstelling aan hoge niveaus van cortisol, wat leidt tot symptomen zoals gewichtstoename, dunne huid en hoge bloeddruk.", "uitgesloten", 145),
(170, "Hyperthyreoïdie", "2023-07-13", "Een aandoening waarbij de schildklier te veel schildklierhormonen produceert, wat leidt tot symptomen zoals gewichtsverlies, snelle hartslag, zweten en nervositeit.", "uitgesloten", 118),
(171, "Periostitis", "2023-04-26", "Ontsteking van het periost (het bindweefsel rond botten), vaak veroorzaakt door overbelasting of infectie, wat leidt tot pijn en zwelling.", "herstellend", 118),
(172, "Amyloïdose", "2022-08-05", "Een zeldzame aandoening waarbij abnormale eiwitafzettingen (amyloïden) zich ophopen in organen en weefsels, wat hun functie belemmert.", "herstellend", 53),
(173, "Chondritis", "2022-08-26", "Ontsteking van het kraakbeen, wat leidt tot pijn, zwelling en stijfheid in de aangetaste gebieden.", "voorlopig", 138),
(174, "Hypogammaglobulinemie", "2023-04-23", "Een aandoening waarbij het lichaam niet genoeg antilichamen produceert, wat leidt tot verhoogde vatbaarheid voor infecties.", "bevestigd", 132),
(175, "Hyperlipidemie", "2024-03-02", "Een aandoening gekenmerkt door verhoogde niveaus van lipiden (zoals cholesterol en triglyceriden) in het bloed, wat het risico op hartziekten verhoogt.", "in afwachting", 138),
(176, "Rheumatoïde Artritis", "2023-01-31", "Een auto-immuunziekte die ontsteking van de gewrichten veroorzaakt, wat leidt tot pijn, zwelling, stijfheid en uiteindelijk gewrichtsdeformatie.", "bevestigd", 118),
(177, "Nephrotisch Syndroom", "2024-06-03", "Een groep symptomen die optreden als gevolg van schade aan de glomeruli in de nieren, wat leidt tot eiwitverlies in de urine, vochtretentie en hoge cholesterolwaarden.", "in afwachting", 87),
(178, "Polycysteus Nier Syndroom", "2022-06-26", "Een erfelijke aandoening waarbij zich meerdere cysten vormen in de nieren, wat leidt tot nierfunctiestoornissen en hoge bloeddruk.", "voorlopig", 90),
(179, "Hemorragische Diathese", "2022-10-25", "Een aandoening die de bloedstolling belemmert, wat leidt tot overmatige bloedingen bij verwondingen of spontaan.", "in afwachting", 131),
(180, "Acuut Renal Failure", "2023-12-24", "Een plotselinge vermindering van de nierfunctie, wat leidt tot ophoping van afvalstoffen en vocht in het lichaam.", "voorlopig", 90),
(181, "Hypertensieve Hartziekte", "2022-07-20", "Hartziekten veroorzaakt door langdurige hoge bloeddruk, wat kan leiden tot hartfalen, coronaire hartziekte en andere complicaties.", "uitgesloten", 138),
(182, "Chondrosarcoom", "2022-07-31", "Een type botkanker dat ontstaat in het kraakbeen, wat leidt tot pijn en zwelling in het aangetaste gebied.", "voorlopig", 50),
(183, "Endometrioom", "2022-10-11", "Een type cyste dat zich vormt in de eierstokken als gevolg van endometriose, wat kan leiden tot pijn en onvruchtbaarheid.", "uitgesloten", 53),
(184, "Kanker van de Maag", "2023-06-22", "Een vorm van kanker die ontstaat in de maagwand, vaak geassocieerd met symptomen zoals buikpijn, misselijkheid en gewichtsverlies.", "chronisch", 138),
(185, "Rhabdomyolyse", "2022-11-22", "Een aandoening waarbij beschadigde spierweefsels hun inhoud afgeven in de bloedbaan, wat kan leiden tot nierbeschadiging en andere complicaties.", "in afwachting", 30),
(186, "Torticollis", "2023-01-31", "Een aandoening waarbij de nek zijwaarts draait en omhoog of omlaag buigt, wat leidt tot pijn en beperkte bewegingsvrijheid.", "chronisch", 110),
(187, "Adrenomedullair Tumor", "2023-06-03", "Een zeldzame tumor die ontstaat in het bijniermerg, wat leidt tot overproductie van hormonen zoals adrenaline.", "voorlopig", 145),
(188, "Pneumonia", "2024-05-21", "Een longinfectie die de alveoli (longblaasjes) vult met vocht of pus, wat leidt tot hoesten, koorts en ademhalingsmoeilijkheden.", "voorlopig", 145),
(189, "Otitis Externa", "2022-11-12", "Een ontsteking van de gehoorgang, vaak veroorzaakt door bacteriële infecties of irritatie, wat leidt tot oorpijn en jeuk.", "in afwachting", 119),
(190, "Sinusitis", "2023-09-26", "Ontsteking van de sinussen, vaak veroorzaakt door infecties, wat leidt tot hoofdpijn, drukgevoel in het gezicht en verstopte neus.", "chronisch", 131),
(191, "Lymfangitis", "2022-09-27", "Ontsteking van de lymfevaten, vaak veroorzaakt door bacteriële infecties, wat leidt tot roodheid, zwelling en pijn langs de lymfebanen.", "in afwachting", 30),
(192, "Rhabdomyolysis", "2022-05-08", "Een ernstige aandoening waarbij spierweefsel beschadigd raakt en myoglobine in het bloed vrijkomt, wat kan leiden tot nierfalen.", "uitgesloten", 80),
(193, "Pancreas Insufficiency", "2022-12-21", "Een aandoening waarbij de alvleesklier niet genoeg enzymen produceert om voedsel goed te verteren, wat leidt tot gewichtsverlies en malabsorptie.", "uitgesloten", 80),
(194, "Meningitis", "2022-06-12", "Ontsteking van de hersenvliezen, vaak veroorzaakt door bacteriële of virale infecties, wat leidt tot hoofdpijn, koorts en nekstijfheid.", "uitgesloten", 110),
(195, "Glaucoma", "2024-05-25", "Een oogziekte die schade toebrengt aan de oogzenuw, vaak geassocieerd met verhoogde oogdruk, wat kan leiden tot verlies van gezichtsvermogen.", "chronisch", 119),
(196, "Ventricular Tachycardia", "2023-01-07", "Een snelle hartritmeafwijking die ontstaat in de ventrikels, wat kan leiden tot hartkloppingen, duizeligheid en in ernstige gevallen hartstilstand.", "voorlopig", 87),
(197, "Paget's Disease of Bone", "2022-11-14", "Een chronische aandoening die de normale cyclus van botafbraak en -opbouw verstoort, wat leidt tot verzwakking en vervorming van de botten.", "bevestigd", 138),
(198, "Hepatische Encefalopathie", "2022-07-31", "Een aandoening waarbij de lever niet goed functioneert, waardoor toxines zich ophopen in de hersenen en leiden tot verwardheid, slaperigheid en coma.", "bevestigd", 70),
(199, "Ankylosing Spondylitis", "2023-12-26", "Een chronische ontstekingsziekte die voornamelijk de wervelkolom en de heupgewrichten aantast, wat leidt tot pijn en stijfheid.", "bevestigd", 119),
(200, "Sjogren's Syndrome", "2023-04-06", "Een auto-immuunziekte die voornamelijk de speeksel- en traanklieren aantast, wat leidt tot droge mond en droge ogen.", "bevestigd", 53),
(201, "Acuut Myocarditis", "2024-01-27", "Ontsteking van de hartspier, vaak veroorzaakt door virale infecties, wat kan leiden tot hartfalen en hartritmestoornissen.", "in afwachting", 145),
(202, "Spondylolisthesis", "2024-03-01", "Een aandoening waarbij een wervel in de wervelkolom verschuift ten opzichte van de aangrenzende wervels, wat leidt tot rugpijn en zenuwcompressie.", "in afwachting", 87),
(203, "Preeclampsie", "2022-07-19", "Een complicatie tijdens de zwangerschap gekenmerkt door hoge bloeddruk en tekenen van schade aan andere organen, vaak de nieren.", "herstellend", 50),
(204, "Hypersensitiviteit Reactions", "2023-09-12", "Overgevoeligheidsreacties van het immuunsysteem op allergenen, wat kan leiden tot symptomen zoals jeuk, zwelling en ademhalingsproblemen.", "in afwachting", 81),
(205, "HIV-assozieerde Kaposi Sarcoom", "2023-01-12", "Een type kanker dat vaak voorkomt bij mensen met een verzwakt immuunsysteem door HIV-infectie, gekenmerkt door bruine of paarse huidlaesies.", "chronisch", 70),
(206, "Endocriene Neoplasma", "2022-11-28", "Tumoren die ontstaan in endocriene klieren, wat leidt tot overproductie van hormonen en diverse hormonale symptomen.", "voorlopig", 44),
(207, "Acuut Dialyse", "2022-07-22", "Een noodprocedure waarbij de nierfunctie tijdelijk wordt vervangen bij acuut nierfalen, wat helpt bij het verwijderen van afvalstoffen en overtollig vocht.", "bevestigd", 59),
(208, "Vascular Dementia", "2023-07-08", "Een vorm van dementie veroorzaakt door verminderde bloedtoevoer naar de hersenen, wat leidt tot cognitieve achteruitgang en geheugenverlies.", "herstellend", 50),
(209, "Necrotizing Fasciitis", "2024-03-19", "Een ernstige bacteriële infectie die snel het bindweefsel en de huid aantast, wat leidt tot ernstige weefselvernietiging en vereist onmiddellijke medische interventie.", "bevestigd", 59),
(210, "Obstructieve Hartaandoeningen", "2022-08-23", "Aandoeningen waarbij de bloedstroom naar het hart wordt belemmerd, wat kan leiden tot angina pectoris en hartaanvallen.", "chronisch", 59),
(211, "Basocellulair Carcinoom", "2023-11-25", "Een veelvoorkomende vorm van huidkanker die ontstaat in de basale cellen van de huid, gekenmerkt door langzaam groeiende, onschadelijke tumoren.", "herstellend", 145),
(212, "Contact Dermatitis", "2024-06-14", "Een huidontsteking veroorzaakt door direct contact met een irriterende stof of allergeen, wat leidt tot roodheid, jeuk en zwelling.", "in afwachting", 80),
(213, "Legg-Calvé-Perthes Disease", "2023-10-15", "Een aandoening bij kinderen waarbij de bloedtoevoer naar het dijbeen (femur) tijdelijk wordt onderbroken, wat leidt tot botafbraak en vervorming.", "chronisch", 80),
(214, "Cystische Fibrose", "2023-08-18", "Een erfelijke aandoening die de longen en het spijsverteringsstelsel aantast, gekenmerkt door dikke slijmen die luchtwegen en organen kunnen verstoppen.", "herstellend", 50),
(215, "Glomerulonefritis", "2022-06-22", "Ontsteking van de glomeruli in de nieren, wat leidt tot bloed in de urine, eiwitverlies en verminderde nierfunctie.", "chronisch", 144),
(216, "Staphylococcal Infections", "2024-02-02", "Infecties veroorzaakt door Staphylococcus-bacteriën, wat kan leiden tot huidinfecties, bloedvergiftiging en longontsteking.", "herstellend", 119),
(217, "Hypogonadotrof Hypogonadisme", "2023-07-13", "Een aandoening waarbij de hypofyse niet genoeg gonadotroop hormonen produceert, wat leidt tot verminderde geslachtshormoonproductie.", "chronisch", 132),
(218, "Varices", "2022-12-10", "Uitgezette en gezwollen aderen, vaak in de benen, wat kan leiden tot pijn, zwelling en huidproblemen.", "bevestigd", 144),
(219, "Kanker van de Alvleesklier", "2024-04-19", "Een agressieve vorm van kanker die in de alvleesklier ontstaat, vaak laat gediagnosticeerd en geassocieerd met buikpijn, gewichtsverlies en geelzucht.", "in afwachting", 30),
(220, "Mastitis", "2022-12-22", "Ontsteking van het borstweefsel, vaak veroorzaakt door een infectie, wat leidt tot pijn, roodheid en zwelling in de borst.", "chronisch", 86),
(221, "Eosinofiele Astma", "2024-06-11", "Een subtype van astma gekenmerkt door een hoge concentratie eosinofielen (een type witte bloedcellen) in de luchtwegen, wat leidt tot ontsteking en ademhalingsproblemen.", "voorlopig", 90),
(222, "Acuut Myocarditis", "2022-10-18", "Ontsteking van de hartspier, vaak veroorzaakt door virale infecties, wat kan leiden tot hartfalen en hartritmestoornissen.", "in afwachting", 87),
(223, "Hyperaldosteronisme", "2022-04-08", "Een aandoening waarbij de bijnieren te veel aldosteron produceren, wat leidt tot hoge bloeddruk en een verstoorde elektrolytenbalans.", "herstellend", 86),
(224, "Mastocytose", "2023-01-31", "Een zeldzame aandoening waarbij het lichaam te veel mestcellen produceert, wat kan leiden tot anafylactische reacties, huiduitslag en buikpijn.", "uitgesloten", 50),
(225, "Sjogren's Syndrome", "2023-12-25", "Een auto-immuunziekte die voornamelijk de speeksel- en traanklieren aantast, wat leidt tot droge mond en droge ogen.", "herstellend", 145),
(226, "Leukocytose", "2023-09-27", "Een verhoogd aantal witte bloedcellen in het bloed, wat kan wijzen op infecties, ontstekingen of andere medische aandoeningen.", "chronisch", 44),
(227, "Cervicitis", "2024-05-23", "Ontsteking van de baarmoederhals, vaak veroorzaakt door infecties zoals chlamydia of gonorroe.", "in afwachting", 70),
(228, "Neurofibromatose", "2024-06-02", "Een genetische aandoening die tumoren op de zenuwen veroorzaakt, wat kan leiden tot huidveranderingen, botafwijkingen en neurologische symptomen.", "voorlopig", 53),
(229, "Acute Glomerulonefritis", "2022-11-16", "Een plotselinge ontsteking van de glomeruli in de nieren, wat leidt tot bloed in de urine, eiwitverlies en verminderde nierfunctie.", "herstellend", 145),
(230, "Cervicale Hernia", "2023-08-31", "Een aandoening waarbij een tussenwervelschijf in de nek uitpuilt, wat kan leiden tot pijn, gevoelloosheid en zwakte in de armen.", "uitgesloten", 119),
(231, "Acuut Pancreatitis", "2024-05-12", "Ontsteking van de alvleesklier, vaak veroorzaakt door galstenen of overmatig alcoholgebruik, wat leidt tot buikpijn, misselijkheid en braken.", "uitgesloten", 30),
(232, "Cataract (Kataract)", "2022-09-27", "Een vertroebeling van de ooglens, wat leidt tot verminderde gezichtshelderheid en, indien niet behandeld, blindheid.", "in afwachting", 92),
(233, "Urticaria (Netelroos)", "2022-10-07", "Een huidreactie gekenmerkt door jeukende, rode bulten of plaques, vaak veroorzaakt door allergische reacties of irriterende stoffen.", "chronisch", 145),
(234, "Myocardinfarct", "2023-12-23", "Een hartaanval veroorzaakt door een plotselinge blokkade van een kransslagader, wat leidt tot beschadiging van de hartspier door zuurstoftekort.", "herstellend", 110),
(235, "Gastro-enteritis", "2023-02-28", "Een ontsteking van de maag en darmen, vaak veroorzaakt door infecties, wat leidt tot braken, diarree en buikpijn.", "in afwachting", 70),
(236, "Cirrhose", "2023-05-27", "Een ernstige leveraandoening waarbij gezond leverweefsel wordt vervangen door littekenweefsel, wat de leverfunctie belemmert en kan leiden tot leverfalen.", "uitgesloten", 138),
(237, "Spina Bifida", "2024-01-28", "Een aangeboren defect waarbij de wervelkolom en het ruggenmerg zich niet volledig ontwikkelen, wat kan leiden tot fysieke en neurologische complicaties.", "bevestigd", 141),
(238, "Cystitis", "2023-01-31", "Een ontsteking van de blaas, meestal veroorzaakt door een bacteriële infectie, wat leidt tot pijn bij het plassen en frequente aandrang om te plassen.", "chronisch", 145),
(239, "Hyperthyreoïdie", "2023-12-26", "Een aandoening waarbij de schildklier te veel schildklierhormonen produceert, wat leidt tot symptomen zoals gewichtsverlies, snelle hartslag, zweten en nervositeit.", "herstellend", 145),
(240, "Cerebrale Parese", "2022-11-05", "Een groep neurologische aandoeningen die de spiercoördinatie en beweging beïnvloeden, vaak veroorzaakt door schade aan de hersenen tijdens de zwangerschap of geboorte.", "in afwachting", 87),
(241, "Cervicale Spondylose", "2023-02-01", "Degeneratieve veranderingen in de nekwervels en tussenwervelschijven, wat leidt tot nekpijn en soms zenuwcompressie.", "voorlopig", 70),
(242, "Tardive Dyskinesie", "2022-11-21", "Een bewegingsstoornis gekenmerkt door onvrijwillige, repetitieve bewegingen, vaak veroorzaakt door langdurig gebruik van bepaalde antipsychotische medicijnen.", "in afwachting", 90),
(243, "Hyperparathyreoïdie", "2023-11-25", "Een aandoening waarbij de bijschildklieren te veel parathyroïdhormoon produceren, wat leidt tot verhoogde calciumspiegels in het bloed.", "bevestigd", 131),
(244, "Osteomyelitis", "2022-09-09", "Een botinfectie die kan leiden tot pijn, zwelling, roodheid en soms koorts, vaak veroorzaakt door bacteriën.", "uitgesloten", 118),
(245, "Astma Bronchiale", "2023-06-06", "Een chronische ontstekingsziekte van de luchtwegen die leidt tot piepende ademhaling, kortademigheid, benauwdheid op de borst en hoesten.", "voorlopig", 144),
(246, "Hepatitis B", "2022-05-21", "Een virale infectie die de lever aantast, wat kan leiden tot leverontsteking, cirrose en leverkanker.", "bevestigd", 132),
(247, "Acuut Otitis Media", "2023-02-28", "Een plotselinge ontsteking van het middenoor, vaak veroorzaakt door bacteriële infecties, wat leidt tot oorpijn en soms koorts.", "chronisch", 80),
(248, "Acuut Pericarditis", "2024-05-13", "Ontsteking van het pericardium (de buitenste laag van het hart), wat pijn op de borst en koorts kan veroorzaken.", "uitgesloten", 138),
(249, "Laryngitis", "2023-12-26", "Ontsteking van het strottenhoofd, wat leidt tot heesheid, verlies van stem en keelpijn.", "uitgesloten", 119),
(250, "Bursitis", "2022-11-06", "Ontsteking van een slijmbeurs (bursa), meestal in een gewricht, wat leidt tot pijn en beperkte beweging.", "in afwachting", 92),
(251, "Chondrodystrophie", "2024-01-21", "Een groep erfelijke aandoeningen die de ontwikkeling van kraakbeen en bot beïnvloeden, wat leidt tot groeivertraging en skeletafwijkingen.", "voorlopig", 30),
(252, "Phlebitis", "2023-08-22", "Ontsteking van een ader, vaak gepaard met pijn, roodheid en zwelling, meestal veroorzaakt door een bloedstolsel of infectie.", "in afwachting", 145),
(253, "Retinitis Pigmentosa", "2022-07-10", "Een groep erfelijke oogziekten die leiden tot degeneratie van het netvlies, wat resulteert in geleidelijk verlies van gezichtsvermogen.", "voorlopig", 138),
(254, "Hypoglykemie", "2023-05-28", "Een aandoening waarbij de bloedglucosewaarden te laag zijn, wat leidt tot symptomen zoals zweten, beven, verwarring en in ernstige gevallen bewusteloosheid.", "bevestigd", 132),
(255, "Renale Cell Carcinoom", "2023-09-10", "Een vorm van nierkanker die begint in de cellen van de nier, vaak geassocieerd met symptomen zoals bloed in de urine, flankpijn en gewichtsverlies.", "chronisch", 118),
(256, "Serebrovasculair Accident (Stroke)", "2023-05-06", "Een plotselinge onderbreking van de bloedtoevoer naar de hersenen, wat leidt tot hersenbeschadiging, verlamming en cognitieve stoornissen.", "uitgesloten", 131),
(257, "Dislipidemie", "2022-07-09", "Een aandoening waarbij er afwijkingen zijn in de niveaus van lipiden in het bloed, zoals verhoogd cholesterol en triglyceriden, wat het risico op hartziekten verhoogt.", "bevestigd", 132),
(258, "Cystitis", "2022-11-26", "Een ontsteking van de blaas, meestal veroorzaakt door een bacteriële infectie, wat leidt tot pijn bij het plassen en frequente aandrang om te plassen.", "chronisch", 30),
(259, "Hepatitis A", "2022-05-05", "Een virale infectie die de lever aantast, vaak veroorzaakt door consumptie van besmet voedsel of water, wat leidt tot leverontsteking, misselijkheid en geelzucht.", "bevestigd", 70),
(260, "Hepatitis B", "2023-12-21", "Een virale infectie die de lever aantast, wat kan leiden tot leverontsteking, cirrose en leverkanker.", "herstellend", 53),
(261, "Hypopituitarisme", "2023-11-29", "Een aandoening waarbij de hypofyse niet genoeg van één of meer van haar hormonen produceert, wat leidt tot diverse hormonale tekorten.", "herstellend", 110),
(262, "Hyperparathyreoïdie", "2023-07-18", "Een aandoening waarbij de bijschildklieren te veel parathyroïdhormoon produceren, wat leidt tot verhoogde calciumspiegels in het bloed.", "in afwachting", 110),
(263, "Hypertensieve Hartziekte", "2022-12-08", "Hartziekten veroorzaakt door langdurige hoge bloeddruk, wat kan leiden tot hartfalen, coronaire hartziekte en andere complicaties.", "voorlopig", 118),
(264, "Pneumothorax", "2024-05-19", "Een aandoening waarbij lucht zich ophoopt in de pleuraholte, waardoor het long gedeeltelijk of volledig kan samenvallen, wat leidt tot ademnood en pijn op de borst.", "herstellend", 30),
(265, "Cholecystitis", "2024-04-11", "Ontsteking van de galblaas, vaak veroorzaakt door galstenen, wat leidt tot buikpijn, koorts en misselijkheid.", "bevestigd", 110),
(266, "Kataract", "2023-05-03", "Een vertroebeling van de ooglens, wat leidt tot verminderde gezichtshelderheid en, indien niet behandeld, blindheid.", "voorlopig", 87),
(267, "Meningitis", "2024-02-15", "Ontsteking van de hersenvliezen, vaak veroorzaakt door bacteriële of virale infecties, wat leidt tot hoofdpijn, koorts en nekstijfheid.", "chronisch", 44),
(268, "Chronic Kidney Disease (CKD)", "2022-07-26", "Een progressieve afname van de nierfunctie, wat kan leiden tot ophoping van afvalstoffen in het lichaam en uiteindelijk nierfalen.", "herstellend", 44),
(269, "Pancreatitis", "2023-02-24", "Ontsteking van de alvleesklier, vaak veroorzaakt door galstenen of overmatig alcoholgebruik, wat leidt tot buikpijn, misselijkheid en braken.", "bevestigd", 145),
(270, "Endometriose", "2022-05-10", "Een chronische aandoening waarbij weefsel dat lijkt op het baarmoederslijmvlies buiten de baarmoeder groeit, wat pijn, onregelmatige menstruatie en vruchtbaarheidsproblemen kan veroorzaken.", "uitgesloten", 132),
(271, "Hereditary Hemochromatosis", "2023-07-10", "Een erfelijke aandoening waarbij het lichaam te veel ijzer absorbeert, wat leidt tot ijzeroverbelasting en schade aan organen zoals de lever en het hart.", "voorlopig", 144),
(272, "Fibromyalgie", "2023-08-16", "Een chronische aandoening gekenmerkt door wijdverspreide pijn in spieren en bindweefsel, evenals vermoeidheid, slaapstoornissen en cognitieve problemen.", "in afwachting", 70),
(273, "Cholesterol Gallstones", "2022-05-03", "Stenen die zich vormen in de galblaas uit cholesterol, wat kan leiden tot pijn, infecties en obstructie van de galwegen.", "bevestigd", 144),
(274, "Chondromalacie Patellae", "2023-03-18", "Verslapping of beschadiging van het kraakbeen onder de knieschijf, wat leidt tot kniepijn en knarsende geluiden bij beweging.", "in afwachting", 81),
(275, "Lymfangitis", "2022-12-24", "Ontsteking van de lymfevaten, vaak veroorzaakt door bacteriële infecties, wat leidt tot roodheid, zwelling en pijn langs de lymfebanen.", "uitgesloten", 110),
(276, "Idiopathische Pulmonale Fibrose", "2023-05-04", "Een progressieve longaandoening zonder bekende oorzaak, gekenmerkt door littekenvorming in de longen en ademnood.", "voorlopig", 50),
(277, "Acuut Bronchitis", "2023-07-26", "Een tijdelijke ontsteking van de luchtwegen in de longen, vaak veroorzaakt door virale infecties, wat leidt tot hoesten en ademhalingsproblemen.", "herstellend", 16),
(278, "Nephrotisch Syndroom", "2024-01-27", "Een groep symptomen die optreden als gevolg van schade aan de glomeruli in de nieren, wat leidt tot eiwitverlies in de urine, vochtretentie en hoge cholesterolwaarden.", "voorlopig", 16),
(279, "Renale Cell Carcinoom", "2023-05-18", "Een vorm van nierkanker die begint in de cellen van de nier, vaak geassocieerd met symptomen zoals bloed in de urine, flankpijn en gewichtsverlies.", "uitgesloten", 92),
(280, "Hypoglykemie", "2024-01-15", "Een aandoening waarbij de bloedglucosewaarden te laag zijn, wat leidt tot symptomen zoals zweten, beven, verwarring en in ernstige gevallen bewusteloosheid.", "herstellend", 118),
(281, "Autisme Spectrum Stoornis (ASS)", "2023-07-08", "Een ontwikkelingsstoornis die sociale interactie, communicatie en gedrag beïnvloedt, vaak met repetitieve gedragingen en beperkte interesses.", "bevestigd", 118),
(282, "Spina Ventosa", "2024-04-04", "Een vorm van tuberculose die de botten aantast, vaak leidend tot zwelling en vervorming van de aangetaste botten.", "chronisch", 144),
(283, "Hemophilia", "2022-11-23", "Een erfelijke bloedziekte die de bloedstolling belemmert, wat leidt tot overmatige bloedingen bij verwondingen of zelfs spontane bloedingen.", "herstellend", 118),
(284, "Polycysteus Ovarium Syndroom (PCOS)", "2023-08-28", "Een hormonale aandoening bij vrouwen die wordt gekenmerkt door onregelmatige menstruatie, overmatige haargroei en cysten in de eierstokken.", "voorlopig", 92),
(285, "Hepatische Encefalopathie", "2024-03-08", "Een aandoening waarbij de lever niet goed functioneert, waardoor toxines zich ophopen in de hersenen en leiden tot verwardheid, slaperigheid en coma.", "chronisch", 86),
(286, "Endocriene Hygiëne (Cushing's Disease)", "2024-04-13", "Een specifieke vorm van het Cushing-syndroom veroorzaakt door een tumor in de hypofyse die overmatige productie van ACTH stimuleert.", "chronisch", 86),
(287, "Acuut Myocarditis", "2023-09-04", "Ontsteking van de hartspier, vaak veroorzaakt door virale infecties, wat kan leiden tot hartfalen en hartritmestoornissen.", "uitgesloten", 53),
(288, "Hypopituitarisme", "2022-06-27", "Een aandoening waarbij de hypofyse niet genoeg van één of meer van haar hormonen produceert, wat leidt tot diverse hormonale tekorten.", "in afwachting", 53),
(289, "Spondylolisthesis", "2024-03-05", "Een aandoening waarbij een wervel in de wervelkolom verschuift ten opzichte van de aangrenzende wervels, wat leidt tot rugpijn en zenuwcompressie.", "voorlopig", 80),
(290, "Hernia Diaphragma", "2022-10-16", "Een aandoening waarbij een deel van de maag of andere organen omhoog schuiven naar de borstholte door een opening in het middenrif.", "voorlopig", 44),
(291, "Hyperaldosteronisme", "2023-12-16", "Een aandoening waarbij de bijnieren te veel aldosteron produceren, wat leidt tot hoge bloeddruk en een verstoorde elektrolytenbalans.", "chronisch", 132),
(292, "Vitiligo", "2022-06-28", "Een huidziekte waarbij pigmentcellen worden vernietigd, wat leidt tot witte vlekken op de huid.", "in afwachting", 138),
(293, "Pneumonia", "2022-08-30", "Een longinfectie die de alveoli (longblaasjes) vult met vocht of pus, wat leidt tot hoesten, koorts en ademhalingsmoeilijkheden.", "herstellend", 16),
(294, "Systemische Lupus Erythematosus", "2022-05-04", "Een auto-immuunziekte waarbij het immuunsysteem de eigen weefsels en organen aanvalt, wat kan leiden tot ontstekingen en schade aan de huid, gewrichten, nieren, hersenen en andere organen.", "chronisch", 50),
(295, "Acuut Bronchitis", "2023-12-07", "Een tijdelijke ontsteking van de luchtwegen in de longen, vaak veroorzaakt door virale infecties, wat leidt tot hoesten en ademhalingsproblemen.", "uitgesloten", 87),
(296, "Acuut Renal Failure", "2023-05-26", "Een plotselinge vermindering van de nierfunctie, wat leidt tot ophoping van afvalstoffen en vocht in het lichaam.", "chronisch", 119),
(297, "Hernia Lumbaris", "2024-03-01", "Een aandoening waarbij een tussenwervelschijf in de onderrug uitpuilt, wat kan leiden tot pijn, gevoelloosheid en zwakte in de benen.", "in afwachting", 118),
(298, "Meningitis", "2024-01-15", "Ontsteking van de hersenvliezen, vaak veroorzaakt door bacteriële of virale infecties, wat leidt tot hoofdpijn, koorts en nekstijfheid.", "in afwachting", 118),
(299, "Pericarditis", "2023-11-17", "Ontsteking van het pericardium (de buitenste laag van het hart), wat pijn op de borst en koorts kan veroorzaken.", "chronisch", 141),
(300, "Acuut Otitis Media", "2022-10-14", "Een plotselinge ontsteking van het middenoor, vaak veroorzaakt door bacteriële infecties, wat leidt tot oorpijn en soms koorts.", "voorlopig", 138),
(301, "Hepatitis C", "2023-12-24", "Een virale infectie die de lever aantast en kan leiden tot leverontsteking, cirrose en leverkanker.", "herstellend", 138),
(302, "Chronic Obstructive Pulmonary Disease (COPD)", "2023-07-22", "Een progressieve longaandoening die de luchtstroom belemmert en ademnood veroorzaakt, vaak veroorzaakt door langdurige blootstelling aan irriterende stoffen zoals sigarettenrook.", "voorlopig", 131),
(303, "Amyotrofische Laterale Sclerose (ALS)", "2022-12-15", "Een progressieve neurodegeneratieve ziekte die de zenuwcellen in de hersenen en het ruggenmerg aantast, wat leidt tot spierzwakte en verlamming.", "in afwachting", 87),
(304, "Hyperlipidemie", "2024-03-31", "Een aandoening gekenmerkt door verhoogde niveaus van lipiden (zoals cholesterol en triglyceriden) in het bloed, wat het risico op hartziekten verhoogt.", "uitgesloten", 138),
(305, "Polycysteus Nier Syndroom", "2023-04-22", "Een erfelijke aandoening waarbij zich meerdere cysten vormen in de nieren, wat leidt tot nierfunctiestoornissen en hoge bloeddruk.", "herstellend", 59),
(306, "Schildklierkanker", "2022-10-06", "Een vorm van kanker die ontstaat in de schildklier, vaak gepaard gaand met knobbels in de hals, moeite met slikken en veranderingen in stem.", "uitgesloten", 87),
(307, "Chondrodystrophie", "2024-04-01", "Een groep erfelijke aandoeningen die de ontwikkeling van kraakbeen en bot beïnvloeden, wat leidt tot groeivertraging en skeletafwijkingen.", "voorlopig", 118),
(308, "Lymfomen", "2022-08-21", "Een groep van bloedkankers die ontstaan in het lymfestelsel, wat leidt tot symptomen zoals gezwollen lymfeklieren, koorts en gewichtsverlies.", "voorlopig", 90),
(309, "Cervicale Myelopathie", "2022-04-09", "Compressie van het ruggenmerg in de nek, wat leidt tot symptomen zoals zwakte, gevoelloosheid en verminderde coördinatie in de ledematen.", "bevestigd", 92),
(310, "Acute Pancreatitis", "2023-04-18", "Ontsteking van de alvleesklier, vaak veroorzaakt door galstenen of overmatig alcoholgebruik, wat leidt tot buikpijn, misselijkheid en braken.", "in afwachting", 138),
(311, "Retinitis Pigmentosa", "2023-02-11", "Een groep erfelijke oogziekten die leiden tot degeneratie van het netvlies, wat resulteert in geleidelijk verlies van gezichtsvermogen.", "voorlopig", 144),
(312, "Kanker van de Alvleesklier", "2023-12-28", "Een agressieve vorm van kanker die in de alvleesklier ontstaat, vaak laat gediagnosticeerd en geassocieerd met buikpijn, gewichtsverlies en geelzucht.", "chronisch", 118);
