INSERT INTO Geneeswijze(naam, beschrijving)
VALUES
("Cognitieve Gedragstherapie (CGT)", "Een psychotherapeutische behandeling gericht op het veranderen van negatieve gedachten en gedragingen."),
("Chemotherapie", "Gebruik van medicijnen om kankercellen te doden of hun groei te stoppen."),
("Radiotherapie", "Gebruik van ioniserende straling om kankercellen te vernietigen of te beschadigen."),
("Chirurgie", "Operationele ingrepen om ziek weefsel, zoals tumoren, te verwijderen of te repareren."),
("Fysiotherapie", "Behandeling gericht op het herstellen van mobiliteit en het verminderen van pijn door beweging en oefeningen."),
("Occupational Therapy (Ergotherapie)", "Therapie gericht op het verbeteren van dagelijkse vaardigheden en zelfstandigheid bij patiënten."),
("Dialyse", "Medische procedure die de functies van de nieren overneemt bij nierfalen."),
("Insulinetherapie", "Toediening van insuline om de bloedsuikerspiegel bij diabetespatiënten te reguleren."),
("Antidepressiva", "Medicijnen gebruikt om symptomen van depressie te verlichten door het beïnvloeden van neurotransmitters."),
("Antipsychotica", "Medicijnen gebruikt voor de behandeling van psychotische stoornissen zoals schizofrenie."),
("Hormoontherapie", "Behandeling met hormonen of hormoonblokkers, vaak gebruikt bij kanker of hormonale stoornissen."),
("Immunotherapie", "Behandeling die het immuunsysteem stimuleert om kankercellen te bestrijden."),
("Transfusie", "Toediening van bloed of bloedproducten aan patiënten met bloedarmoede of bloedverlies."),
("Vaccinatie", "Toediening van een vaccin om het immuunsysteem te trainen tegen specifieke infecties."),
("Biologische therapie", "Behandeling die gebruikmaakt van biologische stoffen om ziekten zoals kanker te bestrijden."),
("Psychotherapie", "Behandeling van mentale gezondheidsproblemen door middel van gesprekken en technieken."),
("Logopedie", "Therapie gericht op het verbeteren van spraak- en taalvaardigheden."),
("Chiropractie", "Handmatige behandeling van het bewegingsapparaat, vooral de wervelkolom."),
("Acupunctuur", "Traditionele Chinese therapie waarbij naalden op specifieke punten in het lichaam worden geplaatst."),
("Massage Therapie", "Handmatige manipulatie van spieren en zachte weefsels om pijn te verlichten en ontspanning te bevorderen."),
("Antiretrovirale therapie (ART)", "Medicamenteuze behandeling voor HIV-infectie die de replicatie van het virus onderdrukt."),
("Hydrotherapie", "Gebruik van watertherapieën voor herstel en pijnverlichting."),
("Revalidatie", "Behandeling gericht op het herstellen van fysieke functies na ziekte of letsel."),
("Nutritional Therapy (Voedingsadvies)", "Behandeling gericht op het verbeteren van de gezondheid door middel van dieet en voeding."),
("Cardiovasculaire Rehabilitatie", "Behandeling gericht op het herstellen van hartfunctie na hartziekten of -operaties."),
("Endoscopie", "Minimaal invasieve procedure om het inwendige van het lichaam te bekijken met een endoscoop."),
("Transplantatie", "Vervanging van een beschadigd orgaan door een gezond orgaan van een donor."),
("Systeemtherapie", "Therapie die gericht is op het verbeteren van de interacties binnen een gezin of ander systeem."),
("Genezeologische Therapie", "Therapeutische benadering die zich richt op de onderliggende oorzaken van fysieke en emotionele problemen."),
("Stemtherapie", "Behandeling gericht op het verbeteren van stemgebruik en vocale gezondheid."),
("Slaaptherapie", "Behandeling gericht op het verbeteren van slaapkwaliteit en het aanpakken van slaapstoornissen."),
("Ergotherapie", "Therapie gericht op het verbeteren van dagelijkse vaardigheden en zelfstandigheid bij patiënten."),
("Arthroscopie", "Minimaal invasieve chirurgische procedure om gewrichten te bekijken en te behandelen."),
("Reconstructieve Chirurgie", "Chirurgische ingrepen gericht op het herstellen van lichaamsstructuren na trauma of ziekte."),
("Endocriene Therapie", "Behandeling gericht op het reguleren van hormonen bij hormonale stoornissen."),
("Homeopathie", "Alternatieve geneeswijze gebaseerd op het principe dat het lichaam zichzelf kan genezen met verdunde stoffen."),
("Naturopathie", "Holistische benadering van genezing die natuurlijke methoden en levensstijlveranderingen gebruikt."),
("Aromatherapie", "Gebruik van essentiële oliën om fysieke en emotionele welzijn te bevorderen."),
("Ayurveda", "Traditionele Indiase geneeswijze die balans in lichaam en geest nastreeft met kruiden, dieet en levensstijl."),
("Tai Chi", "Langzame, gecontroleerde bewegingen en ademhalingstechnieken voor fysieke en mentale balans."),
("Yoga", "Fysieke en mentale oefeningen die flexibiliteit, kracht en ontspanning bevorderen."),
("Reiki", "Energetische genezingstechniek waarbij de behandelaar energie overbrengt naar de patiënt."),
("Hypnotherapie", "Gebruik van hypnose om gedragsveranderingen en emotionele genezing te bevorderen."),
("Biofeedback", "Techniek waarbij patiënten leren om fysiologische functies te controleren door middel van feedback van apparaten."),
("Meditatie", "Praktijk van het richten van de geest om ontspanning en mentale helderheid te bevorderen."),
("Acu-needle", "Integratie van acupunctuur en naaldtechnieken voor pijnverlichting en genezing."),
("Kinesiotaping", "Gebruik van elastische tapes om ondersteuning te bieden aan spieren en gewrichten zonder beweging te beperken."),
("Hyperbare zuurstoftherapie", "Behandeling waarbij patiënten ademen in pure zuurstof in een hogedrukkamer om weefselschade te herstellen."),
("Stemcell therapie", "Gebruik van stamcellen om beschadigd weefsel te herstellen of te vervangen."),
("Cryotherapie", "Behandeling waarbij extreem koude temperaturen worden gebruikt voor pijnverlichting en ontstekingsremming."),
("Lasertherapie", "Gebruik van geconcentreerde lichtstralen voor pijnverlichting, wondgenezing en behandeling van huidproblemen."),
("Elektrotherapie", "Gebruik van elektrische stroom voor pijnverlichting en spierstimulatie."),
("Ultrasound Therapie", "Gebruik van geluidsgolven om diepe weefsels te verwarmen en pijn te verminderen."),
("Biochimische therapie", "Behandeling met stoffen die het lichaam helpen zich zelf te genezen door biochemische processen te beïnvloeden."),
("Nerve block", "Injectie van medicijnen om zenuwen te blokkeren en pijn te verlichten."),
("TENS (Transcutane Elektrische Zenuwstimulatie)", "Gebruik van elektrische pulsen om pijn te verminderen door zenuwen te stimuleren."),
("Chelattherapie", "Behandeling waarbij chelatiemiddelen worden gebruikt om zware metalen uit het lichaam te verwijderen."),
("Leefstijlinterventie", "Aanpassingen in dieet, lichaamsbeweging en gedrag om gezondheid te verbeteren en ziektes te voorkomen."),
("Praktijk voor natuurlijke geneeswijzen", "Integratie van natuurlijke remedies en holistische benaderingen voor gezondheid en welzijn."),
("Antibiotica therapie", "Gebruik van antibiotica om bacteriële infecties te behandelen."),
("Antivirale therapie", "Gebruik van antivirale medicijnen om virale infecties te behandelen."),
("Antifungale therapie", "Gebruik van antifungale medicijnen om schimmelinfecties te behandelen."),
("Steroid therapie", "Gebruik van corticosteroïden om ontstekingen en immuunreacties te verminderen."),
("Pain Management", "Behandelingsstrategieën gericht op het verlichten van chronische en acute pijn."),
("Behavioral Therapy", "Psychotherapeutische benadering gericht op het veranderen van schadelijke gedragspatronen."),
("Art Therapie", "Gebruik van creatieve kunstvormen om emotionele expressie en genezing te bevorderen."),
("Music Therapie", "Gebruik van muziek en muzikale activiteiten om emotionele en fysieke gezondheid te verbeteren."),
("Dance Therapie", "Gebruik van dans en beweging om fysieke en emotionele welzijn te bevorderen."),
