INSERT INTO Geneeswijze_heeft_Medicijn(Geneeswijze_naam, Medicijn_medicijn_nummer)
VALUES
("Cognitieve Gedragstherapie (CGT)", 32),
("Cognitieve Gedragstherapie (CGT)", 65),
("Cognitieve Gedragstherapie (CGT)", 1),
("Cognitieve Gedragstherapie (CGT)", 37),
("Cognitieve Gedragstherapie (CGT)", 43),
("Cognitieve Gedragstherapie (CGT)", 45),
("Chemotherapie", 65),
("Chemotherapie", 34),
("Chemotherapie", 72),
("Chemotherapie", 140),
("Radiotherapie", 5),
("Radiotherapie", 70),
("Radiotherapie", 135),
("Radiotherapie", 7),
("Chirurgie", 129),
("Fysiotherapie", 4),
("Fysiotherapie", 40),
("Fysiotherapie", 137),
("Fysiotherapie", 74),
("Occupational Therapy (Ergotherapie)", 33),
("Insulinetherapie", 0),
("Insulinetherapie", 132),
("Insulinetherapie", 139),
("Insulinetherapie", 12),
("Insulinetherapie", 143),
("Insulinetherapie", 16),
("Antidepressiva", 2),
("Antidepressiva", 35),
("Antidepressiva", 4),
("Antidepressiva", 133),
("Antidepressiva", 134),
("Antidepressiva", 12),
("Antipsychotica", 131),
("Antipsychotica", 7),
("Hormoontherapie", 35),
("Hormoontherapie", 131),
("Hormoontherapie", 134),
("Hormoontherapie", 6),
("Hormoontherapie", 72),
("Hormoontherapie", 74),
("Immunotherapie", 32),
("Immunotherapie", 128),
("Immunotherapie", 137),
("Immunotherapie", 138),
("Vaccinatie", 4),
("Vaccinatie", 136),
("Vaccinatie", 139),
("Biologische therapie", 0),
("Psychotherapie", 0),
("Psychotherapie", 33),
("Chiropractie", 33),
("Chiropractie", 1),
("Acupunctuur", 32),
("Acupunctuur", 2),
("Acupunctuur", 35),
("Massage Therapie", 128),
("Massage Therapie", 2),
("Massage Therapie", 70),
("Massage Therapie", 42),
("Massage Therapie", 11),
("Antiretrovirale therapie (ART)", 70),
("Hydrotherapie", 32),
("Hydrotherapie", 34),
("Hydrotherapie", 35),
("Revalidatie", 33),
("Revalidatie", 6),
("Revalidatie", 74),
("Revalidatie", 138),
("Nutritional Therapy (Voedingsadvies)", 33),
("Cardiovasculaire Rehabilitatie", 0),
("Cardiovasculaire Rehabilitatie", 129),
("Endoscopie", 33),
("Endoscopie", 130),
("Endoscopie", 7),
("Endoscopie", 46),
("Transplantatie", 32),
("Transplantatie", 37),
("Transplantatie", 134),
("Transplantatie", 40),
("Systeemtherapie", 32),
("Systeemtherapie", 35),
("Systeemtherapie", 68),
("Genezeologische Therapie", 128),
("Genezeologische Therapie", 129),
("Genezeologische Therapie", 36),
("Genezeologische Therapie", 4),
("Genezeologische Therapie", 7),
("Genezeologische Therapie", 40),
("Stemtherapie", 0),
("Stemtherapie", 129),
("Stemtherapie", 2),
("Stemtherapie", 32),
("Stemtherapie", 139),
("Slaaptherapie", 32),
("Slaaptherapie", 129),
("Slaaptherapie", 33),
("Slaaptherapie", 131),
("Slaaptherapie", 132),
("Ergotherapie", 37),
("Ergotherapie", 76),
("Ergotherapie", 45),
("Ergotherapie", 141),
("Arthroscopie", 35),
("Arthroscopie", 6),
("Reconstructieve Chirurgie", 128),
("Reconstructieve Chirurgie", 1),
("Reconstructieve Chirurgie", 130),
("Reconstructieve Chirurgie", 36),
("Endocriene Therapie", 129),
("Endocriene Therapie", 35),
("Homeopathie", 128),
("Homeopathie", 129),
("Homeopathie", 65),
("Homeopathie", 144),
("Homeopathie", 17),
("Naturopathie", 130),
("Naturopathie", 68),
("Ayurveda", 2),
("Ayurveda", 35),
("Yoga", 66),
("Yoga", 6),
("Yoga", 40),
("Yoga", 72),
("Reiki", 32),
("Reiki", 33),
("Reiki", 10),
("Reiki", 139),
("Reiki", 78),
("Reiki", 50),
("Hypnotherapie", 0),
("Hypnotherapie", 32),
("Biofeedback", 1),
("Biofeedback", 9),
("Biofeedback", 74),
("Kinesiotaping", 0),
("Kinesiotaping", 32),
("Kinesiotaping", 3),
("Hyperbare zuurstoftherapie", 0),
("Stemcell therapie", 136),
("Stemcell therapie", 137),
("Stemcell therapie", 8),
("Stemcell therapie", 139),
("Stemcell therapie", 43),
("Stemcell therapie", 51),
("Lasertherapie", 1),
("Elektrotherapie", 0),
("Elektrotherapie", 34),
("Elektrotherapie", 132),
("Elektrotherapie", 70),
("Elektrotherapie", 10),
("Ultrasound Therapie", 34),
("Ultrasound Therapie", 3),
("Ultrasound Therapie", 68),
("Ultrasound Therapie", 135),
("Ultrasound Therapie", 10),
("Ultrasound Therapie", 78),
("Biochimische therapie", 128),
("Nerve block", 1),
("Nerve block", 2),
("Nerve block", 72),
("Nerve block", 43),
("Nerve block", 77),
("TENS (Transcutane Elektrische Zenuwstimulatie)", 35),
("TENS (Transcutane Elektrische Zenuwstimulatie)", 37),
("TENS (Transcutane Elektrische Zenuwstimulatie)", 10),
("TENS (Transcutane Elektrische Zenuwstimulatie)", 140),
("TENS (Transcutane Elektrische Zenuwstimulatie)", 144),
("Chelattherapie", 132),
("Chelattherapie", 37),
("Chelattherapie", 68),
("Chelattherapie", 135),
("Leefstijlinterventie", 34),
("Leefstijlinterventie", 6),
("Leefstijlinterventie", 43),
("Leefstijlinterventie", 75),
("Leefstijlinterventie", 14),
("Praktijk voor natuurlijke geneeswijzen", 131),
("Antibiotica therapie", 128),
("Antibiotica therapie", 129),
("Antibiotica therapie", 66),
("Antibiotica therapie", 10),
("Antivirale therapie", 33),
("Antivirale therapie", 77),
("Antivirale therapie", 49),
("Antivirale therapie", 17),
("Antivirale therapie", 50),
("Antifungale therapie", 65),
("Antifungale therapie", 35),
("Pain Management", 132),
("Pain Management", 36),
("Pain Management", 134),
("Pain Management", 76),
("Behavioral Therapy", 134),
("Art Therapie", 0),
("Art Therapie", 128),
("Art Therapie", 1),
("Art Therapie", 7),
("Art Therapie", 72),
("Music Therapie", 128),
("Music Therapie", 0),
("Music Therapie", 131),
("Dance Therapie", 0);
("Dance Therapie", 5);
("Dance Therapie", 133);
