INSERT INTO Geneeswijze_heeft_Medicijn(Geneeswijze_naam, Medicijn_medicijn_nummer)
VALUES
("Cognitieve Gedragstherapie (CGT)", 0),
("Chemotherapie", 32),
("Radiotherapie", 33),
("Chirurgie", 65),
("Chirurgie", 33),
("Chirurgie", 6),
("Chirurgie", 136),
("Fysiotherapie", 134),
("Fysiotherapie", 135),
("Occupational Therapy (Ergotherapie)", 33),
("Occupational Therapy (Ergotherapie)", 130),
("Occupational Therapy (Ergotherapie)", 3),
("Occupational Therapy (Ergotherapie)", 138),
("Dialyse", 133),
("Dialyse", 9),
("Dialyse", 75),
("Dialyse", 141),
("Dialyse", 15),
("Dialyse", 144),
("Insulinetherapie", 1),
("Antidepressiva", 128),
("Antidepressiva", 129),
("Antidepressiva", 33),
("Antipsychotica", 0),
("Antipsychotica", 1),
("Antipsychotica", 133),
("Antipsychotica", 7),
("Antipsychotica", 40),
("Antipsychotica", 44),
("Hormoontherapie", 0),
("Hormoontherapie", 133),
("Hormoontherapie", 135),
("Hormoontherapie", 14),
("Hormoontherapie", 15),
("Hormoontherapie", 143),
("Immunotherapie", 33),
("Immunotherapie", 4),
("Transfusie", 32),
("Transfusie", 5),
("Transfusie", 139),
("Transfusie", 76),
("Transfusie", 46),
("Vaccinatie", 128),
("Vaccinatie", 134),
("Vaccinatie", 40),
("Vaccinatie", 137),
("Biologische therapie", 134),
("Biologische therapie", 40),
("Biologische therapie", 43),
("Biologische therapie", 80),
("Biologische therapie", 18),
("Psychotherapie", 66),
("Psychotherapie", 3),
("Psychotherapie", 130),
("Logopedie", 32),
("Logopedie", 35),
("Logopedie", 132),
("Logopedie", 8),
("Logopedie", 136),
("Acupunctuur", 0),
("Acupunctuur", 65),
("Acupunctuur", 135),
("Massage Therapie", 0),
("Antiretrovirale therapie (ART)", 0),
("Hydrotherapie", 128),
("Hydrotherapie", 5),
("Hydrotherapie", 136),
("Hydrotherapie", 9),
("Revalidatie", 130),
("Revalidatie", 66),
("Revalidatie", 37),
("Revalidatie", 135),
("Revalidatie", 40),
("Revalidatie", 72),
("Nutritional Therapy (Voedingsadvies)", 7),
("Nutritional Therapy (Voedingsadvies)", 72),
("Nutritional Therapy (Voedingsadvies)", 144),
("Cardiovasculaire Rehabilitatie", 32),
("Endoscopie", 32),
("Endoscopie", 130),
("Endoscopie", 36),
("Transplantatie", 129),
("Transplantatie", 34),
("Transplantatie", 131),
("Transplantatie", 7),
("Transplantatie", 136),
("Systeemtherapie", 37),
("Genezeologische Therapie", 134),
("Genezeologische Therapie", 6),
("Stemtherapie", 32),
("Stemtherapie", 4),
("Stemtherapie", 5),
("Stemtherapie", 135),
("Stemtherapie", 40),
("Slaaptherapie", 0),
("Slaaptherapie", 65),
("Ergotherapie", 128),
("Arthroscopie", 65),
("Arthroscopie", 2),
("Reconstructieve Chirurgie", 3),
("Reconstructieve Chirurgie", 36),
("Reconstructieve Chirurgie", 68),
("Homeopathie", 33),
("Homeopathie", 4),
("Homeopathie", 133),
("Homeopathie", 37),
("Homeopathie", 7),
("Naturopathie", 131),
("Naturopathie", 36),
("Aromatherapie", 34),
("Aromatherapie", 35),
("Aromatherapie", 133),
("Ayurveda", 32),
("Tai Chi", 3),
("Tai Chi", 4),
("Tai Chi", 40),
("Yoga", 32),
("Reiki", 32),
("Reiki", 34),
("Reiki", 131),
("Reiki", 70),
("Reiki", 13),
("Reiki", 46),
("Hypnotherapie", 3),
("Hypnotherapie", 9),
("Hypnotherapie", 74),
("Meditatie", 0),
("Meditatie", 36),
("Meditatie", 133),
("Meditatie", 70),
("Acu-needle", 131),
("Acu-needle", 135),
("Kinesiotaping", 3),
("Kinesiotaping", 4),
("Kinesiotaping", 40),
("Kinesiotaping", 76),
("Kinesiotaping", 77),
("Kinesiotaping", 44),
("Hyperbare zuurstoftherapie", 129),
("Hyperbare zuurstoftherapie", 130),
("Stemcell therapie", 131),
("Cryotherapie", 129),
("Cryotherapie", 68),
("Cryotherapie", 135),
("Lasertherapie", 34),
("Elektrotherapie", 133),
("Elektrotherapie", 7),
("Elektrotherapie", 40),
("Elektrotherapie", 137),
("Elektrotherapie", 48),
("Ultrasound Therapie", 33),
("Biochimische therapie", 2),
("Biochimische therapie", 130),
("Biochimische therapie", 37),
("Nerve block", 2),
("Nerve block", 131),
("TENS (Transcutane Elektrische Zenuwstimulatie)", 32),
("TENS (Transcutane Elektrische Zenuwstimulatie)", 0),
("TENS (Transcutane Elektrische Zenuwstimulatie)", 35),
("TENS (Transcutane Elektrische Zenuwstimulatie)", 134),
("Chelattherapie", 66),
("Chelattherapie", 45),
("Chelattherapie", 141),
("Chelattherapie", 46),
("Praktijk voor natuurlijke geneeswijzen", 65),
("Praktijk voor natuurlijke geneeswijzen", 1),
("Praktijk voor natuurlijke geneeswijzen", 70),
("Praktijk voor natuurlijke geneeswijzen", 135),
("Praktijk voor natuurlijke geneeswijzen", 80),
("Praktijk voor natuurlijke geneeswijzen", 50),
("Antibiotica therapie", 130),
("Antibiotica therapie", 2),
("Antibiotica therapie", 66),
("Antibiotica therapie", 134),
("Antibiotica therapie", 135),
("Antibiotica therapie", 13),
("Antivirale therapie", 133),
("Antivirale therapie", 70),
("Antifungale therapie", 1),
("Antifungale therapie", 33),
("Steroid therapie", 37),
("Steroid therapie", 40),
("Steroid therapie", 139),
("Steroid therapie", 13),
("Steroid therapie", 15),
("Pain Management", 65),
("Pain Management", 75),
("Pain Management", 140),
("Pain Management", 46),
("Pain Management", 14),
("Pain Management", 144),
("Behavioral Therapy", 33),
("Behavioral Therapy", 66),
("Art Therapie", 5),
("Art Therapie", 37),
("Art Therapie", 70),
("Art Therapie", 72),
("Music Therapie", 130),
("Music Therapie", 133),
("Music Therapie", 7),
("Music Therapie", 40),
("Dance Therapie", 33),
("Dance Therapie", 35),
("Dance Therapie", 132),
("Dance Therapie", 133),
("Dance Therapie", 8),
("Dance Therapie", 45),
