INSERT INTO Medischedossier(md_nummer, bloedgroep, rookgedrag, alcoholgedrag, lichamelijke_beperkingen, mentale_gezondheid, verzekering_informatie, Bewoner_code)
VALUES
(0, "A-", "Roken ter imitatie van anderen", "Sociale drinker", "e", "Antisociale persoonlijkheidsstoornis", "Polderzorg", 15),
(1, "O-", "Vaping (elektronisch roken)", "Feestdrinker", " ", "Dissociatieve amnesie", "SNS Zorgverzekering", 17),
(2, "B-", "Roken op het werk", "Creatief drinker", "n", "Histrionische persoonlijkheidsstoornis", "Paramed", 18),
(3, "B-", "Dagelijks roken", "Aangepaste drinker", "n", "Separation anxiety disorder", "ASR", 19),
(4, "B+", "Rookt niet", "Gezondheidsbewuste drinker", "n", "Slaapapneu", "Achmea", 20),
(5, "AB+", "Rookt niet", "Af en toe drinker", "i", "Narcistische persoonlijkheidsstoornis", "Zilveren Kruis", 21),
(6, "B+", "Rookt niet", "Concertrinker", "n", "Posttraumatische stressstoornis (PTSS)", "Achmea", 22),
(7, "B-", "Rookt niet", "Functioneel drinker", "i", "Vrouwelijke seksuele dysfunctie", "ANWB Zorgverzekering", 23),
(8, "O-", "Rookt niet", "Single occasion drinker", " ", "Posttraumatische stressstoornis (PTSS)", "SNS Zorgverzekering", 24),
(9, "B+", "Rookt niet", "Single occasion drinker", "e", "Depersonalisatie/derealisatie stoornis", "Polderzorg", 25),
(10, "O+", "Rookt niet", "Sociale drinker", "e", "Geen bijzonderheden", "Zilveren Kruis", 26),
(11, "AB+", "Rookt niet", "Routine drinker", "k", "Antisociale persoonlijkheidsstoornis", "DSW", 27),
(12, "B-", "Rookt niet", "Vervangend drinker", "j", "Rumination disorder", "OHRA", 28),
(13, "O-", "Rookt niet", "Sociale drinker", "j", "Verslaving", "Delta Lloyd", 29),
(14, "AB+", "Rookt niet", "Single occasion drinker", "l", "Boulimia nervosa", "ASR", 31),
(15, "O+", "Rookt niet", "Experimenterend drinker", "c", "Posttraumatische stressstoornis (PTSS)", "DSW Zorgverzekering", 32),
(16, "A-", "Rookt niet", "Aangepaste drinker", "i", "Dissociatieve identiteitsstoornis", "OHRA", 33),
(17, "A-", "Rookt niet", "Feestdrinker", "g", "Paranoïde persoonlijkheidsstoornis", "Achmea", 34),
(18, "O-", "Rookt niet", "Single occasion drinker", " ", "Motorische coördinatiestoornis", "Achmea", 35),
(19, "AB-", "Rookt niet", "Alcoholvrije drinker", "i", "Erectiestoornissen", "FBTO", 36),
(20, "A-", "Rookt niet", "Vervangend drinker", "p", "Geen bijzonderheden", "Delta Lloyd", 37),
(21, "A-", "Rookt niet", "Af en toe drinker", "n", "Rumination disorder", "Zorg en Zekerheid", 38),
(22, "B+", "Rookt niet", "Creatief drinker", "G", "Ziekteangststoornis", "Paramed", 39),
(23, "B-", "Rookt niet", "Medicinale drinker", "G", "Sociale angststoornis", "ASR", 40),
(24, "B+", "Rookt niet", "Sociale drinker", " ", "Afhankelijke persoonlijkheidsstoornis", "InShared", 41),
(25, "B-", "Rookt niet", "Functioneel drinker", "h", "Tikstoornissen (zoals de ziekte van Tourette)", "ASR", 42),
(26, "O-", "Rookt niet", "Vervangend drinker", "l", "Insomnie", "ASR", 43),
(27, "A+", "Rookt niet", "Overmatig drinker", "k", "Premature ejaculatie", "Zorg en Zekerheid", 45),
(28, "A+", "Rookt niet", "Routine drinker", "l", "Acute stressstoornis", "OHRA", 46),
(29, "AB-", "Rookt niet", "Aangepaste drinker", " ", "Leerstoornissen", "InShared", 47),
(30, "O-", "Rookt niet", "Routine drinker", "i", "Afhankelijke persoonlijkheidsstoornis", "De Friesland", 48),
(31, "B-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "VGZ", 49),
(32, "AB+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Univé", 51),
(33, "A-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Paramed", 52),
(34, "O-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "DSW", 54),
(35, "O+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Menzis", 55),
(36, "B+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Univé", 56),
(37, "A-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "DSW Zorgverzekering", 57),
(38, "O-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Paramed", 58),
(39, "AB-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "VGZ", 60),
(40, "AB-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "VGZ", 61),
(41, "A-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Zorg en Zekerheid", 62),
(42, "AB+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Menzis", 63),
(43, "A+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Aegon", 64),
(44, "B-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "VGZ", 65),
(45, "B-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "SNS Zorgverzekering", 66),
(46, "A-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Polderzorg", 67),
(47, "O+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "DSW", 68),
(48, "AB+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "InShared", 69),
(49, "O+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Zorg en Zekerheid", 71),
(50, "B+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Achmea", 72),
(51, "B-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "CZ", 73),
(52, "A+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Zilveren Kruis", 74);
