INSERT INTO Medischedossier(md_nummer, bloedgroep, rookgedrag, alcoholgedrag, lichamelijke_beperkingen, mentale_gezondheid, verzekering_informatie, Bewoner_code)
VALUES
(0, "A+", "Dagelijks roken", "Culturele drinker", "i", "Slaapapneu", "Aegon", 16),
(1, "O+", "Vaping (elektronisch roken)", "Overmatig drinker", "e", "Attention Deficit Hyperactivity Disorder (ADHD)", "VGZ", 17),
(2, "A+", "Roken in privé", "Alcoholvrije drinker", "g", "Boulimia nervosa", "SNS Zorgverzekering", 18),
(3, "A-", "Roken tijdens pauzes", "Routine drinker", "e", "Dissociatieve amnesie", "Delta Lloyd", 19),
(4, "AB-", "Rookt niet", "Routine drinker", "e", "Narcistische persoonlijkheidsstoornis", "Delta Lloyd", 20),
(5, "O+", "Rookt niet", "Culturele drinker", "e", "Geen bijzonderheden", "DSW Zorgverzekering", 21),
(6, "O+", "Rookt niet", "Routine drinker", "h", "Depersonalisatie/derealisatie stoornis", "De Friesland", 22),
(7, "A-", "Rookt niet", "Sociale drinker", "a", "Schizofrenie", "CZ", 23),
(8, "A-", "Rookt niet", "Dagelijkse drinker", " ", "Antisociale persoonlijkheidsstoornis", "InShared", 24),
(9, "AB-", "Rookt niet", "Overmatig drinker", "k", "Dissociatieve amnesie", "Achmea", 26),
(10, "A+", "Rookt niet", "Culturele drinker", "m", "Boulimia nervosa", "CZ", 27),
(11, "B+", "Rookt niet", "Medicinale drinker", "h", "Rumination disorder", "DSW Zorgverzekering", 28),
(12, "B-", "Rookt niet", "Zelfmedicatie drinker", " ", "Posttraumatische stressstoornis (PTSS)", "Delta Lloyd", 29),
(13, "B-", "Rookt niet", "Vervangend drinker", "n", "Premature ejaculatie", "ASR", 30),
(14, "B-", "Rookt niet", "Gezondheidsbewuste drinker", "h", "Autismespectrumstoornis", "Delta Lloyd", 31),
(15, "B+", "Rookt niet", "Gezondheidsbewuste drinker", "n", "Schizoaffectieve stoornis", "DSW", 33),
(16, "A+", "Rookt niet", "Af en toe drinker", "l", "Boulimia nervosa", "ASR", 34),
(17, "O+", "Rookt niet", "Ritueel drinker", "r", "Zelfbeschadigend gedrag", "Paramed", 35),
(18, "O+", "Rookt niet", "Concertrinker", "l", "Anorexia nervosa", "Univé", 36),
(19, "B-", "Rookt niet", "Sociale drinker", "l", "Kortdurende psychotische stoornis", "SNS Zorgverzekering", 37),
(20, "AB-", "Rookt niet", "Aangepaste drinker", "l", "Leerstoornissen", "Univé", 38),
(21, "O+", "Rookt niet", "Sociale drinker", "e", "Zelfbeschadigend gedrag", "CZ", 39),
(22, "AB+", "Rookt niet", "Stressdrinker", "e", "Paniekstoornis", "CZ", 41),
(23, "O+", "Rookt niet", "Creatief drinker", "e", "Schizoaffectieve stoornis", "ANWB Zorgverzekering", 42),
(24, "O-", "Rookt niet", "Single occasion drinker", "i", "Attention Deficit Hyperactivity Disorder (ADHD)", "FBTO", 43),
(25, "O+", "Rookt niet", "Routine drinker", "n", "Obsessieve-compulsieve persoonlijkheidsstoornis", "Univé", 44),
(26, "O+", "Rookt niet", "Culturele drinker", "k", "Aanpassingsstoornis", "Delta Lloyd", 45),
(27, "A+", "Rookt niet", "Culturele drinker", "e", "Narcistische persoonlijkheidsstoornis", "CZ", 46),
(28, "AB-", "Rookt niet", "Stressdrinker", "e", "Separation anxiety disorder", "ANWB Zorgverzekering", 47),
(29, "O+", "Rookt niet", "Zelfmedicatie drinker", "e", "Premature ejaculatie", "OHRA", 49),
(30, "A+", "Rookt niet", "Experimenterend drinker", "b", "Acute stressstoornis", "DSW Zorgverzekering", 50),
(31, "B+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "ASR", 51),
(32, "B+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "DSW Zorgverzekering", 52),
(33, "AB+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Achmea", 53),
(34, "O-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Achmea", 54),
(35, "A-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "ASR", 55),
(36, "B-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Univé", 56),
(37, "AB+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Zilveren Kruis", 57),
(38, "B+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "OHRA", 59),
(39, "O+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "FBTO", 60),
(40, "A-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Aegon", 61),
(41, "A-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "FBTO", 62),
(42, "B-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Paramed", 64),
(43, "AB+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Paramed", 65),
(44, "AB-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Achmea", 66),
(45, "A+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "De Friesland", 67),
(46, "O-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Univé", 69),
(47, "B+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "ANWB Zorgverzekering", 70),
(48, "A+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "SNS Zorgverzekering", 71),
(49, "O-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Delta Lloyd", 72),
(50, "B+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "OHRA", 73),
(51, "B-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "ANWB Zorgverzekering", 74);
