INSERT INTO Medischedossier(md_nummer, bloedgroep, rookgedrag, alcoholgedrag, lichamelijke_beperkingen, mentale_gezondheid, verzekering_informatie, Bewoner_code)
VALUES
(0, "AB-", "Roken als beloning", "Dagelijkse drinker", "n", "Boulimia nervosa", "Zorg en Zekerheid", 79),
(1, "AB-", "Verslaafde rokers", "Creatief drinker", "e", "Motorische coördinatiestoornis", "OHRA", 80),
(2, "A-", "Roken in de auto", "Functioneel drinker", " ", "Vermijdende persoonlijkheidsstoornis", "DSW Zorgverzekering", 82),
(3, "B+", "Stress roken", "Experimenterend drinker", "n", "Narcistische persoonlijkheidsstoornis", "Zorg en Zekerheid", 84),
(4, "O-", "Roken tijdens pauzes", "Single occasion drinker", "e", "Acute stressstoornis", "VGZ", 86),
(5, "O-", "Experimenterend roken", "Functioneel drinker", "G", "Specifieke fobieën", "Polderzorg", 88),
(6, "B-", "Experimenterend roken", "Overmatig drinker", "n", "Obsessieve-compulsieve stoornis (OCD)", "De Friesland", 92),
(7, "A-", "Roken tijdens maaltijden", "Routine drinker", "e", "Attention Deficit Hyperactivity Disorder (ADHD)", "InShared", 95),
(8, "A+", "Gelegenheidsrokers", "Concertrinker", "b", "Sociale angststoornis", "Aegon", 98),
(9, "A-", "Roken in de auto", "Dagelijkse drinker", "i", "Vrouwelijke seksuele dysfunctie", "DSW Zorgverzekering", 99),
(10, "B+", "Sociaal roken", "Functioneel drinker", "e", "Ziekteangststoornis", "Achmea", 102),
(11, "B-", "Roken op het werk", "Sociale drinker", "h", "Sociale angststoornis", "Achmea", 104),
(12, "AB-", "Roken in privé", "Verslaafde drinker", "i", "Boulimia nervosa", "SNS Zorgverzekering", 108),
(13, "AB-", "Rookt niet", "Experimenterend drinker", "k", "Slaapapneu", "Paramed", 109),
(14, "B-", "Rookt niet", "Single occasion drinker", "r", "Dissociatieve amnesie", "Univé", 110),
(15, "B-", "Rookt niet", "Concertrinker", "e", "Histrionische persoonlijkheidsstoornis", "DSW Zorgverzekering", 111),
(16, "A-", "Rookt niet", "Zelfmedicatie drinker", "G", "Attention Deficit Hyperactivity Disorder (ADHD)", "Aegon", 113),
(17, "A+", "Rookt niet", "Functioneel drinker", " ", "Depersonalisatie/derealisatie stoornis", "InShared", 114),
(18, "O+", "Rookt niet", "Stressdrinker", "j", "Slaapapneu", "Delta Lloyd", 115),
(19, "B+", "Rookt niet", "Vervangend drinker", "n", "Pica", "ANWB Zorgverzekering", 116),
(20, "O-", "Rookt niet", "Routine drinker", "e", "Geen bijzonderheden", "Polderzorg", 117),
(21, "A-", "Rookt niet", "Verslaafde drinker", "l", "Acute stressstoornis", "ASR", 119),
(22, "O-", "Rookt niet", "Gezondheidsbewuste drinker", "e", "Vrouwelijke seksuele dysfunctie", "FBTO", 123),
(23, "A+", "Rookt niet", "Functioneel drinker", "c", "Bipolaire stoornis", "Polderzorg", 125),
(24, "O+", "Rookt niet", "Sociale drinker", "g", "Zelfbeschadigend gedrag", "SNS Zorgverzekering", 126),
(25, "A-", "Rookt niet", "Dagelijkse drinker", "g", "Rumination disorder", "Polderzorg", 127),
(26, "A+", "Rookt niet", "Single occasion drinker", "j", "Attention Deficit Hyperactivity Disorder (ADHD)", "VGZ", 128),
(27, "B+", "Rookt niet", "Overmatig drinker", "c", "Specifieke fobieën", "ANWB Zorgverzekering", 130),
(28, "AB+", "Rookt niet", "Alcoholvrije drinker", "h", "Vermijdende persoonlijkheidsstoornis", "Aegon", 135),
(29, "AB-", "Rookt niet", "Gezondheidsbewuste drinker", "e", "Verslaving", "FBTO", 136),
(30, "B-", "Rookt niet", "Ritueel drinker", "n", "Kortdurende psychotische stoornis", "Zilveren Kruis", 137),
(31, "B-", "Rookt niet", "Overmatig drinker", "h", "Cyclothymie", "Univé", 141),
(32, "B-", "Rookt niet", "Single occasion drinker", "l", "Attention Deficit Hyperactivity Disorder (ADHD)", "DSW Zorgverzekering", 142),
(33, "AB-", "Rookt niet", "Gezondheidsbewuste drinker", "m", "Cyclothymie", "Paramed", 145),
(34, "O-", "Rookt niet", "Sociale drinker", " ", "Obsessieve-compulsieve stoornis (OCD)", "Paramed", 146),
(35, "O+", "Rookt niet", "Creatief drinker", "m", "Ziekteangststoornis", "Menzis", 151),
(36, "B-", "Rookt niet", "Vervangend drinker", "n", "Schizoaffectieve stoornis", "Univé", 152),
(37, "A-", "Rookt niet", "Culturele drinker", "l", "Borderline persoonlijkheidsstoornis", "Univé", 153),
(38, "A+", "Rookt niet", "Culturele drinker", "i", "Rumination disorder", "Aegon", 154),
(39, "O+", "Rookt niet", "Feestdrinker", "h", "Paranoïde persoonlijkheidsstoornis", "Polderzorg", 155),
(40, "O+", "Rookt niet", "Stressdrinker", "G", "Autismespectrumstoornis", "OHRA", 156),
(41, "AB-", "Rookt niet", "Af en toe drinker", " ", "Specifieke fobieën", "ANWB Zorgverzekering", 157),
(42, "B-", "Rookt niet", "Aangepaste drinker", "r", "Obsessieve-compulsieve persoonlijkheidsstoornis", "Polderzorg", 162),
(43, "A+", "Rookt niet", "Zelfmedicatie drinker", "e", "Bipolaire stoornis", "Menzis", 163),
(44, "A+", "Rookt niet", "Gezondheidsbewuste drinker", "e", "Aanpassingsstoornis", "Aegon", 164),
(45, "AB+", "Rookt niet", "Experimenterend drinker", "e", "Dysthymie", "SNS Zorgverzekering", 170),
(46, "B-", "Rookt niet", "Functioneel drinker", "i", "Autismespectrumstoornis", "Menzis", 171),
(47, "AB-", "Rookt niet", "Routine drinker", " ", "Geen bijzonderheden", "VGZ", 172),
(48, "A-", "Rookt niet", "Single occasion drinker", "l", "Kortdurende psychotische stoornis", "VGZ", 173),
(49, "O-", "Rookt niet", "Ritueel drinker", "e", "Dysthymie", "Menzis", 174),
(50, "A-", "Rookt niet", "Aangepaste drinker", "e", "Dysthymie", "De Friesland", 175),
(51, "AB-", "Rookt niet", "Sociale drinker", "l", "Autismespectrumstoornis", "Aegon", 176),
(52, "B-", "Rookt niet", "Verslaafde drinker", " ", "Depressie", "Menzis", 177),
(53, "AB-", "Rookt niet", "Sociale drinker", " ", "Schizofrenie", "Menzis", 178),
(54, "AB-", "Rookt niet", "Zelfmedicatie drinker", "e", "Obsessieve-compulsieve persoonlijkheidsstoornis", "Zilveren Kruis", 179),
(55, "B-", "Rookt niet", "Vervangend drinker", "r", "Narcolepsie", "De Friesland", 180),
(56, "O+", "Rookt niet", "Routine drinker", "e", "Kortdurende psychotische stoornis", "Paramed", 181),
(57, "O+", "Rookt niet", "Concertrinker", "g", "Posttraumatische stressstoornis (PTSS)", "DSW Zorgverzekering", 182),
(58, "A+", "Rookt niet", "Vervangend drinker", " ", "Obsessieve-compulsieve persoonlijkheidsstoornis", "CZ", 183),
(59, "A+", "Rookt niet", "Overmatig drinker", "n", "Boulimia nervosa", "Aegon", 184),
(60, "B+", "Rookt niet", "Dagelijkse drinker", "e", "Vrouwelijke seksuele dysfunctie", "FBTO", 185),
(61, "AB-", "Rookt niet", "Alcoholvrije drinker", "i", "Slaapapneu", "DSW", 186),
(62, "AB+", "Rookt niet", "Culturele drinker", "h", "Boulimia nervosa", "Aegon", 187),
(63, "A-", "Rookt niet", "Gezondheidsbewuste drinker", "b", "Rumination disorder", "VGZ", 188),
(64, "A-", "Rookt niet", "Vervangend drinker", "e", "Separation anxiety disorder", "VGZ", 189),
(65, "O-", "Rookt niet", "Sociale drinker", "c", "Verslaving", "DSW", 190),
(66, "O-", "Rookt niet", "Routine drinker", " ", "Dissociatieve amnesie", "Zorg en Zekerheid", 191),
(67, "A-", "Rookt niet", "Ritueel drinker", "m", "Rustelozebenensyndroom", "InShared", 192),
(68, "A+", "Rookt niet", "Aangepaste drinker", "k", "Bipolaire stoornis", "InShared", 193),
(69, "A-", "Rookt niet", "Af en toe drinker", "l", "Dissociatieve amnesie", "Aegon", 194),
(70, "A-", "Rookt niet", "Creatief drinker", "c", "Vermijdende persoonlijkheidsstoornis", "VGZ", 195),
(71, "B-", "Rookt niet", "Ritueel drinker", "e", "Antisociale persoonlijkheidsstoornis", "Delta Lloyd", 196),
(72, "A+", "Rookt niet", "Medicinale drinker", " ", "Anorexia nervosa", "DSW Zorgverzekering", 197),
(73, "B-", "Rookt niet", "Gezondheidsbewuste drinker", "k", "Kortdurende psychotische stoornis", "ASR", 198),
(74, "B-", "Rookt niet", "Gezondheidsbewuste drinker", "l", "Erectiestoornissen", "Menzis", 199),
(75, "B+", "Rookt niet", "Ritueel drinker", "e", "Narcolepsie", "Zorg en Zekerheid", 200),
(76, "B+", "Rookt niet", "Overmatig drinker", "k", "Kortdurende psychotische stoornis", "OHRA", 201),
(77, "A+", "Rookt niet", "Creatief drinker", "n", "Leerstoornissen", "Paramed", 202),
(78, "AB-", "Rookt niet", "Medicinale drinker", "r", "Paranoïde persoonlijkheidsstoornis", "Zorg en Zekerheid", 203),
(79, "AB-", "Rookt niet", "Ritueel drinker", "i", "Obsessieve-compulsieve stoornis (OCD)", "VGZ", 204),
(80, "A+", "Rookt niet", "Overmatig drinker", "k", "Vermijdende persoonlijkheidsstoornis", "Univé", 205),
(81, "O-", "Rookt niet", "Vervangend drinker", "g", "Premature ejaculatie", "Aegon", 206),
(82, "AB+", "Rookt niet", "Culturele drinker", "p", "Separation anxiety disorder", "Delta Lloyd", 207),
(83, "A+", "Rookt niet", "Culturele drinker", "l", "Cyclothymie", "CZ", 208),
(84, "A+", "Rookt niet", "Stressdrinker", "l", "Narcistische persoonlijkheidsstoornis", "ANWB Zorgverzekering", 209),
(85, "AB+", "Rookt niet", "Alcoholvrije drinker", "n", "Verslaving", "De Friesland", 210),
(86, "B+", "Rookt niet", "Single occasion drinker", "e", "Borderline persoonlijkheidsstoornis", "OHRA", 211),
(87, "AB-", "Rookt niet", "Feestdrinker", "l", "Antisociale persoonlijkheidsstoornis", "Paramed", 212),
(88, "AB-", "Rookt niet", "Experimenterend drinker", "e", "Zelfbeschadigend gedrag", "ASR", 213),
(89, "A-", "Rookt niet", "Culturele drinker", "e", "Narcolepsie", "Univé", 214),
(90, "A-", "Rookt niet", "Single occasion drinker", "n", "Slaapapneu", "De Friesland", 215),
(91, "A+", "Rookt niet", "Vervangend drinker", "j", "Obsessieve-compulsieve persoonlijkheidsstoornis", "Zilveren Kruis", 216),
(92, "O+", "Rookt niet", "Routine drinker", " ", "Rumination disorder", "ASR", 217),
(93, "O+", "Rookt niet", "Overmatig drinker", "m", "Eetbuistoornis", "DSW Zorgverzekering", 218),
(94, "AB+", "Rookt niet", "Aangepaste drinker", "a", "Attention Deficit Hyperactivity Disorder (ADHD)", "ASR", 219),
(95, "A+", "Rookt niet", "Functioneel drinker", "e", "Algemene angststoornis", "Zilveren Kruis", 220),
(96, "A+", "Rookt niet", "Feestdrinker", "e", "Narcistische persoonlijkheidsstoornis", "Delta Lloyd", 221),
(97, "AB+", "Rookt niet", "Feestdrinker", "c", "Antisociale persoonlijkheidsstoornis", "DSW Zorgverzekering", 222),
(98, "B-", "Rookt niet", "Dagelijkse drinker", "p", "Schizoaffectieve stoornis", "Polderzorg", 223),
(99, "AB-", "Rookt niet", "Dagelijkse drinker", "c", "Algemene angststoornis", "VGZ", 224),
(100, "A+", "Rookt niet", "Ritueel drinker", "a", "Posttraumatische stressstoornis (PTSS)", "Menzis", 225),
(101, "A+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "ASR", 226),
(102, "AB+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "DSW Zorgverzekering", 227),
(103, "A+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "DSW Zorgverzekering", 228),
(104, "O-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "ASR", 229),
(105, "O+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "DSW", 230),
(106, "A+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Achmea", 231),
(107, "O-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Univé", 232),
(108, "AB-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Menzis", 233),
(109, "AB-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "OHRA", 234),
(110, "A-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "ANWB Zorgverzekering", 235),
(111, "AB+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "ASR", 236),
(112, "A+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "DSW Zorgverzekering", 237),
(113, "AB+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "De Friesland", 238),
(114, "O-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "ANWB Zorgverzekering", 239),
(115, "O+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Delta Lloyd", 240),
(116, "O+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Polderzorg", 241),
(117, "AB-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "CZ", 242),
(118, "A+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "OHRA", 243),
(119, "AB-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Univé", 244),
(120, "AB+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Zorg en Zekerheid", 245),
(121, "B+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "Zorg en Zekerheid", 246),
(122, "B-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "DSW Zorgverzekering", 247),
(123, "O+", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "ANWB Zorgverzekering", 248),
(124, "A-", "Rookt niet", "Drinkt geen drank", "Geen lichamelijke beperkingen", "Geen bijzonderheden", "De Friesland", 249);
