INSERT INTO Onderzoek(onderzoek_id, titel, beschrijving, type, status, Medischedossier_md_nummer, Arts_arts_code)
VALUES
(0, "Volledig bloedbeeld (CBC)", "Een onderzoek dat verschillende componenten van het bloed meet, zoals rode bloedcellen, witte bloedcellen en bloedplaatjes.", "Controle", "Afgerond", 32, 59),
(1, "Elektrolytenpanel", "Meet de niveaus van elektrolyten zoals natrium, kalium en chloride in het bloed, essentieel voor de werking van spieren en zenuwen.", "Diagnostisch onderzoek", "Afgerond", 4, 90),
(2, "Leverfunctieonderzoek", "Beoordeelt de gezondheid van de lever door enzymen en andere stoffen in het bloed te meten.", "Diagnostisch onderzoek", "Afgerond", 18, 132),
(3, "Nierfunctieonderzoek (BUN, creatinine)", "Evalueert de nierfunctie door de concentraties van bloedureumstikstof en creatinine te meten.", "Diagnostisch onderzoek", "Afgerond", 30, 80),
(4, "Lipidenprofiel", "Meet vetten in het bloed, inclusief cholesterol en triglyceriden, om het risico op hartziekten te beoordelen.", "Diagnostisch onderzoek", "Afgerond", 15, 90),
(5, "Bloedsuiker (glucose)", "Meet het suikergehalte in het bloed om diabetes of hypoglykemie te diagnosticeren.", "Controle", "In onderzoek", 36, 141),
(6, "HbA1c (Langetermijnbloedsuiker)", "Evalueert de gemiddelde bloedsuikerspiegel over de afgelopen twee tot drie maanden.", "Controle", "Afgerond", 39, 92),
(7, "Elektrocardiogram (ECG)", "Meet de elektrische activiteit van het hart om hartritmestoornissen en andere hartproblemen te detecteren.", "Controle", "Afgerond", 31, 16),
(8, "C-reactief proteïne (CRP)", "Meet ontstekingsniveaus in het lichaam en kan wijzen op infecties of chronische ontstekingsziekten.", "Diagnostisch onderzoek", "Afgerond", 6, 44),
(9, "Sedimentatiesnelheid (BSE)", "Meet hoe snel rode bloedcellen bezinken in een buis, wat een indicatie kan zijn van ontsteking.", "Diagnostisch onderzoek", "Afgerond", 38, 145),
(10, "Urineanalyse", "Beoordeelt de samenstelling van urine om nierziekten, infecties of andere aandoeningen te detecteren.", "Controle", "Afgerond", 34, 50),
(11, "24-uurs urine-eiwit", "Meet de hoeveelheid eiwit die in urine wordt uitgescheiden over een periode van 24 uur, belangrijk voor nierfunctie.", "Diagnostisch onderzoek", "Afgerond", 26, 141),
(12, "Urine-cultuur", "Detecteert en identificeert bacteriën in de urine om urineweginfecties te diagnosticeren.", "Controle", "Afgerond", 34, 144),
(13, "Microscopische urinesecretie", "Onderzoekt urine onder de microscoop op de aanwezigheid van cellen, kristallen en andere elementen.", "Diagnostisch onderzoek", "Afgerond", 41, 119),
(14, "Urine-pH meting", "Bepaalt de zuurgraad van urine, wat kan helpen bij de diagnose van nierstenen en andere aandoeningen.", "Diagnostisch onderzoek", "In onderzoek", 1, 141),
(15, "Röntgenfoto", "Maakt afbeeldingen van interne structuren van het lichaam, zoals botten en longen, met behulp van röntgenstralen.", "Diagnostisch onderzoek", "In onderzoek", 39, 30),
(16, "Echografie (ultrasound)", "Gebruikt geluidsgolven om beelden van organen en structuren in het lichaam te maken.", "Controle", "Afgerond", 17, 131),
(17, "Magnetic Resonance Imaging (MRI)", "Maakt gedetailleerde beelden van weefsels en organen met behulp van magnetische velden en radiogolven.", "Diagnostisch onderzoek", "In onderzoek", 28, 80),
(18, "Computed Tomography (CT-scan)", "Combineert röntgenbeelden vanuit verschillende hoeken om dwarsdoorsneden van het lichaam te creëren.", "Controle", "In onderzoek", 35, 131),
(19, "Positron Emissie Tomografie (PET-scan)", "Beeldvormingstechniek die de stofwisseling van cellen in het lichaam meet, vaak gebruikt bij kankerdiagnose.", "Diagnostisch onderzoek", "In onderzoek", 5, 81),
(20, "Mammografie", "Röntgenonderzoek van de borsten om borstkanker vroegtijdig te detecteren.", "Diagnostisch onderzoek", "In onderzoek", 29, 53),
(21, "Dichtheidsmeting botten (DEXA-scan)", "Meet de botdichtheid om osteoporose en het risico op botbreuken te beoordelen.", "Controle", "In onderzoek", 22, 87),
(22, "Nucleaire geneeskunde scans (zoals schildklier scan)", "Gebruik radioactieve stoffen om de functie en structuur van organen te onderzoeken.", "Diagnostisch onderzoek", "Afgerond", 51, 53),
(23, "Fluoroscopie", "Real-time bewegende röntgenbeelden gebruikt om functies van interne organen te bestuderen.", "Controle", "Afgerond", 30, 90),
(24, "Angiografie", "Beeldvorming van bloedvaten met contrastmiddelen om bloedvatafwijkingen te detecteren.", "Diagnostisch onderzoek", "Afgerond", 18, 138),
(25, "Holter-monitoring", "Continue ECG-monitoring gedurende 24-48 uur om hartritmestoornissen te detecteren.", "Diagnostisch onderzoek", "Afgerond", 15, 70),
(26, "Stress-test (inspanningstest)", "Beoordeelt de hartfunctie tijdens fysieke inspanning om cardiovasculaire gezondheid te beoordelen.", "Diagnostisch onderzoek", "Afgerond", 5, 59),
(27, "Echocardiogram", "Ultrasoundonderzoek van het hart om de structuur en functie van het hart te evalueren.", "Controle", "Afgerond", 29, 59),
(28, "Bloeddrukmeting", "Meet de druk van het bloed tegen de wanden van de bloedvaten, essentieel voor het diagnosticeren van hypertensie.", "Controle", "Afgerond", 49, 92),
(29, "Ankle-Brachial Index (ABI)", "Vergelijkt de bloeddruk in enkels met die in armen om perifere arteriële aandoeningen te detecteren.", "Controle", "Afgerond", 52, 90),
(30, "Cardiale MRI", "Gedetailleerde beeldvorming van het hart en de grote bloedvaten met behulp van MRI-technologie.", "Controle", "In onderzoek", 16, 16),
(31, "Cardiale CT-scan", "Beeldvorming van het hart en de bloedvaten met een CT-scan voor het detecteren van aderverkalking en andere hartproblemen.", "Controle", "Afgerond", 52, 131),
(32, "Elektrofysiologisch onderzoek", "Onderzoekt de elektrische activiteiten van het hart om hartritmestoornissen te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 28, 141),
(33, "Spiroergometrie", "Beoordeelt de longfunctie en het zuurstofgebruik tijdens inspanning.", "Controle", "In onderzoek", 51, 119),
(34, "Spirometrie", "Meet de longfunctie door de hoeveelheid en snelheid van uitgeademde lucht te bepalen.", "Diagnostisch onderzoek", "In onderzoek", 3, 132),
(35, "Longvolume-metingen", "Bepaalt de verschillende longvolumes en capaciteit om longziekten te diagnosticeren.", "Controle", "In onderzoek", 20, 138),
(36, "Peak flow meting", "Meet de maximale snelheid van uitgeademde lucht, vaak gebruikt bij astma management.", "Controle", "Afgerond", 42, 92),
(37, "Bronchoscopy", "Visueel onderzoek van de luchtwegen met een bronchoscoop om afwijkingen te identificeren.", "Controle", "In onderzoek", 14, 50),
(38, "Pulmonaire functionele tests", "Evalueert de ademhalingsfunctie en efficiëntie van de longen.", "Controle", "In onderzoek", 45, 87),
(39, "Allergietests", "Identificeert allergenen die allergische reacties veroorzaken.", "Controle", "Afgerond", 11, 50),
(40, "Hepatitis panel", "Test op verschillende hepatitisvirussen om leverinfecties te diagnosticeren.", "Controle", "Afgerond", 16, 90),
(41, "HIV-test", "Detecteert de aanwezigheid van het HIV-virus in het lichaam.", "Diagnostisch onderzoek", "In onderzoek", 29, 141),
(42, "Thyroïd functieonderzoek", "Meet hormonen zoals TSH, T3 en T4 om schildklierproblemen te diagnosticeren.", "Controle", "Afgerond", 33, 59),
(43, "Vitamin D-test", "Bepaalt het niveau van vitamine D in het bloed, belangrijk voor botgezondheid en immuunfunctie.", "Diagnostisch onderzoek", "Afgerond", 10, 50),
(44, "Prostaat-specifiek antigeen (PSA) test", "Meet het PSA-niveau om prostaatkanker en andere prostaatproblemen te screenen.", "Diagnostisch onderzoek", "Afgerond", 24, 138),
(45, "Pap-test", "Beoordeelt celveranderingen in de baarmoederhals om baarmoederhalskanker te detecteren.", "Controle", "In onderzoek", 50, 118),
(46, "Coloscopie", "Visueel onderzoek van de dikke darm en endeldarm met een coloscope om afwijkingen te identificeren.", "Diagnostisch onderzoek", "Afgerond", 5, 145),
(47, "Gastroscopie", "Onderzoek van de maag en de eerste delen van de dunne darm met een gastroscoop.", "Diagnostisch onderzoek", "In onderzoek", 34, 141),
(48, "Biopsie", "Verzamelen van weefselmonsters voor microscopisch onderzoek om ziekten zoals kanker te diagnosticeren.", "Diagnostisch onderzoek", "Afgerond", 49, 138),
(49, "Cytologie", "Analyseert cellen om afwijkingen of kankercellen te identificeren.", "Controle", "Afgerond", 44, 80),
(50, "Genetische testen", "Onderzoekt DNA om genetische afwijkingen en erfelijke ziekten te detecteren.", "Diagnostisch onderzoek", "In onderzoek", 30, 92),
(51, "Urine-cytologie", "Analyseert urine op abnormale cellen, vaak gebruikt bij de detectie van blaaskanker.", "Controle", "Afgerond", 51, 132),
(52, "Slaaponderzoek (Polysomnografie)", "Evalueert slaapkwaliteit en diagnoseert slaapstoornissen zoals slaapapneu.", "Controle", "Afgerond", 17, 119),
(53, "Neuropsychologisch onderzoek", "Beoordeelt cognitieve functies zoals geheugen, aandacht en probleemoplossend vermogen.", "Controle", "In onderzoek", 0, 92),
(54, "EEG (Elektro-encefalogram)", "Meet de elektrische activiteit van de hersenen om epilepsie en andere neurologische aandoeningen te diagnosticeren.", "Controle", "In onderzoek", 13, 118),
(55, "EMG (Elektromyografie)", "Evalueert de elektrische activiteit van spieren om neuromusculaire aandoeningen te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 32, 81),
(56, "Lumbar puncture (ruggenprik)", "Verzamelt cerebrospinale vloeistof voor onderzoek naar infecties, ontstekingen en andere neurologische aandoeningen.", "Diagnostisch onderzoek", "In onderzoek", 2, 132),
(57, "MRI van de hersenen", "Gedetailleerde beeldvorming van de hersenen om afwijkingen zoals tumoren, beroertes of multiple sclerose te detecteren.", "Diagnostisch onderzoek", "In onderzoek", 25, 141),
(58, "CT-scan van de hersenen", "Beeldvorming van de hersenen met een CT-scan voor het opsporen van bloedingen, tumoren en andere hersenaandoeningen.", "Diagnostisch onderzoek", "Afgerond", 20, 92),
(59, "PET-scan van de hersenen", "Beeldvorming die de stofwisseling van hersencellen meet, vaak gebruikt bij de diagnose van kanker en neurologische aandoeningen.", "Diagnostisch onderzoek", "In onderzoek", 49, 92),
(60, "Arteriografie", "Beeldvorming van slagaders met contrastmiddel om vaatziekten te diagnosticeren.", "Controle", "In onderzoek", 2, 50),
(61, "Venografie", "Beeldvorming van aders met contrastmiddel om veneuze aandoeningen te identificeren.", "Controle", "In onderzoek", 29, 144),
(62, "Spirometrie met diffusiecapaciteit", "Meet de longfunctie en de capaciteit van de longen om gasuitwisseling te faciliteren.", "Diagnostisch onderzoek", "Afgerond", 43, 87),
(63, "Krachtmetingen spierkracht", "Evalueert de spierkracht om spierziekten en zenuwstoornissen te diagnosticeren.", "Diagnostisch onderzoek", "Afgerond", 49, 50),
(64, "Bewegingstesten (bijv. gait analysis)", "Analyseert het looppatroon om bewegingsstoornissen en musculoskeletale problemen te identificeren.", "Controle", "In onderzoek", 32, 16),
(65, "Hormonale panelen", "Meet verschillende hormonen om endocriene stoornissen te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 24, 131),
(66, "Antilichamen testen", "Detecteert antilichamen in het bloed om auto-immuunziekten en infecties te diagnosticeren.", "Controle", "Afgerond", 1, 50),
(67, "Tumormarkers", "Meet specifieke stoffen in het bloed die kunnen wijzen op kanker.", "Controle", "Afgerond", 37, 110),
(68, "Lactaat dehydrogenase (LDH) test", "Meet het LDH-niveau, wat kan wijzen op weefselschade of bepaalde vormen van kanker.", "Controle", "In onderzoek", 16, 144),
(69, "Amylase en lipase testen", "Evalueert enzymen die lever- en alvleesklieraandoeningen kunnen signaleren.", "Controle", "In onderzoek", 48, 119),
(70, "Procalcitonine test", "Meet het niveau van procalcitonine als marker voor bacteriële infecties en sepsis.", "Diagnostisch onderzoek", "In onderzoek", 44, 138),
(71, "Immunoglobuline testen", "Meet de niveaus van verschillende immunoglobulinen om immuunstoornissen te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 17, 110),
(72, "Ferritine test", "Meet het ferritinegehalte om ijzertekorten of -overlading te diagnosticeren.", "Controle", "Afgerond", 46, 90),
(73, "B12 en foliumzuur testen", "Evalueert niveaus van vitamine B12 en foliumzuur, belangrijk voor bloedvorming en zenuwfunctie.", "Controle", "Afgerond", 37, 132),
(74, "Serologische testen", "Detecteert antilichamen of antigenen in het bloed voor de diagnose van infectieziekten.", "Controle", "In onderzoek", 0, 92),
(75, "PCR (Polymerase Chain Reaction)", "Versterkt DNA-segmenten voor het detecteren van genetische afwijkingen en infecties.", "Controle", "Afgerond", 19, 50),
(76, "Western blot", "Detecteert specifieke eiwitten in een monster, vaak gebruikt voor HIV-diagnostiek.", "Diagnostisch onderzoek", "In onderzoek", 38, 16),
(77, "ELISA (Enzyme-Linked Immunosorbent Assay)", "Detecteert en kwantificeert antilichamen of antigenen in biologische monsters.", "Controle", "Afgerond", 7, 144),
(78, "Flowcytometrie", "Analyseert fysieke en chemische eigenschappen van cellen of deeltjes in een vloeistof.", "Controle", "Afgerond", 24, 110),
(79, "Microbiologische kweek", "Groeit micro-organismen uit klinische monsters voor identificatie en gevoeligheidstesten.", "Diagnostisch onderzoek", "In onderzoek", 32, 92),
(80, "Klinische beeldvorming met contrastmiddelen", "Gebruikt contrastmiddelen om de zichtbaarheid van structuren tijdens beeldvorming te verbeteren.", "Diagnostisch onderzoek", "Afgerond", 32, 141),
(81, "Intracraniale drukmeting", "Meet de druk binnen de schedel om aandoeningen zoals hydrocephalus of hersenletsel te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 41, 110),
(82, "Arteriële bloedgasanalyse", "Evalueert zuurstof- en kooldioxidegehaltes in het bloed om de longfunctie en metabolische status te beoordelen.", "Diagnostisch onderzoek", "In onderzoek", 42, 44),
(83, "Capnografie", "Meet de concentratie kooldioxide in de uitgeademde lucht, vaak gebruikt tijdens anesthesie.", "Controle", "Afgerond", 34, 110),
(84, "Glomerulaire filtratiesnelheid (GFR)", "Bepaalt de nierfiltratiefunctie om nierziekten te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 14, 81),
(85, "Bilirubinetest", "Meet het bilirubinegehalte om lever- en galwegproblemen te identificeren.", "Diagnostisch onderzoek", "In onderzoek", 32, 86),
(86, "Albumine-test", "Meet het albuminegehalte in het bloed om lever- en nierfuncties te beoordelen.", "Controle", "In onderzoek", 42, 145),
(87, "Transaminasen (AST, ALT) testen", "Evalueert leverenzymen om leverbeschadiging te detecteren.", "Controle", "Afgerond", 48, 53),
(88, "Gamma-glutamyltransferase (GGT) test", "Meet GGT-niveaus om leverziekten en galwegobstructies te diagnosticeren.", "Controle", "In onderzoek", 50, 90),
(89, "Alkalische fosfatase (ALP) test", "Evalueert ALP-niveaus voor de diagnose van lever-, galweg- en botziekten.", "Diagnostisch onderzoek", "Afgerond", 43, 138),
(90, "Lactaattest", "Meet lactaatniveaus om weefsellacetaatproductie en zuurstoftekort te beoordelen.", "Diagnostisch onderzoek", "Afgerond", 42, 30),
(91, "Troponine test", "Detecteert hartspierbeschadiging, vaak gebruikt bij de diagnose van hartinfarct.", "Controle", "Afgerond", 3, 30),
(92, "BNP (B-type natriuretisch peptide) test", "Meet BNP-niveaus om hartfalen te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 3, 59),
(93, "D-dimeer test", "Detecteert fibrine-afbraakproducten om de aanwezigheid van bloedstolsels te beoordelen.", "Controle", "In onderzoek", 43, 118),
(94, "Serum proteïne electrophorese", "Scheidt eiwitten in het bloed om afwijkingen zoals multiple myeloom te diagnosticeren.", "Controle", "In onderzoek", 9, 118),
(95, "Electrolyten herzien", "Beoordeelt de balans van elektrolyten voor de diagnose van verschillende aandoeningen.", "Diagnostisch onderzoek", "Afgerond", 11, 86),
(96, "Celiac disease panel", "Detecteert antilichamen geassocieerd met coeliakie om de diagnose te bevestigen.", "Diagnostisch onderzoek", "In onderzoek", 9, 86),
(97, "HIV-viral load test", "Meet de hoeveelheid HIV-virus in het bloed om de progressie van de infectie te volgen.", "Controle", "In onderzoek", 11, 16),
(98, "Hepatitis C RNA test", "Detecteert het RNA van hepatitis C virus voor bevestiging van een actieve infectie.", "Controle", "In onderzoek", 22, 53),
(99, "Antistreptolysine O (ASO) test", "Meet ASO-antilichamen om recente streptokokkeninfecties te identificeren.", "Controle", "Afgerond", 37, 132),
(100, "Rheumatoid factor (RF) test", "Detecteert RF-antilichamen die geassocieerd zijn met reumatoïde artritis.", "Diagnostisch onderzoek", "In onderzoek", 3, 110),
(101, "Anti-CCP test", "Detecteert anti-cyclic citrullinated peptide-antilichamen voor de diagnose van reumatoïde artritis.", "Controle", "In onderzoek", 49, 53),
(102, "SLE panel (Systemische Lupus Erythematosus)", "Bevat tests zoals ANA om lupus en andere auto-immuunziekten te diagnosticeren.", "Controle", "Afgerond", 16, 131),
(103, "Complement niveaus (C3, C4)", "Meet complement-eiwit niveaus om immuunreacties en ontstekingen te evalueren.", "Controle", "In onderzoek", 29, 132),
(104, "HBA1c varianten", "Evalueert specifieke varianten van HbA1c voor nauwkeurige diabetesmonitoring.", "Controle", "In onderzoek", 44, 119),
(105, "Auto-antistoffen testen", "Detecteert auto-antistoffen die betrokken zijn bij auto-immuunziekten.", "Diagnostisch onderzoek", "In onderzoek", 26, 110),
(106, "Metabolisch panel", "Beoordeelt verschillende metabolieten en elektrolyten om de algemene gezondheid te beoordelen.", "Diagnostisch onderzoek", "Afgerond", 31, 81),
(107, "T3 en T4 testen", "Meet schildklierhormonen om hyperthyreoïdie of hypothyreoïdie te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 2, 59),
(108, "TSH (Thyroid Stimulating Hormone) test", "Evalueert de schildklierfunctie door het meten van TSH-niveaus.", "Diagnostisch onderzoek", "Afgerond", 27, 87),
(109, "Serum calcium test", "Meet calciumspiegels in het bloed voor de diagnose van bot- en nierziekten.", "Controle", "Afgerond", 2, 80),
(110, "Serum magnesium test", "Evalueert magnesiumniveaus om elektrolytenbalans en spierfunctie te beoordelen.", "Diagnostisch onderzoek", "In onderzoek", 12, 138),
(111, "Serum fosfaat test", "Meet fosfaatspiegels in het bloed, belangrijk voor botgezondheid en energieproductie.", "Controle", "In onderzoek", 13, 138),
(112, "Albumine-creatinine ratio", "Evalueert nierfunctie door de verhouding tussen albumine en creatinine in urine te meten.", "Diagnostisch onderzoek", "In onderzoek", 15, 131),
(113, "Serum osmolaliteit", "Meet de concentratie van opgeloste deeltjes in het bloed voor de beoordeling van vochtbalans.", "Diagnostisch onderzoek", "In onderzoek", 0, 138),
(114, "Serum anion gap", "Berekening die helpt bij de diagnose van acidose en andere elektrolytstoornissen.", "Controle", "Afgerond", 16, 30),
(115, "Serum lactate", "Meet lactaatniveaus om zuurstoftekort en weefselschade te detecteren.", "Diagnostisch onderzoek", "Afgerond", 12, 132),
(116, "Urine osmolaliteit", "Evalueert de concentratie van urine om nierfunctie en hydratatiestatus te beoordelen.", "Controle", "In onderzoek", 41, 44),
(117, "Arteriële bloedgassen", "Analyseert zuurstof- en kooldioxidegehaltes in het bloed voor ademhalings- en metabolische stoornissen.", "Controle", "Afgerond", 48, 50),
(118, "Serum amyloïde A (SAA)", "Meet SAA-niveaus als marker voor acute ontsteking.", "Controle", "Afgerond", 36, 132),
(119, "Plasmacells onderzoek", "Evalueert plasmacellen in het bloed of beenmerg voor aandoeningen zoals multiple myeloom.", "Diagnostisch onderzoek", "Afgerond", 0, 141),
(120, "Cytomegalovirus (CMV) test", "Detecteert CMV-infecties, vooral belangrijk bij immuungecompromitteerde patiënten.", "Controle", "In onderzoek", 27, 87),
(121, "Epstein-Barr Virus (EBV) test", "Detecteert EBV-infecties die geassocieerd zijn met ziekten zoals mononucleosis.", "Controle", "In onderzoek", 10, 81),
(122, "Herpes simplex virus (HSV) test", "Detecteert HSV-infecties die huid- en slijmvliesinfecties veroorzaken.", "Diagnostisch onderzoek", "In onderzoek", 33, 92),
(123, "Varicella-Zoster Virus (VZV) test", "Detecteert VZV-infecties, waaronder waterpokken en gordelroos.", "Diagnostisch onderzoek", "Afgerond", 41, 90),
(124, "Hepatitis B surface antigen (HBsAg) test", "Detecteert het oppervlakte-antigeen van hepatitis B virus voor actieve infectie.", "Diagnostisch onderzoek", "In onderzoek", 31, 81),
(125, "HIV-antilichaam en antigeen test", "Detecteert zowel antilichamen als antigenen voor vroege diagnose van HIV.", "Controle", "In onderzoek", 52, 118),
(126, "Syfilis test (RPR, VDRL)", "Detecteert syfilis-infectie door middel van serologische testen.", "Controle", "In onderzoek", 50, 59),
(127, "Tuberculose (TB) test (Mantoux)", "Beoordeelt blootstelling aan tuberculose door huidtesten.", "Diagnostisch onderzoek", "Afgerond", 3, 118),
(128, "Interferon-gamma release assays (IGRAs)", "Detecteert tuberculose-infectie door het meten van immuunreacties op TB-antigenen.", "Diagnostisch onderzoek", "In onderzoek", 16, 119),
(129, "Lactose intolerantie test", "Evalueert de capaciteit van het lichaam om lactose te verteren.", "Diagnostisch onderzoek", "In onderzoek", 22, 59),
(130, "Coeliakie genetische testen", "Identificeert genetische markers geassocieerd met coeliakie.", "Diagnostisch onderzoek", "Afgerond", 44, 50),
(131, "Fructose intolerantie test", "Evalueert de capaciteit van het lichaam om fructose te verteren.", "Diagnostisch onderzoek", "In onderzoek", 45, 16),
(132, "Zinkmeting", "Meet zinkniveaus in het bloed voor de diagnose van zinktekorten of -overdoses.", "Diagnostisch onderzoek", "Afgerond", 7, 81),
(133, "Selenium test", "Evalueert seleniumniveaus voor de diagnose van tekorten of toxiciteit.", "Diagnostisch onderzoek", "Afgerond", 44, 80),
(134, "Cholesterol subtypes", "Beoordeelt verschillende typen cholesterol, zoals HDL, LDL en VLDL.", "Controle", "Afgerond", 23, 16),
(135, "Triglyceriden test", "Meet de niveaus van triglyceriden in het bloed, belangrijk voor hartgezondheid.", "Diagnostisch onderzoek", "Afgerond", 36, 132),
(136, "Apoproteïne testen", "Evalueert apoproteïnen zoals ApoA en ApoB voor hartziekte risico's.", "Diagnostisch onderzoek", "In onderzoek", 30, 110),
(137, "Homocysteïne test", "Meet homocysteïneniveaus als risicofactor voor hartziekten en beroertes.", "Controle", "Afgerond", 23, 87),
(138, "Genetisch screenen op BRCA1/BRCA2", "Detecteert genetische mutaties die het risico op borstkanker en eierstokkanker verhogen.", "Diagnostisch onderzoek", "Afgerond", 51, 92),
(139, "HLA typing", "Identificeert menselijke leukocytenantigenen voor transplantatie- en auto-immuunziekte diagnoses.", "Controle", "In onderzoek", 3, 81),
(140, "Natriuretische peptiden", "Meet niveaus van natriuretische peptiden voor de evaluatie van hartfalen.", "Controle", "Afgerond", 9, 131),
(141, "Beta-2 microglobuline test", "Evalueert het niveau van beta-2 microglobuline voor de diagnose van nierziekten en bepaalde kankers.", "Controle", "In onderzoek", 52, 50),
(142, "Serum ferritine", "Meet ferritine voor de evaluatie van ijzeropslag in het lichaam.", "Diagnostisch onderzoek", "In onderzoek", 25, 59),
(143, "Karnosine test", "Evalueert karnosine niveaus, een antioxidant in het lichaam.", "Diagnostisch onderzoek", "In onderzoek", 13, 118),
(144, "Zink-ionen test", "Meet vrije zinkionen in het bloed, belangrijk voor immuunfunctie en enzymatische processen.", "Controle", "Afgerond", 38, 80),
(145, "Sideroferet test", "Beoordeelt ijzerbindend vermogen van het bloed voor diagnose van anemie.", "Controle", "In onderzoek", 8, 70),
(146, "Methylmalonzuur test", "Meet methylmalonzuurniveaus voor de diagnose van vitamine B12 tekort.", "Diagnostisch onderzoek", "In onderzoek", 35, 110),
(147, "Homocysteïne en folaat panel", "Evalueert homocysteïne en folaat niveaus voor hart- en vaatziekten risicobeoordeling.", "Diagnostisch onderzoek", "In onderzoek", 43, 44),
(148, "Urine-cortisol test", "Meet cortisol niveaus in urine om bijnierfuncties te evalueren.", "Controle", "Afgerond", 33, 138),
(149, "ACTH test", "Meet adrenocorticotroop hormoon niveaus voor de diagnose van bijnieraandoeningen.", "Controle", "In onderzoek", 48, 131),
(150, "Insulinetest", "Evalueert insulineniveaus om diabetes en insulineresistentie te diagnosticeren.", "Controle", "In onderzoek", 18, 70),
(151, "C-peptide test", "Meet C-peptide niveaus als indicator van endogene insulineproductie.", "Diagnostisch onderzoek", "Afgerond", 45, 80),
(152, "Glucagon test", "Evalueert de respons van de alvleesklier op glucagon voor diabetes diagnose.", "Controle", "Afgerond", 0, 87),
(153, "Serum ketonen", "Meet ketonen in het bloed voor de diagnose van ketoacidose en metabolische stoornissen.", "Controle", "In onderzoek", 39, 53),
(154, "Prolactine test", "Meet prolactineniveaus om hormonale stoornissen en pituitary aandoeningen te diagnosticeren.", "Controle", "Afgerond", 21, 90),
(155, "Luteïniserend hormoon (LH) test", "Evalueert LH niveaus voor reproductieve gezondheidsdiagnoses.", "Diagnostisch onderzoek", "Afgerond", 51, 81),
(156, "Follikelstimulerend hormoon (FSH) test", "Meet FSH niveaus voor de evaluatie van voortplantingsstoornissen.", "Diagnostisch onderzoek", "In onderzoek", 20, 80),
(157, "Estradiol test", "Meet estradiol niveaus voor de evaluatie van vrouwelijke reproductieve gezondheid.", "Diagnostisch onderzoek", "Afgerond", 37, 141),
(158, "Testosteron test", "Evalueert testosteronniveaus voor de diagnose van hormonale stoornissen.", "Controle", "In onderzoek", 34, 118),
(159, "Progesteron test", "Meet progesteronniveaus voor de evaluatie van de menstruatiecyclus en vruchtbaarheid.", "Controle", "Afgerond", 31, 30),
(160, "DHEA-S test", "Evalueert de niveaus van dehydroepiandrosteron-sulfaat voor de diagnose van bijnierstoornissen.", "Controle", "Afgerond", 24, 90),
(161, "Androstenedione test", "Meet androstenedioneniveaus voor de evaluatie van androgenen productie.", "Controle", "Afgerond", 46, 119),
(162, "Renine en aldosteron testen", "Evalueert renine en aldosteronniveaus voor de diagnose van hypertensie en bijnieraandoeningen.", "Controle", "Afgerond", 20, 86),
(163, "Metaanalyse van laboratoriumresultaten", "Integreert verschillende laboratoriumtestresultaten voor een holistische diagnostische evaluatie.", "Diagnostisch onderzoek", "Afgerond", 51, 81),
(164, "Serum albumine test", "Meet albumine niveaus in het bloed voor de evaluatie van lever- en nierfuncties.", "Diagnostisch onderzoek", "Afgerond", 30, 70),
(165, "Serum globuline test", "Evalueert globuline niveaus voor de diagnose van immuun- en leverziekten.", "Controle", "Afgerond", 24, 30),
(166, "Apolipoproteïne E (ApoE) test", "Beoordeelt ApoE genotypen voor risico op Alzheimer en cardiovasculaire ziekten.", "Controle", "Afgerond", 9, 70),
(167, "Serum uric acid test", "Meet uric acid niveaus voor de diagnose van jicht en nierstenen.", "Controle", "In onderzoek", 13, 132),
(168, "Celiac serologie", "Bevat testen zoals tTG-IgA voor de diagnose van coeliakie.", "Diagnostisch onderzoek", "In onderzoek", 44, 80),
(169, "HLA-B27 test", "Detecteert het HLA-B27 antigen, geassocieerd met spondyloartritis en andere auto-immuunziekten.", "Diagnostisch onderzoek", "In onderzoek", 50, 44),
(170, "Rheuma panel", "Bevat verschillende tests voor de diagnose van reumatische aandoeningen.", "Diagnostisch onderzoek", "In onderzoek", 7, 119),
(171, "Serum viscosity", "Meet de stroperigheid van het bloed voor de diagnose van multiple myeloom en andere aandoeningen.", "Diagnostisch onderzoek", "In onderzoek", 48, 70),
(172, "Serum protein electrophoresis (SPEP)", "Scheidt en kwantificeert eiwitten in het bloed voor de diagnose van immunoglobulineziekten.", "Diagnostisch onderzoek", "Afgerond", 52, 141),
(173, "Immunofixatie electrophoresis (IFE)", "Identificeert specifieke immunoglobulines voor de diagnose van multiple myeloom en andere aandoeningen.", "Diagnostisch onderzoek", "Afgerond", 40, 132),
(174, "Serum amyloid A (SAA) test", "Meet SAA niveaus als een acute fase reactant voor ontstekingsdiagnostiek.", "Diagnostisch onderzoek", "Afgerond", 43, 53),
(175, "Ferritine en transferrine saturatie", "Evalueert ijzeropslag en transport in het lichaam voor de diagnose van anemie.", "Controle", "In onderzoek", 10, 110),
(176, "Haptoglobine test", "Meet haptoglobine niveaus voor de diagnose van hemolytische anemie.", "Diagnostisch onderzoek", "In onderzoek", 0, 90),
(177, "Serum ceruloplasmine test", "Meet ceruloplasmine niveaus voor de diagnose van de ziekte van Wilson.", "Controle", "Afgerond", 52, 144),
(178, "Alpha-1 antitrypsine test", "Evalueert niveaus van alpha-1 antitrypsine voor de diagnose van lever- en longziekten.", "Controle", "In onderzoek", 15, 90),
(179, "Parathyroïde hormoon (PTH) test", "Meet PTH niveaus voor de diagnose van parathyroïd functionele stoornissen.", "Controle", "In onderzoek", 50, 70),
(180, "Osteocalcine test", "Evalueert osteocalcine niveaus voor de diagnose van botmetabolisme en osteoporose.", "Controle", "In onderzoek", 14, 30),
(181, "Serum alkaline phosphatase isoenzymen", "Scheidt ALP isoenzymen voor de diagnose van lever- en botziekten.", "Controle", "Afgerond", 34, 30),
(182, "Sideroblasten telling", "Beoordeelt de aanwezigheid van sideroblasten in het beenmerg voor de diagnose van sideroblastaire anemie.", "Diagnostisch onderzoek", "In onderzoek", 16, 144),
(183, "Serum proteinase 3 (PR3) en myeloperoxidase (MPO) antilichamen", "Detecteert ANCA (anti-neutrophil cytoplasmic antibodies) voor de diagnose van vasculitis.", "Controle", "Afgerond", 33, 110),
(184, "Neutrofiele functie testen", "Evalueert de functie van neutrofielen voor de diagnose van immuungecompromitteerde aandoeningen.", "Diagnostisch onderzoek", "Afgerond", 46, 86),
(185, "Serum tryptase test", "Meet tryptase niveaus voor de diagnose van systemische anafylaxie en myeloïde proliferatieve aandoeningen.", "Controle", "Afgerond", 26, 50),
(186, "Kappa en lambda light chains", "Evalueert lichtketen niveaus voor de diagnose van multiple myeloom en andere plasmacelziekten.", "Diagnostisch onderzoek", "In onderzoek", 4, 110),
(187, "Serum β2-microglobuline test", "Meet β2-microglobuline niveaus voor de diagnose van nierziekten en bepaalde kankers.", "Diagnostisch onderzoek", "In onderzoek", 8, 70),
(188, "Serum uridine test", "Evalueert uridine niveaus voor de diagnose van metabole stoornissen.", "Diagnostisch onderzoek", "In onderzoek", 26, 59),
(189, "Thyroglobuline test", "Meet thyroglobuline niveaus voor de monitoring van schildklierkanker.", "Diagnostisch onderzoek", "In onderzoek", 41, 144),
(190, "Ammoniak test", "Meet ammoniak niveaus in het bloed voor de diagnose van leverfalen en metabole stoornissen.", "Controle", "Afgerond", 33, 30),
(191, "Serum ammonia", "Evalueert ammonia niveaus voor de diagnose van leverfunctiestoornissen en ureumcyclusdefecten.", "Controle", "In onderzoek", 17, 50),
(192, "Vitaminen panel", "Beoordeelt verschillende vitaminen niveaus voor de diagnose van tekorten en toxiciteit.", "Controle", "In onderzoek", 20, 59),
(193, "Mineralen panel", "Meet niveaus van essentiële mineralen zoals calcium, magnesium en kalium.", "Diagnostisch onderzoek", "In onderzoek", 19, 92),
(194, "Serum albumine/globuline ratio", "Evalueert de verhouding tussen albumine en globuline voor de diagnose van lever- en nierziekten.", "Diagnostisch onderzoek", "Afgerond", 9, 44),
(195, "Insuline-like growth factor (IGF) test", "Meet IGF niveaus voor de diagnose van groeistoornissen en acromegalie.", "Controle", "In onderzoek", 38, 53),
(196, "Serum iron binding capacity (TIBC)", "Evalueert de totale ijzerbindende capaciteit van het bloed voor de diagnose van anemie.", "Diagnostisch onderzoek", "In onderzoek", 39, 110),
(197, "Serum folate test", "Meet folaat niveaus voor de diagnose van vitamine B12 tekort en megaloblastische anemie.", "Controle", "Afgerond", 5, 16),
(198, "Serum homocysteïne", "Evalueert homocysteïneniveaus als risicofactor voor cardiovasculaire ziekten.", "Controle", "Afgerond", 32, 119),
(199, "Serum ceruloplasmine", "Meet ceruloplasmine niveaus voor de diagnose van de ziekte van Wilson.", "Controle", "In onderzoek", 27, 92),
(200, "Serum aldolase test", "Evalueert aldolase niveaus voor de diagnose van spierziekten en leverziekten.", "Diagnostisch onderzoek", "Afgerond", 23, 30),
(201, "Serum myoglobin test", "Meet myoglobine niveaus voor de diagnose van spierbeschadiging en myocardinfarct.", "Controle", "In onderzoek", 14, 145),
(202, "Myositis panel", "Bevat verschillende tests voor de diagnose van inflammatoire spierziekten.", "Controle", "Afgerond", 29, 81),
(203, "Serum lactate dehydrogenase (LDH)", "Meet LDH niveaus als marker voor weefselschade en bepaalde vormen van kanker.", "Controle", "Afgerond", 3, 87),
(204, "Serum creatine kinase (CK)", "Evalueert CK niveaus voor de diagnose van spierbeschadiging en myocardinfarct.", "Diagnostisch onderzoek", "In onderzoek", 28, 92),
(205, "Serum sodium test", "Meet natriumspiegels voor de diagnose van elektrolytstoornissen en hydratatiestatus.", "Diagnostisch onderzoek", "Afgerond", 47, 90),
(206, "Serum potassium test", "Evalueert kaliumspiegels voor de diagnose van elektrolytstoornissen en spierfunctie.", "Diagnostisch onderzoek", "Afgerond", 15, 92),
(207, "Serum chloride test", "Meet chloride niveaus voor de diagnose van elektrolytstoornissen en acidose.", "Controle", "In onderzoek", 20, 119),
(208, "Serum bicarbonate test", "Evalueert bicarbonaat niveaus voor de diagnose van acidose en alkalose.", "Diagnostisch onderzoek", "In onderzoek", 46, 59),
(209, "Serum phosphate test", "Meet fosfaatspiegels voor de diagnose van bot- en nierziekten.", "Diagnostisch onderzoek", "Afgerond", 22, 16),
(210, "Serum magnesium test", "Evalueert magnesiumspiegels voor de diagnose van elektrolytstoornissen en spierfunctie.", "Diagnostisch onderzoek", "Afgerond", 35, 138),
(211, "Serum calcium test", "Meet calciumspiegels voor de diagnose van bot- en nierziekten.", "Controle", "Afgerond", 49, 144),
(212, "Serum albumin test", "Evalueert albumine niveaus voor de diagnose van lever- en nierziekten.", "Controle", "In onderzoek", 37, 141),
(213, "Serum total protein", "Meet totale eiwitniveaus voor de diagnose van diverse aandoeningen.", "Controle", "Afgerond", 1, 50),
(214, "Serum globulins", "Evalueert globuline niveaus voor de diagnose van immuun- en leverziekten.", "Controle", "Afgerond", 45, 86),
(215, "Serum bilirubine test", "Meet bilirubine niveaus voor de diagnose van lever- en galwegproblemen.", "Controle", "In onderzoek", 49, 50),
(216, "Serum alkaline phosphatase (ALP)", "Evalueert ALP niveaus voor de diagnose van lever-, galweg- en botziekten.", "Diagnostisch onderzoek", "In onderzoek", 45, 144),
(217, "Serum gamma-glutamyltransferase (GGT)", "Meet GGT niveaus voor de diagnose van leverziekten en galwegobstructies.", "Controle", "Afgerond", 45, 131),
(218, "Serum aspartate aminotransferase (AST)", "Evalueert AST niveaus voor de diagnose van lever- en spierziekten.", "Controle", "Afgerond", 17, 131),
(219, "Serum alanine aminotransferase (ALT)", "Meet ALT niveaus voor de diagnose van leverbeschadiging.", "Controle", "Afgerond", 10, 110),
(220, "Serum lactate", "Evalueert lactaat niveaus voor de diagnose van zuurstoftekort en weefselschade.", "Diagnostisch onderzoek", "In onderzoek", 16, 53);
