INSERT INTO Onderzoek(onderzoek_id, titel, beschrijving, type, status, Medischedossier_md_nummer, Arts_arts_code)
VALUES
(0, "Volledig bloedbeeld (CBC)", "Een onderzoek dat verschillende componenten van het bloed meet, zoals rode bloedcellen, witte bloedcellen en bloedplaatjes.", "Diagnostisch onderzoek", "In onderzoek", 17, 109),
(1, "Elektrolytenpanel", "Meet de niveaus van elektrolyten zoals natrium, kalium en chloride in het bloed, essentieel voor de werking van spieren en zenuwen.", "Controle", "Afgerond", 38, 91),
(2, "Leverfunctieonderzoek", "Beoordeelt de gezondheid van de lever door enzymen en andere stoffen in het bloed te meten.", "Diagnostisch onderzoek", "Afgerond", 38, 48),
(3, "Nierfunctieonderzoek (BUN, creatinine)", "Evalueert de nierfunctie door de concentraties van bloedureumstikstof en creatinine te meten.", "Controle", "Afgerond", 45, 109),
(4, "Lipidenprofiel", "Meet vetten in het bloed, inclusief cholesterol en triglyceriden, om het risico op hartziekten te beoordelen.", "Diagnostisch onderzoek", "Afgerond", 23, 68),
(5, "Bloedsuiker (glucose)", "Meet het suikergehalte in het bloed om diabetes of hypoglykemie te diagnosticeren.", "Controle", "In onderzoek", 8, 151),
(6, "HbA1c (Langetermijnbloedsuiker)", "Evalueert de gemiddelde bloedsuikerspiegel over de afgelopen twee tot drie maanden.", "Controle", "In onderzoek", 6, 151),
(7, "Elektrocardiogram (ECG)", "Meet de elektrische activiteit van het hart om hartritmestoornissen en andere hartproblemen te detecteren.", "Diagnostisch onderzoek", "Afgerond", 2, 48),
(8, "C-reactief proteïne (CRP)", "Meet ontstekingsniveaus in het lichaam en kan wijzen op infecties of chronische ontstekingsziekten.", "Controle", "Afgerond", 6, 127),
(9, "Sedimentatiesnelheid (BSE)", "Meet hoe snel rode bloedcellen bezinken in een buis, wat een indicatie kan zijn van ontsteking.", "Controle", "Afgerond", 8, 150),
(10, "Urineanalyse", "Beoordeelt de samenstelling van urine om nierziekten, infecties of andere aandoeningen te detecteren.", "Controle", "Afgerond", 1, 68),
(11, "24-uurs urine-eiwit", "Meet de hoeveelheid eiwit die in urine wordt uitgescheiden over een periode van 24 uur, belangrijk voor nierfunctie.", "Diagnostisch onderzoek", "In onderzoek", 51, 134),
(12, "Urine-cultuur", "Detecteert en identificeert bacteriën in de urine om urineweginfecties te diagnosticeren.", "Controle", "In onderzoek", 47, 91),
(13, "Microscopische urinesecretie", "Onderzoekt urine onder de microscoop op de aanwezigheid van cellen, kristallen en andere elementen.", "Diagnostisch onderzoek", "Afgerond", 27, 127),
(14, "Urine-pH meting", "Bepaalt de zuurgraad van urine, wat kan helpen bij de diagnose van nierstenen en andere aandoeningen.", "Controle", "Afgerond", 22, 125),
(15, "Röntgenfoto", "Maakt afbeeldingen van interne structuren van het lichaam, zoals botten en longen, met behulp van röntgenstralen.", "Controle", "In onderzoek", 12, 79),
(16, "Echografie (ultrasound)", "Gebruikt geluidsgolven om beelden van organen en structuren in het lichaam te maken.", "Controle", "Afgerond", 6, 150),
(17, "Magnetic Resonance Imaging (MRI)", "Maakt gedetailleerde beelden van weefsels en organen met behulp van magnetische velden en radiogolven.", "Diagnostisch onderzoek", "Afgerond", 39, 79),
(18, "Computed Tomography (CT-scan)", "Combineert röntgenbeelden vanuit verschillende hoeken om dwarsdoorsneden van het lichaam te creëren.", "Diagnostisch onderzoek", "Afgerond", 40, 91),
(19, "Positron Emissie Tomografie (PET-scan)", "Beeldvormingstechniek die de stofwisseling van cellen in het lichaam meet, vaak gebruikt bij kankerdiagnose.", "Controle", "In onderzoek", 24, 150),
(20, "Mammografie", "Röntgenonderzoek van de borsten om borstkanker vroegtijdig te detecteren.", "Diagnostisch onderzoek", "In onderzoek", 29, 32),
(21, "Dichtheidsmeting botten (DEXA-scan)", "Meet de botdichtheid om osteoporose en het risico op botbreuken te beoordelen.", "Diagnostisch onderzoek", "In onderzoek", 12, 68),
(22, "Nucleaire geneeskunde scans (zoals schildklier scan)", "Gebruik radioactieve stoffen om de functie en structuur van organen te onderzoeken.", "Diagnostisch onderzoek", "In onderzoek", 11, 25),
(23, "Fluoroscopie", "Real-time bewegende röntgenbeelden gebruikt om functies van interne organen te bestuderen.", "Diagnostisch onderzoek", "In onderzoek", 13, 48),
(24, "Angiografie", "Beeldvorming van bloedvaten met contrastmiddelen om bloedvatafwijkingen te detecteren.", "Diagnostisch onderzoek", "In onderzoek", 36, 109),
(25, "Holter-monitoring", "Continue ECG-monitoring gedurende 24-48 uur om hartritmestoornissen te detecteren.", "Diagnostisch onderzoek", "In onderzoek", 3, 125),
(26, "Stress-test (inspanningstest)", "Beoordeelt de hartfunctie tijdens fysieke inspanning om cardiovasculaire gezondheid te beoordelen.", "Diagnostisch onderzoek", "In onderzoek", 26, 127),
(27, "Echocardiogram", "Ultrasoundonderzoek van het hart om de structuur en functie van het hart te evalueren.", "Controle", "In onderzoek", 50, 48),
(28, "Bloeddrukmeting", "Meet de druk van het bloed tegen de wanden van de bloedvaten, essentieel voor het diagnosticeren van hypertensie.", "Diagnostisch onderzoek", "In onderzoek", 0, 109),
(29, "Ankle-Brachial Index (ABI)", "Vergelijkt de bloeddruk in enkels met die in armen om perifere arteriële aandoeningen te detecteren.", "Controle", "Afgerond", 7, 91),
(30, "Cardiale MRI", "Gedetailleerde beeldvorming van het hart en de grote bloedvaten met behulp van MRI-technologie.", "Controle", "In onderzoek", 12, 25),
(31, "Cardiale CT-scan", "Beeldvorming van het hart en de bloedvaten met een CT-scan voor het detecteren van aderverkalking en andere hartproblemen.", "Controle", "Afgerond", 51, 100),
(32, "Elektrofysiologisch onderzoek", "Onderzoekt de elektrische activiteiten van het hart om hartritmestoornissen te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 15, 91),
(33, "Spiroergometrie", "Beoordeelt de longfunctie en het zuurstofgebruik tijdens inspanning.", "Controle", "Afgerond", 49, 113),
(34, "Spirometrie", "Meet de longfunctie door de hoeveelheid en snelheid van uitgeademde lucht te bepalen.", "Controle", "In onderzoek", 21, 109),
(35, "Longvolume-metingen", "Bepaalt de verschillende longvolumes en capaciteit om longziekten te diagnosticeren.", "Diagnostisch onderzoek", "Afgerond", 19, 109),
(36, "Peak flow meting", "Meet de maximale snelheid van uitgeademde lucht, vaak gebruikt bij astma management.", "Controle", "In onderzoek", 12, 150),
(37, "Bronchoscopy", "Visueel onderzoek van de luchtwegen met een bronchoscoop om afwijkingen te identificeren.", "Diagnostisch onderzoek", "Afgerond", 15, 91),
(38, "Pulmonaire functionele tests", "Evalueert de ademhalingsfunctie en efficiëntie van de longen.", "Diagnostisch onderzoek", "In onderzoek", 34, 125),
(39, "Allergietests", "Identificeert allergenen die allergische reacties veroorzaken.", "Diagnostisch onderzoek", "Afgerond", 29, 113),
(40, "Hepatitis panel", "Test op verschillende hepatitisvirussen om leverinfecties te diagnosticeren.", "Controle", "In onderzoek", 36, 140),
(41, "HIV-test", "Detecteert de aanwezigheid van het HIV-virus in het lichaam.", "Controle", "In onderzoek", 9, 40),
(42, "Thyroïd functieonderzoek", "Meet hormonen zoals TSH, T3 en T4 om schildklierproblemen te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 51, 127),
(43, "Vitamin D-test", "Bepaalt het niveau van vitamine D in het bloed, belangrijk voor botgezondheid en immuunfunctie.", "Controle", "Afgerond", 19, 107),
(44, "Prostaat-specifiek antigeen (PSA) test", "Meet het PSA-niveau om prostaatkanker en andere prostaatproblemen te screenen.", "Diagnostisch onderzoek", "In onderzoek", 8, 32),
(45, "Pap-test", "Beoordeelt celveranderingen in de baarmoederhals om baarmoederhalskanker te detecteren.", "Diagnostisch onderzoek", "Afgerond", 44, 40),
(46, "Coloscopie", "Visueel onderzoek van de dikke darm en endeldarm met een coloscope om afwijkingen te identificeren.", "Diagnostisch onderzoek", "Afgerond", 9, 133),
(47, "Gastroscopie", "Onderzoek van de maag en de eerste delen van de dunne darm met een gastroscoop.", "Controle", "Afgerond", 39, 11),
(48, "Biopsie", "Verzamelen van weefselmonsters voor microscopisch onderzoek om ziekten zoals kanker te diagnosticeren.", "Diagnostisch onderzoek", "Afgerond", 29, 58),
(49, "Cytologie", "Analyseert cellen om afwijkingen of kankercellen te identificeren.", "Diagnostisch onderzoek", "Afgerond", 28, 79),
(50, "Genetische testen", "Onderzoekt DNA om genetische afwijkingen en erfelijke ziekten te detecteren.", "Controle", "In onderzoek", 33, 140),
(51, "Urine-cytologie", "Analyseert urine op abnormale cellen, vaak gebruikt bij de detectie van blaaskanker.", "Diagnostisch onderzoek", "Afgerond", 21, 134),
(52, "Slaaponderzoek (Polysomnografie)", "Evalueert slaapkwaliteit en diagnoseert slaapstoornissen zoals slaapapneu.", "Diagnostisch onderzoek", "Afgerond", 1, 109),
(53, "Neuropsychologisch onderzoek", "Beoordeelt cognitieve functies zoals geheugen, aandacht en probleemoplossend vermogen.", "Diagnostisch onderzoek", "Afgerond", 31, 100),
(54, "EEG (Elektro-encefalogram)", "Meet de elektrische activiteit van de hersenen om epilepsie en andere neurologische aandoeningen te diagnosticeren.", "Diagnostisch onderzoek", "Afgerond", 14, 154),
(55, "EMG (Elektromyografie)", "Evalueert de elektrische activiteit van spieren om neuromusculaire aandoeningen te diagnosticeren.", "Controle", "Afgerond", 12, 79),
(56, "Lumbar puncture (ruggenprik)", "Verzamelt cerebrospinale vloeistof voor onderzoek naar infecties, ontstekingen en andere neurologische aandoeningen.", "Controle", "Afgerond", 48, 91),
(57, "MRI van de hersenen", "Gedetailleerde beeldvorming van de hersenen om afwijkingen zoals tumoren, beroertes of multiple sclerose te detecteren.", "Controle", "In onderzoek", 5, 58),
(58, "CT-scan van de hersenen", "Beeldvorming van de hersenen met een CT-scan voor het opsporen van bloedingen, tumoren en andere hersenaandoeningen.", "Diagnostisch onderzoek", "In onderzoek", 12, 79),
(59, "PET-scan van de hersenen", "Beeldvorming die de stofwisseling van hersencellen meet, vaak gebruikt bij de diagnose van kanker en neurologische aandoeningen.", "Controle", "In onderzoek", 48, 150),
(60, "Arteriografie", "Beeldvorming van slagaders met contrastmiddel om vaatziekten te diagnosticeren.", "Diagnostisch onderzoek", "Afgerond", 47, 11),
(61, "Venografie", "Beeldvorming van aders met contrastmiddel om veneuze aandoeningen te identificeren.", "Diagnostisch onderzoek", "In onderzoek", 2, 107),
(62, "Spirometrie met diffusiecapaciteit", "Meet de longfunctie en de capaciteit van de longen om gasuitwisseling te faciliteren.", "Controle", "In onderzoek", 7, 154),
(63, "Krachtmetingen spierkracht", "Evalueert de spierkracht om spierziekten en zenuwstoornissen te diagnosticeren.", "Controle", "In onderzoek", 14, 127),
(64, "Bewegingstesten (bijv. gait analysis)", "Analyseert het looppatroon om bewegingsstoornissen en musculoskeletale problemen te identificeren.", "Diagnostisch onderzoek", "In onderzoek", 8, 79),
(65, "Hormonale panelen", "Meet verschillende hormonen om endocriene stoornissen te diagnosticeren.", "Diagnostisch onderzoek", "Afgerond", 19, 91),
(66, "Antilichamen testen", "Detecteert antilichamen in het bloed om auto-immuunziekten en infecties te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 37, 125),
(67, "Tumormarkers", "Meet specifieke stoffen in het bloed die kunnen wijzen op kanker.", "Diagnostisch onderzoek", "Afgerond", 30, 113),
(68, "Lactaat dehydrogenase (LDH) test", "Meet het LDH-niveau, wat kan wijzen op weefselschade of bepaalde vormen van kanker.", "Diagnostisch onderzoek", "Afgerond", 40, 109),
(69, "Amylase en lipase testen", "Evalueert enzymen die lever- en alvleesklieraandoeningen kunnen signaleren.", "Controle", "Afgerond", 39, 134),
(70, "Procalcitonine test", "Meet het niveau van procalcitonine als marker voor bacteriële infecties en sepsis.", "Controle", "Afgerond", 36, 133),
(71, "Immunoglobuline testen", "Meet de niveaus van verschillende immunoglobulinen om immuunstoornissen te diagnosticeren.", "Diagnostisch onderzoek", "Afgerond", 3, 32),
(72, "Ferritine test", "Meet het ferritinegehalte om ijzertekorten of -overlading te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 24, 25),
(73, "B12 en foliumzuur testen", "Evalueert niveaus van vitamine B12 en foliumzuur, belangrijk voor bloedvorming en zenuwfunctie.", "Diagnostisch onderzoek", "In onderzoek", 12, 11),
(74, "Serologische testen", "Detecteert antilichamen of antigenen in het bloed voor de diagnose van infectieziekten.", "Controle", "Afgerond", 17, 151),
(75, "PCR (Polymerase Chain Reaction)", "Versterkt DNA-segmenten voor het detecteren van genetische afwijkingen en infecties.", "Diagnostisch onderzoek", "Afgerond", 10, 68),
(76, "Western blot", "Detecteert specifieke eiwitten in een monster, vaak gebruikt voor HIV-diagnostiek.", "Diagnostisch onderzoek", "Afgerond", 36, 107),
(77, "ELISA (Enzyme-Linked Immunosorbent Assay)", "Detecteert en kwantificeert antilichamen of antigenen in biologische monsters.", "Controle", "In onderzoek", 33, 63),
(78, "Flowcytometrie", "Analyseert fysieke en chemische eigenschappen van cellen of deeltjes in een vloeistof.", "Controle", "In onderzoek", 6, 113),
(79, "Microbiologische kweek", "Groeit micro-organismen uit klinische monsters voor identificatie en gevoeligheidstesten.", "Controle", "Afgerond", 36, 58),
(80, "Klinische beeldvorming met contrastmiddelen", "Gebruikt contrastmiddelen om de zichtbaarheid van structuren tijdens beeldvorming te verbeteren.", "Controle", "In onderzoek", 37, 91),
(81, "Intracraniale drukmeting", "Meet de druk binnen de schedel om aandoeningen zoals hydrocephalus of hersenletsel te diagnosticeren.", "Controle", "Afgerond", 9, 150),
(82, "Arteriële bloedgasanalyse", "Evalueert zuurstof- en kooldioxidegehaltes in het bloed om de longfunctie en metabolische status te beoordelen.", "Diagnostisch onderzoek", "In onderzoek", 24, 11),
(83, "Capnografie", "Meet de concentratie kooldioxide in de uitgeademde lucht, vaak gebruikt tijdens anesthesie.", "Controle", "In onderzoek", 20, 150),
(84, "Glomerulaire filtratiesnelheid (GFR)", "Bepaalt de nierfiltratiefunctie om nierziekten te diagnosticeren.", "Diagnostisch onderzoek", "In onderzoek", 11, 107),
(85, "Bilirubinetest", "Meet het bilirubinegehalte om lever- en galwegproblemen te identificeren.", "Controle", "In onderzoek", 41, 32),
(86, "Albumine-test", "Meet het albuminegehalte in het bloed om lever- en nierfuncties te beoordelen.", "Diagnostisch onderzoek", "Afgerond", 23, 109),
(87, "Transaminasen (AST, ALT) testen", "Evalueert leverenzymen om leverbeschadiging te detecteren.", "Controle", "In onderzoek", 28, 140),
(88, "Gamma-glutamyltransferase (GGT) test", "Meet GGT-niveaus om leverziekten en galwegobstructies te diagnosticeren.", "Controle", "Afgerond", 19, 11),
(89, "Alkalische fosfatase (ALP) test", "Evalueert ALP-niveaus voor de diagnose van lever-, galweg- en botziekten.", "Controle", "Afgerond", 29, 109),
(90, "Lactaattest", "Meet lactaatniveaus om weefsellacetaatproductie en zuurstoftekort te beoordelen.", "Diagnostisch onderzoek", "Afgerond", 15, 32),
(91, "Troponine test", "Detecteert hartspierbeschadiging, vaak gebruikt bij de diagnose van hartinfarct.", "Diagnostisch onderzoek", "Afgerond", 36, 125),
(92, "BNP (B-type natriuretisch peptide) test", "Meet BNP-niveaus om hartfalen te diagnosticeren.", "Controle", "Afgerond", 38, 40),
(93, "D-dimeer test", "Detecteert fibrine-afbraakproducten om de aanwezigheid van bloedstolsels te beoordelen.", "Controle", "In onderzoek", 32, 58),
(94, "Serum proteïne electrophorese", "Scheidt eiwitten in het bloed om afwijkingen zoals multiple myeloom te diagnosticeren.", "Controle", "In onderzoek", 25, 32),
(95, "Electrolyten herzien", "Beoordeelt de balans van elektrolyten voor de diagnose van verschillende aandoeningen.", "Diagnostisch onderzoek", "In onderzoek", 43, 150),
(96, "Celiac disease panel", "Detecteert antilichamen geassocieerd met coeliakie om de diagnose te bevestigen.", "Controle", "Afgerond", 51, 154),
(97, "HIV-viral load test", "Meet de hoeveelheid HIV-virus in het bloed om de progressie van de infectie te volgen.", "Controle", "Afgerond", 36, 125),
(98, "Hepatitis C RNA test", "Detecteert het RNA van hepatitis C virus voor bevestiging van een actieve infectie.", "Diagnostisch onderzoek", "Afgerond", 36, 11),
(99, "Antistreptolysine O (ASO) test", "Meet ASO-antilichamen om recente streptokokkeninfecties te identificeren.", "Controle", "In onderzoek", 29, 68),
(100, "Rheumatoid factor (RF) test", "Detecteert RF-antilichamen die geassocieerd zijn met reumatoïde artritis.", "Controle", "In onderzoek", 11, 48),
(101, "Anti-CCP test", "Detecteert anti-cyclic citrullinated peptide-antilichamen voor de diagnose van reumatoïde artritis.", "Diagnostisch onderzoek", "In onderzoek", 4, 113),
(102, "SLE panel (Systemische Lupus Erythematosus)", "Bevat tests zoals ANA om lupus en andere auto-immuunziekten te diagnosticeren.", "Controle", "Afgerond", 12, 127),
(103, "Complement niveaus (C3, C4)", "Meet complement-eiwit niveaus om immuunreacties en ontstekingen te evalueren.", "Controle", "In onderzoek", 15, 107),
(104, "HBA1c varianten", "Evalueert specifieke varianten van HbA1c voor nauwkeurige diabetesmonitoring.", "Controle", "Afgerond", 10, 127),
(105, "Auto-antistoffen testen", "Detecteert auto-antistoffen die betrokken zijn bij auto-immuunziekten.", "Controle", "In onderzoek", 9, 134),
(106, "Metabolisch panel", "Beoordeelt verschillende metabolieten en elektrolyten om de algemene gezondheid te beoordelen.", "Controle", "In onderzoek", 32, 58),
(107, "T3 en T4 testen", "Meet schildklierhormonen om hyperthyreoïdie of hypothyreoïdie te diagnosticeren.", "Controle", "In onderzoek", 23, 150),
(108, "TSH (Thyroid Stimulating Hormone) test", "Evalueert de schildklierfunctie door het meten van TSH-niveaus.", "Diagnostisch onderzoek", "Afgerond", 14, 68),
(109, "Serum calcium test", "Meet calciumspiegels in het bloed voor de diagnose van bot- en nierziekten.", "Controle", "Afgerond", 18, 150),
(110, "Serum magnesium test", "Evalueert magnesiumniveaus om elektrolytenbalans en spierfunctie te beoordelen.", "Controle", "Afgerond", 35, 134),
(111, "Serum fosfaat test", "Meet fosfaatspiegels in het bloed, belangrijk voor botgezondheid en energieproductie.", "Diagnostisch onderzoek", "In onderzoek", 40, 79),
(112, "Albumine-creatinine ratio", "Evalueert nierfunctie door de verhouding tussen albumine en creatinine in urine te meten.", "Diagnostisch onderzoek", "Afgerond", 1, 109),
(113, "Serum osmolaliteit", "Meet de concentratie van opgeloste deeltjes in het bloed voor de beoordeling van vochtbalans.", "Controle", "Afgerond", 37, 68),
(114, "Serum anion gap", "Berekening die helpt bij de diagnose van acidose en andere elektrolytstoornissen.", "Diagnostisch onderzoek", "Afgerond", 8, 150),
(115, "Serum lactate", "Meet lactaatniveaus om zuurstoftekort en weefselschade te detecteren.", "Diagnostisch onderzoek", "Afgerond", 19, 140),
(116, "Urine osmolaliteit", "Evalueert de concentratie van urine om nierfunctie en hydratatiestatus te beoordelen.", "Controle", "In onderzoek", 3, 79),
(117, "Arteriële bloedgassen", "Analyseert zuurstof- en kooldioxidegehaltes in het bloed voor ademhalings- en metabolische stoornissen.", "Diagnostisch onderzoek", "In onderzoek", 31, 25),
(118, "Serum amyloïde A (SAA)", "Meet SAA-niveaus als marker voor acute ontsteking.", "Controle", "Afgerond", 24, 109),
(119, "Plasmacells onderzoek", "Evalueert plasmacellen in het bloed of beenmerg voor aandoeningen zoals multiple myeloom.", "Controle", "In onderzoek", 18, 113),
(120, "Cytomegalovirus (CMV) test", "Detecteert CMV-infecties, vooral belangrijk bij immuungecompromitteerde patiënten.", "Diagnostisch onderzoek", "Afgerond", 0, 150),
(121, "Epstein-Barr Virus (EBV) test", "Detecteert EBV-infecties die geassocieerd zijn met ziekten zoals mononucleosis.", "Controle", "Afgerond", 14, 107),
(122, "Herpes simplex virus (HSV) test", "Detecteert HSV-infecties die huid- en slijmvliesinfecties veroorzaken.", "Diagnostisch onderzoek", "Afgerond", 36, 79),
(123, "Varicella-Zoster Virus (VZV) test", "Detecteert VZV-infecties, waaronder waterpokken en gordelroos.", "Controle", "In onderzoek", 18, 63),
(124, "Hepatitis B surface antigen (HBsAg) test", "Detecteert het oppervlakte-antigeen van hepatitis B virus voor actieve infectie.", "Controle", "Afgerond", 7, 154),
(125, "HIV-antilichaam en antigeen test", "Detecteert zowel antilichamen als antigenen voor vroege diagnose van HIV.", "Diagnostisch onderzoek", "Afgerond", 37, 134),
(126, "Syfilis test (RPR, VDRL)", "Detecteert syfilis-infectie door middel van serologische testen.", "Diagnostisch onderzoek", "In onderzoek", 24, 113),
(127, "Tuberculose (TB) test (Mantoux)", "Beoordeelt blootstelling aan tuberculose door huidtesten.", "Controle", "In onderzoek", 10, 68),
(128, "Interferon-gamma release assays (IGRAs)", "Detecteert tuberculose-infectie door het meten van immuunreacties op TB-antigenen.", "Diagnostisch onderzoek", "Afgerond", 30, 58),
(129, "Lactose intolerantie test", "Evalueert de capaciteit van het lichaam om lactose te verteren.", "Controle", "Afgerond", 24, 140),
(130, "Coeliakie genetische testen", "Identificeert genetische markers geassocieerd met coeliakie.", "Controle", "Afgerond", 19, 133),
(131, "Fructose intolerantie test", "Evalueert de capaciteit van het lichaam om fructose te verteren.", "Diagnostisch onderzoek", "In onderzoek", 16, 40),
(132, "Zinkmeting", "Meet zinkniveaus in het bloed voor de diagnose van zinktekorten of -overdoses.", "Controle", "Afgerond", 19, 91),
(133, "Selenium test", "Evalueert seleniumniveaus voor de diagnose van tekorten of toxiciteit.", "Diagnostisch onderzoek", "Afgerond", 45, 151),
(134, "Cholesterol subtypes", "Beoordeelt verschillende typen cholesterol, zoals HDL, LDL en VLDL.", "Controle", "In onderzoek", 21, 134),
(135, "Triglyceriden test", "Meet de niveaus van triglyceriden in het bloed, belangrijk voor hartgezondheid.", "Controle", "Afgerond", 25, 32),
(136, "Apoproteïne testen", "Evalueert apoproteïnen zoals ApoA en ApoB voor hartziekte risico's.", "Diagnostisch onderzoek", "Afgerond", 13, 109),
(137, "Homocysteïne test", "Meet homocysteïneniveaus als risicofactor voor hartziekten en beroertes.", "Controle", "In onderzoek", 47, 58),
(138, "Genetisch screenen op BRCA1/BRCA2", "Detecteert genetische mutaties die het risico op borstkanker en eierstokkanker verhogen.", "Diagnostisch onderzoek", "Afgerond", 28, 100),
(139, "HLA typing", "Identificeert menselijke leukocytenantigenen voor transplantatie- en auto-immuunziekte diagnoses.", "Diagnostisch onderzoek", "Afgerond", 24, 151),
(140, "Natriuretische peptiden", "Meet niveaus van natriuretische peptiden voor de evaluatie van hartfalen.", "Controle", "In onderzoek", 37, 58),
(141, "Beta-2 microglobuline test", "Evalueert het niveau van beta-2 microglobuline voor de diagnose van nierziekten en bepaalde kankers.", "Controle", "Afgerond", 8, 79),
(142, "Serum ferritine", "Meet ferritine voor de evaluatie van ijzeropslag in het lichaam.", "Diagnostisch onderzoek", "Afgerond", 4, 150),
(143, "Karnosine test", "Evalueert karnosine niveaus, een antioxidant in het lichaam.", "Controle", "Afgerond", 1, 79),
(144, "Zink-ionen test", "Meet vrije zinkionen in het bloed, belangrijk voor immuunfunctie en enzymatische processen.", "Diagnostisch onderzoek", "In onderzoek", 49, 79),
(145, "Sideroferet test", "Beoordeelt ijzerbindend vermogen van het bloed voor diagnose van anemie.", "Diagnostisch onderzoek", "Afgerond", 37, 68),
(146, "Methylmalonzuur test", "Meet methylmalonzuurniveaus voor de diagnose van vitamine B12 tekort.", "Diagnostisch onderzoek", "Afgerond", 50, 68),
(147, "Homocysteïne en folaat panel", "Evalueert homocysteïne en folaat niveaus voor hart- en vaatziekten risicobeoordeling.", "Diagnostisch onderzoek", "Afgerond", 28, 40),
(148, "Urine-cortisol test", "Meet cortisol niveaus in urine om bijnierfuncties te evalueren.", "Controle", "Afgerond", 30, 133),
(149, "ACTH test", "Meet adrenocorticotroop hormoon niveaus voor de diagnose van bijnieraandoeningen.", "Diagnostisch onderzoek", "In onderzoek", 2, 40),
(150, "Insulinetest", "Evalueert insulineniveaus om diabetes en insulineresistentie te diagnosticeren.", "Diagnostisch onderzoek", "Afgerond", 17, 133),
(151, "C-peptide test", "Meet C-peptide niveaus als indicator van endogene insulineproductie.", "Controle", "In onderzoek", 31, 91),
(152, "Glucagon test", "Evalueert de respons van de alvleesklier op glucagon voor diabetes diagnose.", "Controle", "Afgerond", 42, 91),
(153, "Serum ketonen", "Meet ketonen in het bloed voor de diagnose van ketoacidose en metabolische stoornissen.", "Diagnostisch onderzoek", "In onderzoek", 10, 32),
(154, "Prolactine test", "Meet prolactineniveaus om hormonale stoornissen en pituitary aandoeningen te diagnosticeren.", "Diagnostisch onderzoek", "Afgerond", 31, 48),
(155, "Luteïniserend hormoon (LH) test", "Evalueert LH niveaus voor reproductieve gezondheidsdiagnoses.", "Diagnostisch onderzoek", "In onderzoek", 29, 68),
(156, "Follikelstimulerend hormoon (FSH) test", "Meet FSH niveaus voor de evaluatie van voortplantingsstoornissen.", "Diagnostisch onderzoek", "Afgerond", 13, 109),
(157, "Estradiol test", "Meet estradiol niveaus voor de evaluatie van vrouwelijke reproductieve gezondheid.", "Controle", "In onderzoek", 41, 133),
(158, "Testosteron test", "Evalueert testosteronniveaus voor de diagnose van hormonale stoornissen.", "Controle", "Afgerond", 23, 107),
(159, "Progesteron test", "Meet progesteronniveaus voor de evaluatie van de menstruatiecyclus en vruchtbaarheid.", "Diagnostisch onderzoek", "In onderzoek", 24, 63),
(160, "DHEA-S test", "Evalueert de niveaus van dehydroepiandrosteron-sulfaat voor de diagnose van bijnierstoornissen.", "Controle", "Afgerond", 43, 40),
(161, "Androstenedione test", "Meet androstenedioneniveaus voor de evaluatie van androgenen productie.", "Controle", "In onderzoek", 16, 25),
(162, "Renine en aldosteron testen", "Evalueert renine en aldosteronniveaus voor de diagnose van hypertensie en bijnieraandoeningen.", "Diagnostisch onderzoek", "In onderzoek", 27, 100),
(163, "Metaanalyse van laboratoriumresultaten", "Integreert verschillende laboratoriumtestresultaten voor een holistische diagnostische evaluatie.", "Diagnostisch onderzoek", "Afgerond", 5, 63),
(164, "Serum albumine test", "Meet albumine niveaus in het bloed voor de evaluatie van lever- en nierfuncties.", "Diagnostisch onderzoek", "In onderzoek", 27, 151),
(165, "Serum globuline test", "Evalueert globuline niveaus voor de diagnose van immuun- en leverziekten.", "Controle", "Afgerond", 11, 32),
(166, "Apolipoproteïne E (ApoE) test", "Beoordeelt ApoE genotypen voor risico op Alzheimer en cardiovasculaire ziekten.", "Diagnostisch onderzoek", "In onderzoek", 15, 11),
(167, "Serum uric acid test", "Meet uric acid niveaus voor de diagnose van jicht en nierstenen.", "Controle", "Afgerond", 32, 107),
(168, "Celiac serologie", "Bevat testen zoals tTG-IgA voor de diagnose van coeliakie.", "Diagnostisch onderzoek", "Afgerond", 5, 40),
(169, "HLA-B27 test", "Detecteert het HLA-B27 antigen, geassocieerd met spondyloartritis en andere auto-immuunziekten.", "Diagnostisch onderzoek", "In onderzoek", 14, 11),
(170, "Rheuma panel", "Bevat verschillende tests voor de diagnose van reumatische aandoeningen.", "Diagnostisch onderzoek", "Afgerond", 42, 107),
(171, "Serum viscosity", "Meet de stroperigheid van het bloed voor de diagnose van multiple myeloom en andere aandoeningen.", "Controle", "Afgerond", 24, 154),
(172, "Serum protein electrophoresis (SPEP)", "Scheidt en kwantificeert eiwitten in het bloed voor de diagnose van immunoglobulineziekten.", "Diagnostisch onderzoek", "In onderzoek", 39, 133),
(173, "Immunofixatie electrophoresis (IFE)", "Identificeert specifieke immunoglobulines voor de diagnose van multiple myeloom en andere aandoeningen.", "Controle", "In onderzoek", 46, 25),
(174, "Serum amyloid A (SAA) test", "Meet SAA niveaus als een acute fase reactant voor ontstekingsdiagnostiek.", "Diagnostisch onderzoek", "In onderzoek", 35, 140),
(175, "Ferritine en transferrine saturatie", "Evalueert ijzeropslag en transport in het lichaam voor de diagnose van anemie.", "Diagnostisch onderzoek", "Afgerond", 48, 11),
(176, "Haptoglobine test", "Meet haptoglobine niveaus voor de diagnose van hemolytische anemie.", "Diagnostisch onderzoek", "Afgerond", 18, 63),
(177, "Serum ceruloplasmine test", "Meet ceruloplasmine niveaus voor de diagnose van de ziekte van Wilson.", "Diagnostisch onderzoek", "Afgerond", 23, 68),
(178, "Alpha-1 antitrypsine test", "Evalueert niveaus van alpha-1 antitrypsine voor de diagnose van lever- en longziekten.", "Diagnostisch onderzoek", "In onderzoek", 4, 63),
(179, "Parathyroïde hormoon (PTH) test", "Meet PTH niveaus voor de diagnose van parathyroïd functionele stoornissen.", "Controle", "Afgerond", 48, 68),
(180, "Osteocalcine test", "Evalueert osteocalcine niveaus voor de diagnose van botmetabolisme en osteoporose.", "Diagnostisch onderzoek", "Afgerond", 21, 58),
(181, "Serum alkaline phosphatase isoenzymen", "Scheidt ALP isoenzymen voor de diagnose van lever- en botziekten.", "Diagnostisch onderzoek", "In onderzoek", 24, 48),
(182, "Sideroblasten telling", "Beoordeelt de aanwezigheid van sideroblasten in het beenmerg voor de diagnose van sideroblastaire anemie.", "Diagnostisch onderzoek", "In onderzoek", 14, 100),
(183, "Serum proteinase 3 (PR3) en myeloperoxidase (MPO) antilichamen", "Detecteert ANCA (anti-neutrophil cytoplasmic antibodies) voor de diagnose van vasculitis.", "Diagnostisch onderzoek", "Afgerond", 25, 134),
(184, "Neutrofiele functie testen", "Evalueert de functie van neutrofielen voor de diagnose van immuungecompromitteerde aandoeningen.", "Diagnostisch onderzoek", "Afgerond", 39, 150),
(185, "Serum tryptase test", "Meet tryptase niveaus voor de diagnose van systemische anafylaxie en myeloïde proliferatieve aandoeningen.", "Controle", "In onderzoek", 34, 125),
(186, "Kappa en lambda light chains", "Evalueert lichtketen niveaus voor de diagnose van multiple myeloom en andere plasmacelziekten.", "Diagnostisch onderzoek", "Afgerond", 44, 58),
(187, "Serum β2-microglobuline test", "Meet β2-microglobuline niveaus voor de diagnose van nierziekten en bepaalde kankers.", "Diagnostisch onderzoek", "In onderzoek", 46, 48),
(188, "Serum uridine test", "Evalueert uridine niveaus voor de diagnose van metabole stoornissen.", "Controle", "In onderzoek", 16, 40),
(189, "Thyroglobuline test", "Meet thyroglobuline niveaus voor de monitoring van schildklierkanker.", "Diagnostisch onderzoek", "In onderzoek", 4, 79),
(190, "Ammoniak test", "Meet ammoniak niveaus in het bloed voor de diagnose van leverfalen en metabole stoornissen.", "Diagnostisch onderzoek", "In onderzoek", 32, 32),
(191, "Serum ammonia", "Evalueert ammonia niveaus voor de diagnose van leverfunctiestoornissen en ureumcyclusdefecten.", "Controle", "In onderzoek", 18, 133),
(192, "Vitaminen panel", "Beoordeelt verschillende vitaminen niveaus voor de diagnose van tekorten en toxiciteit.", "Controle", "In onderzoek", 37, 48),
(193, "Mineralen panel", "Meet niveaus van essentiële mineralen zoals calcium, magnesium en kalium.", "Diagnostisch onderzoek", "Afgerond", 25, 63),
(194, "Serum albumine/globuline ratio", "Evalueert de verhouding tussen albumine en globuline voor de diagnose van lever- en nierziekten.", "Diagnostisch onderzoek", "In onderzoek", 5, 107),
(195, "Insuline-like growth factor (IGF) test", "Meet IGF niveaus voor de diagnose van groeistoornissen en acromegalie.", "Controle", "Afgerond", 0, 127),
(196, "Serum iron binding capacity (TIBC)", "Evalueert de totale ijzerbindende capaciteit van het bloed voor de diagnose van anemie.", "Controle", "Afgerond", 1, 150),
(197, "Serum folate test", "Meet folaat niveaus voor de diagnose van vitamine B12 tekort en megaloblastische anemie.", "Diagnostisch onderzoek", "Afgerond", 7, 48),
(198, "Serum homocysteïne", "Evalueert homocysteïneniveaus als risicofactor voor cardiovasculaire ziekten.", "Diagnostisch onderzoek", "Afgerond", 0, 79),
(199, "Serum ceruloplasmine", "Meet ceruloplasmine niveaus voor de diagnose van de ziekte van Wilson.", "Controle", "In onderzoek", 19, 134),
(200, "Serum aldolase test", "Evalueert aldolase niveaus voor de diagnose van spierziekten en leverziekten.", "Controle", "Afgerond", 1, 140),
(201, "Serum myoglobin test", "Meet myoglobine niveaus voor de diagnose van spierbeschadiging en myocardinfarct.", "Controle", "In onderzoek", 18, 40),
(202, "Myositis panel", "Bevat verschillende tests voor de diagnose van inflammatoire spierziekten.", "Diagnostisch onderzoek", "In onderzoek", 16, 150),
(203, "Serum lactate dehydrogenase (LDH)", "Meet LDH niveaus als marker voor weefselschade en bepaalde vormen van kanker.", "Controle", "Afgerond", 18, 91),
(204, "Serum creatine kinase (CK)", "Evalueert CK niveaus voor de diagnose van spierbeschadiging en myocardinfarct.", "Diagnostisch onderzoek", "Afgerond", 36, 11),
(205, "Serum sodium test", "Meet natriumspiegels voor de diagnose van elektrolytstoornissen en hydratatiestatus.", "Controle", "In onderzoek", 32, 107),
(206, "Serum potassium test", "Evalueert kaliumspiegels voor de diagnose van elektrolytstoornissen en spierfunctie.", "Diagnostisch onderzoek", "In onderzoek", 26, 91),
(207, "Serum chloride test", "Meet chloride niveaus voor de diagnose van elektrolytstoornissen en acidose.", "Controle", "In onderzoek", 17, 25),
(208, "Serum bicarbonate test", "Evalueert bicarbonaat niveaus voor de diagnose van acidose en alkalose.", "Diagnostisch onderzoek", "Afgerond", 23, 40),
(209, "Serum phosphate test", "Meet fosfaatspiegels voor de diagnose van bot- en nierziekten.", "Controle", "In onderzoek", 42, 134),
(210, "Serum magnesium test", "Evalueert magnesiumspiegels voor de diagnose van elektrolytstoornissen en spierfunctie.", "Controle", "In onderzoek", 43, 40),
(211, "Serum calcium test", "Meet calciumspiegels voor de diagnose van bot- en nierziekten.", "Diagnostisch onderzoek", "Afgerond", 9, 25),
(212, "Serum albumin test", "Evalueert albumine niveaus voor de diagnose van lever- en nierziekten.", "Controle", "In onderzoek", 9, 11),
(213, "Serum total protein", "Meet totale eiwitniveaus voor de diagnose van diverse aandoeningen.", "Controle", "In onderzoek", 50, 113),
(214, "Serum globulins", "Evalueert globuline niveaus voor de diagnose van immuun- en leverziekten.", "Diagnostisch onderzoek", "Afgerond", 5, 32),
(215, "Serum bilirubine test", "Meet bilirubine niveaus voor de diagnose van lever- en galwegproblemen.", "Controle", "In onderzoek", 51, 113),
(216, "Serum alkaline phosphatase (ALP)", "Evalueert ALP niveaus voor de diagnose van lever-, galweg- en botziekten.", "Diagnostisch onderzoek", "Afgerond", 9, 48),
(217, "Serum gamma-glutamyltransferase (GGT)", "Meet GGT niveaus voor de diagnose van leverziekten en galwegobstructies.", "Controle", "Afgerond", 30, 25),
(218, "Serum aspartate aminotransferase (AST)", "Evalueert AST niveaus voor de diagnose van lever- en spierziekten.", "Controle", "In onderzoek", 38, 150),
(219, "Serum alanine aminotransferase (ALT)", "Meet ALT niveaus voor de diagnose van leverbeschadiging.", "Controle", "In onderzoek", 33, 25),
(220, "Serum lactate", "Evalueert lactaat niveaus voor de diagnose van zuurstoftekort en weefselschade.", "Diagnostisch onderzoek", "Afgerond", 7, 150);
