INSERT INTO Specialisatie(specialisatie_code, specialisatie_naam, specialisatie_beschrijving)
VALUES
(0, "Geriatrisch Verpleegkundige", "Gespecialiseerd in de zorg voor oudere patiënten met complexe gezondheidsbehoeften."),
(1, "Dementiezorg Specialist", "Expertise in de zorg en ondersteuning van bewoners met dementie en cognitieve achteruitgang."),
(2, "Revalidatieverpleegkundige", "Richt zich op het herstel en de revalidatie van ouderen na operaties of langdurige ziekte."),
(3, "Palliatieve Zorgverlener", "Biedt comfort en ondersteuning aan bewoners met terminale ziekten."),
(4, "Voedingsdeskundige", "Ontwikkelt voedingsplannen en begeleidt bewoners met specifieke dieetbehoeften."),
(5, "Fysiotherapeut", "Behandelt bewegingsbeperkingen en bevordert de fysieke gezondheid van bewoners."),
(6, "Occupational Therapist", "Helpt bewoners bij het uitvoeren van dagelijkse activiteiten en verbetert hun zelfstandigheid."),
(7, "Logopedist", "Behandelt communicatie- en slikproblemen bij ouderen."),
(8, "Psycholoog", "Behandelt mentale gezondheidstoestanden en biedt psychologische ondersteuning aan bewoners."),
(9, "Sociaal Werker", "Ondersteunt bewoners bij sociale en emotionele kwesties en verbindt hen met externe diensten."),
(10, "Zorgcoördinator", "Coördineert zorgplannen en fungeert als schakel tussen bewoners, families en zorgverleners."),
(11, "Medicatiebeheerder", "Beheert en controleert medicatiebeheer binnen het verzorgingscentrum."),
(12, "Ergotherapeut", "Helpt bewoners bij het verbeteren van hun dagelijkse activiteiten en motorische vaardigheden."),
(13, "Begeleider Activiteiten", "Organiseert en begeleidt recreatieve en therapeutische activiteiten voor bewoners."),
(14, "Geriatrisch Psychiater", "Behandelt psychiatrische aandoeningen bij oudere patiënten."),
(15, "Palliatieve Verpleegkundige", "Gespecialiseerd in het bieden van palliatieve zorg aan bewoners in de laatste levensfase."),
(16, "Zorgmanager", "Beheert de dagelijkse operaties van het verzorgingscentrum en waarborgt hoge zorgstandaarden."),
(17, "Tandartsverpleegkundige", "Ondersteunt tandartsen bij mondzorg voor bewoners en verzorgt mondhygiëne."),
(18, "Recreatiebegeleider", "Faciliteert sociale en recreatieve activiteiten om het welzijn van bewoners te bevorderen."),
(19, "Farmaceutische Zorgverlener", "Beheert medicatie en zorgt voor veilige medicatietoediening aan bewoners."),
(20, "Zorgassistent", "Biedt basiszorg en ondersteuning aan verpleegkundigen en verzorgenden."),
(21, "Hoofd Verpleegafdeling", "Leidt de verpleegafdeling en coördineert het verpleegkundig team."),
(22, "Zorgadministrateur", "Beheert administratieve taken zoals dossiers, planning en correspondentie."),
(23, "Palliatieve Psycholoog", "Biedt psychologische ondersteuning aan bewoners en hun families tijdens palliatieve zorg."),
(24, "Geriatrisch Apotheker", "Beheert medicatie en adviseert over farmacotherapie specifiek voor oudere patiënten."),
(25, "Zorg- en Welzijnscoördinator", "Coördineert welzijns- en zorgprogramma's binnen het verzorgingscentrum."),
(26, "Begeleider Zelfstandigheid", "Helpt bewoners bij het behouden en verbeteren van hun zelfstandigheid en autonomie."),
(27, "Klinisch Psycholoog", "Behandelt klinische psychologische problemen en biedt therapieën aan bewoners."),
(28, "Zorginnovatie Specialist", "Implementeert innovatieve zorgmethoden en technologieën om de kwaliteit van zorg te verbeteren."),
(29, "Ethicus Zorg", "Behandelt ethische vraagstukken en ondersteunt bij besluitvorming in zorgsituaties."),
(30, "Zorgopleider", "Opleidt en begeleidt nieuwe zorgverleners binnen het verzorgingscentrum."),
(31, "Zorgkwaliteit Manager", "Verantwoordelijk voor het monitoren en verbeteren van de zorgkwaliteit binnen het centrum."),
(32, "Begeleider End-of-Life", "Ondersteunt bewoners en hun families tijdens de laatste levensfase."),
(33, "Zorglogistiek Specialist", "Beheert logistieke processen binnen het verzorgingscentrum om efficiënte zorg te garanderen."),
(34, "Multidisciplinair Coördinator", "Coördineert samenwerking tussen verschillende zorgdisciplines voor optimale zorgverlening."),
(35, "Zorg- en Activiteitenadviseur", "Adviseert over zorg- en activiteitenprogramma's om het welzijn van bewoners te bevorderen."),
(36, "Gezondheidsvoorlichter", "Biedt informatie en voorlichting aan bewoners over gezondheidskwesties en preventie."),
(37, "Zorgonderzoeker", "Voert onderzoek uit naar verbeteringen in zorgpraktijken en -processen binnen het centrum."),
(38, "Zorginformatiespecialist", "Beheert zorginformatiesystemen en zorgt voor accurate gegevensregistratie."),
(39, "Begeleider Activiteiten Therapie", "Implementeert therapeutische activiteiten om het cognitieve en fysieke welzijn te bevorderen."),
(40, "Zorgfinancieringsadviseur", "Adviseert over financiering en budgettering binnen het verzorgingscentrum."),
(41, "Zorgveiligheid Coördinator", "Zorgt voor naleving van veiligheidsnormen en protocollen binnen het verzorgingscentrum."),
(42, "Familie Ondersteuner", "Biedt ondersteuning aan de families van bewoners bij het omgaan met zorgvragen en -behoeften."),
(43, "Zorg- en Rehabilitatie Specialist", "Combineert zorgverlening met revalidatieprogramma's om het herstel van bewoners te ondersteunen."),
(44, "Beheerder Faciliteiten", "Beheert de faciliteiten en infrastructuur van het verzorgingscentrum om een veilige omgeving te waarborgen."),
(45, "Zorgcommunicatiespecialist", "Faciliteert effectieve communicatie tussen zorgverleners, bewoners en families."),
(46, "Klinisch Manager", "Overziet klinische operaties en zorgt voor hoogwaardige medische zorg binnen het centrum."),
(47, "Zorgmarketing Specialist", "Ontwikkelt en implementeert marketingstrategieën om de zorgdiensten van het centrum te promoten."),
(48, "Zorgethicus", "Behandelt ethische dilemma's en ondersteunt zorgverleners bij ethisch verantwoorde besluitvorming."),
(49, "Zorgplanner", "Plant en coördineert zorgactiviteiten en diensten om aan de behoeften van bewoners te voldoen."),
(50, "Verpleegkundig Onderzoeker", "Voert verpleegkundig onderzoek uit om de kwaliteit en effectiviteit van zorgpraktijken te verbeteren."),
(51, "Zorgtechnoloog", "Implementeert en beheert technologische oplossingen ter ondersteuning van zorgverlening."),
(52, "Zorgpsycholoog", "Behandelt psychologische aspecten van zorg en ondersteunt bewoners bij emotionele uitdagingen."),
(53, "Zorgafspraken Specialist", "Beheert en optimaliseert zorgafspraken en planningen voor bewoners en zorgverleners."),
(54, "Verpleegkundige Ergotherapeut", "Combineert verpleegkundige zorg met ergotherapeutische interventies voor een holistische benadering."),
(55, "Begeleider Sociale Activiteiten", "Faciliteert sociale interacties en gemeenschapsactiviteiten om het sociale welzijn van bewoners te bevorderen."),
(56, "Zorg Jurist", "Behandelt juridische zaken binnen het verzorgingscentrum, inclusief patiëntrechten en regelgeving.");
