INSERT INTO Team(team_naam, omschrijving, aantal_leden)
VALUES
("Team Zorgzaam", "Biedt basiszorg en ondersteuning aan bewoners, gericht op dagelijks welzijn.", 1),
("Team Welzijn", "Focust op het bevorderen van mentaal en emotioneel welzijn van de bewoners.", 1),
("Team Vitaliteit", "Ondersteunt fysieke gezondheid en bevordert actieve levensstijlen onder bewoners.", 1),
("Team Comfort", "Zorgt voor een comfortabele en huiselijke omgeving voor alle bewoners.", 1),
("Team Herstel", "Levert revalidatie- en herstelzorg aan bewoners na medische ingrepen.", 1),
("Team Harmonie", "Bevordert een harmonieuze sfeer en interpersoonlijke relaties binnen het centrum.", 1),
("Team Steun", "Biedt emotionele en praktische ondersteuning aan bewoners en hun families.", 1),
("Team Veiligheid", "Waarborgt de veiligheid en gezondheid van bewoners door preventieve maatregelen.", 1),
("Team Levenskwaliteit", "Streeft naar het verbeteren van de algehele levenskwaliteit van bewoners.", 1),
("Team Vriendelijkheid", "Focust op het bieden van vriendelijke en empathische zorg aan alle bewoners.", 1),
("Team Betrokkenheid", "Stimuleert actieve betrokkenheid en participatie van bewoners in het dagelijkse leven.", 1),
("Team Groei", "Ondersteunt persoonlijke groei en ontwikkeling van bewoners door educatieve activiteiten.", 1),
("Team Empathie", "Biedt zorg met een hoog niveau van empathie en begrip voor individuele behoeften.", 1),
("Team Inspiratie", "Organiseert inspirerende activiteiten en evenementen die bewoners motiveren.", 1),
("Team Respect", "Bevordert een cultuur van respect en waardigheid binnen het verzorgingscentrum.", 1),
("Team Integratie", "Faciliteert de integratie van nieuwe bewoners en bevordert een inclusieve gemeenschap.", 1),
("Team Compassie", "Biedt compassievolle zorg en ondersteuning aan bewoners in nood.", 1),
("Team Samenwerking", "Stimuleert samenwerking tussen verschillende zorgdisciplines voor optimale zorgverlening.", 1),
("Team Verlichting", "Verlicht de dagelijkse stress en draagt bij aan het comfort van bewoners.", 1),
("Team Toewijding", "Biedt toegewijde en consistente zorg aan alle bewoners.", 1),
("Team Innovatie", "Implementeert innovatieve zorgmethoden en technologieën binnen het centrum.", 1),
("Team Begeleiding", "Begeleidt bewoners bij persoonlijke en sociale uitdagingen.", 1),
("Team Flexibiliteit", "Past zich aan veranderende zorgbehoeften en omstandigheden van bewoners aan.", 1),
("Team Professionalite", "Handhaaft hoge professionele standaarden in alle aspecten van zorgverlening.", 1),
("Team Betrouwbaarheid", "Zorgt voor betrouwbare en consistente zorgdiensten voor alle bewoners.", 1),
("Team Connectie", "Versterkt de verbinding tussen bewoners en het zorgteam voor betere zorgrelaties.", 1),
("Team Helderheid", "Bevordert duidelijke communicatie en transparantie binnen het verzorgingscentrum.", 1),
("Team Kracht", "Leidt grote zorgprojecten en biedt uitgebreide ondersteuning aan bewoners met complexe behoeften.", 1),
("Team Eenvoud", "Zorgt voor eenvoudige en efficiënte zorgprocessen om het welzijn van bewoners te maximaliseren.", 1),
("Team Balans", "Ondersteunt bewoners bij het vinden van een balans tussen zorg en persoonlijke activiteiten.", 1);
