INSERT INTO Vaccin(vaccin_naam, vaccin_code, opmerkingen)
VALUES
("Influenza Vaccin", "FLU2024", "Seizoensgebonden vaccinatie tegen griep."),
("COVID-19 Vaccin (Pfizer-BioNTech)", "COVID19PFIZER", "mRNA-gebaseerd vaccin, vereist twee doses."),
("COVID-19 Vaccin (Moderna)", "COVID19MODERNA", "mRNA-gebaseerd vaccin, vereist twee doses."),
("COVID-19 Vaccin (AstraZeneca)", "COVID19AZ", "Vector-gebaseerd vaccin, vereist twee doses."),
("MMR Vaccin", "MMR2024", "Beschermt tegen mazelen, bof en rubella."),
("DTaP Vaccin", "DTAP2024", "Beschermt tegen difterie, tetanus en pertussis."),
("HPV Vaccin (Gardasil)", "HPVGARDASIL", "Beschermt tegen humaan papillomavirus, voorkómt baarmoederhalskanker."),
("HPV Vaccin (Cervarix)", "HPVCERVARIX", "Beschermt tegen humaan papillomavirus, voorkómt baarmoederhalskanker."),
("Varicella Vaccin", "VAR2024", "Beschermt tegen waterpokken."),
("Hepatitis B Vaccin", "HEPB2024", "Beschermt tegen hepatitis B virusinfectie."),
("Rotavirus Vaccin", "ROTA2024", "Beschermt tegen rotavirusinfectie, voorkómt ernstige diarree bij baby's."),
("Pneumokokken Vaccin (PCV13)", "PCV132024", "Beschermt tegen pneumokokkeninfecties zoals longontsteking."),
("Pneumokokken Vaccin (PPSV23)", "PPSV232024", "Beschermt tegen pneumokokkeninfecties, aanbevolen voor oudere volwassenen."),
("Hepatitis A Vaccin", "HEPA2024", "Beschermt tegen hepatitis A virusinfectie."),
("Meningokokken Vaccin (MenACWY)", "MENACWY2024", "Beschermt tegen meningokokkengroepen A, C, W, en Y."),
("Meningokokken Vaccin (MenB)", "MENB2024", "Beschermt tegen meningokokkengroep B."),
("Japanese Encephalitis Vaccin", "JE2024", "Beschermt tegen Japanse encefalitis, een door muggen overgedragen ziekte."),
("Rabies Vaccin", "RABIES2024", "Beschermt tegen rabiës, meestal voorgeschreven na blootstelling aan dieren."),
("Yellow Fever Vaccin", "YF2024", "Verplicht voor reizen naar bepaalde tropische gebieden."),
("Cholera Vaccin", "CHOL2024", "Beschermt tegen cholera, aanbevolen voor reizen naar risicogebieden."),
("Typhoid Vaccin", "TYPH2024", "Beschermt tegen tyfus, aanbevolen voor reizen naar risicogebieden."),
("Polio Vaccin (IPV)", "POLIOIPV2024", "Inerte poliovaccin, onderdeel van het routinevaccinatieschema."),
("Polio Vaccin (OPV)", "POLIOOPV2024", "Orale poliovaccin, minder vaak gebruikt in ontwikkelde landen."),
("Hib Vaccin", "HIB2024", "Beschermt tegen Haemophilus influenzae type b infecties."),
("BCG Vaccin", "BCG2024", "Beschermt tegen tuberculose, voornamelijk gebruikt in landen met hoge TB-prevalentie."),
("MMRV Vaccin", "MMRV2024", "Een combinatievaccin tegen mazelen, bof, rubella en varicella."),
("DT Vaccin", "DT2024", "Beschermt tegen difterie en tetanus, zonder pertussis."),
("Tdap Vaccin", "TDAP2024", "Beschermt tegen tetanus, difterie en pertussis."),
("MenHibrix Vaccin", "MENHIBRIX2024", "Beschermt tegen meningokokkengroepen C en Y en Haemophilus influenzae type b."),
("Shingles Vaccin (Shingrix)", "SHINGRIX2024", "Beschermt tegen gordelroos (herpes zoster), aanbevolen voor volwassenen boven 50 jaar."),
("Shingles Vaccin (Zostavax)", "ZOSTAVAX2024", "Beschermt tegen gordelroos, een levend verzwakt vaccin."),
("Meningitis B Vaccin (Bexsero)", "MENBEXSERO2024", "Beschermt tegen meningitis B."),
("Meningitis B Vaccin (Trumenba)", "MENBTRUMENBA2024", "Beschermt tegen meningitis B."),
("Japanese Encephalitis Vaccin (Ixiaro)", "JEIXIARO2024", "Een niet-levend vaccin tegen Japanse encefalitis."),
("Japanese Encephalitis Vaccin (SA14-14-2)", "JESA1420142024", "Een levend verzwakt vaccin tegen Japanse encefalitis."),
("Rabies Vaccin (Verorab)", "RABIEVERORAB2024", "Een geïmmuneoglobuline-gebaseerd vaccin tegen rabiës."),
("Rabies Vaccin (Imovax Rabies)", "RABIEIMOVAX2024", "Een geïmmuneoglobuline-gebaseerd vaccin tegen rabiës."),
("Cholera Vaccin (Dukoral)", "CHOLDUKORAL2024", "Een oraal vaccin tegen cholera, aanbevolen voor reizen naar risicogebieden."),
("Cholera Vaccin (Shanchol)", "CHOLSHANCHOL2024", "Een oraal vaccin tegen cholera, aanbevolen voor reizen naar risicogebieden."),
("Typhoid Vaccin (Typhim Vi)", "TYPHIMVI2024", "Een orale vaccinatie tegen tyfus."),
("Typhoid Vaccin (Vivotif)", "VIVOTIF2024", "Een orale vaccinatie tegen tyfus."),
("Hib Vaccin (ActHIB)", "HIBACTHIB2024", "Beschermt tegen Haemophilus influenzae type b infecties."),
("Hib Vaccin (Hiberix)", "HIBHIBERIX2024", "Beschermt tegen Haemophilus influenzae type b infecties."),
