INSERT INTO Ziekte_heeft_Geneeswijze(Geneeswijze_naam, Ziekte_ziekte_id)
VALUES
("Leefstijlinterventie", 0),
("Antivirale therapie", 0),
("Music Therapie", 0),
("Leefstijlinterventie", 1),
("Antivirale therapie", 1),
("Music Therapie", 1),
("Naturopathie", 1),
("Leefstijlinterventie", 2),
("Antivirale therapie", 2),
("Music Therapie", 2),
("Pain Management", 2),
("Antivirale therapie", 3),
("Music Therapie", 3),
("Antivirale therapie", 4),
("Pain Management", 4),
("Antivirale therapie", 5),
("Music Therapie", 5),
("Pain Management", 5),
("Naturopathie", 5),
("Leefstijlinterventie", 6),
("Antivirale therapie", 6),
("Music Therapie", 6),
("Naturopathie", 6),
("Leefstijlinterventie", 7),
("Antivirale therapie", 7),
("Music Therapie", 7),
("Leefstijlinterventie", 8),
("Music Therapie", 9),
("Naturopathie", 9),
("Leefstijlinterventie", 10),
("Antivirale therapie", 10),
("Music Therapie", 10),
("Pain Management", 10),
("Antivirale therapie", 11),
("Leefstijlinterventie", 12),
("Antivirale therapie", 12),
("Leefstijlinterventie", 13),
("Antivirale therapie", 13),
("Music Therapie", 13),
("Pain Management", 13),
("Leefstijlinterventie", 14),
("Antivirale therapie", 14),
("Music Therapie", 14),
("Leefstijlinterventie", 15),
("Antivirale therapie", 15),
("Music Therapie", 15),
("Leefstijlinterventie", 16),
("Antivirale therapie", 16),
("Naturopathie", 16),
("Leefstijlinterventie", 17),
("Antivirale therapie", 17),
("Music Therapie", 17),
("Antifungale therapie", 17),
("Leefstijlinterventie", 18),
("Antivirale therapie", 18),
("Pain Management", 18),
("Leefstijlinterventie", 19),
("Antivirale therapie", 19),
("Music Therapie", 19),
("Leefstijlinterventie", 20),
("Antivirale therapie", 20),
("Music Therapie", 20),
("Leefstijlinterventie", 21),
("Leefstijlinterventie", 22),
("Antivirale therapie", 22),
("Music Therapie", 22),
("Leefstijlinterventie", 23),
("Music Therapie", 23),
("Leefstijlinterventie", 24),
("Leefstijlinterventie", 25),
("Antivirale therapie", 25),
("Leefstijlinterventie", 26),
("Music Therapie", 26),
("Naturopathie", 26),
("Arthroscopie", 26),
("Leefstijlinterventie", 27),
("Music Therapie", 27),
("Pain Management", 27),
("Naturopathie", 27),
("Leefstijlinterventie", 28),
("Leefstijlinterventie", 29),
("Leefstijlinterventie", 30),
("Leefstijlinterventie", 31),
("Pain Management", 31),
("Leefstijlinterventie", 32),
("Leefstijlinterventie", 38),
("Antivirale therapie", 38),
("Naturopathie", 38),
("Leefstijlinterventie", 39),
("Antivirale therapie", 39),
("Naturopathie", 39),
("Pain Management", 39),
("Leefstijlinterventie", 41),
("Antivirale therapie", 42),
("Music Therapie", 42),
("Naturopathie", 42),
("Pain Management", 42),
("Leefstijlinterventie", 43),
("Antivirale therapie", 43),
("Music Therapie", 43),
("Naturopathie", 43),
("Leefstijlinterventie", 45),
("Music Therapie", 45),
("Pain Management", 45),
("Naturopathie", 45),
("Antivirale therapie", 46),
("Music Therapie", 46),
("Pain Management", 46),
("Antivirale therapie", 47),
("Music Therapie", 47),
("Naturopathie", 47),
("Antivirale therapie", 48),
("Music Therapie", 48),
("Naturopathie", 48),
("Leefstijlinterventie", 50),
("Leefstijlinterventie", 51),
("Antivirale therapie", 51),
("Music Therapie", 51),
("Pain Management", 51),
("Antivirale therapie", 52),
("Music Therapie", 52),
("Pain Management", 52),
("Leefstijlinterventie", 53),
("Antivirale therapie", 54),
("Naturopathie", 54),
("Antivirale therapie", 57),
("Music Therapie", 57),
("Leefstijlinterventie", 58),
("Antivirale therapie", 58),
("Leefstijlinterventie", 70),
("Antivirale therapie", 70),
("Music Therapie", 70),
("Leefstijlinterventie", 87),
("Naturopathie", 87),
("Leefstijlinterventie", 88),
("Music Therapie", 88),
("Pain Management", 88),
("Leefstijlinterventie", 89),
("Music Therapie", 89),
("Leefstijlinterventie", 94),
("Antivirale therapie", 94),
("Leefstijlinterventie", 113),
("Pain Management", 113),
("Leefstijlinterventie", 195),
("Antivirale therapie", 195),
("Leefstijlinterventie", 273);
("Antivirale therapie", 273);
("Naturopathie", 273);
("Pain Management", 273);
