INSERT INTO Ziekte_heeft_Geneeswijze(Geneeswijze_naam, Ziekte_ziekte_id)
VALUES
("Genezeologische Therapie", 0),
("Radiotherapie", 0),
("Reiki", 0),
("Genezeologische Therapie", 1),
("Genezeologische Therapie", 2),
("Radiotherapie", 2),
("Radiotherapie", 3),
("Reiki", 3),
("Radiotherapie", 4),
("Yoga", 5),
("Reiki", 5),
("Endocriene Therapie", 6),
("Yoga", 6),
("Radiotherapie", 6),
("Reiki", 6),
("Radiotherapie", 7),
("Endocriene Therapie", 7),
("Hyperbare zuurstoftherapie", 7),
("Nerve block", 7),
("Yoga", 8),
("Endocriene Therapie", 8),
("Genezeologische Therapie", 9),
("Endocriene Therapie", 9),
("Radiotherapie", 10),
("Yoga", 11),
("Radiotherapie", 11),
("Hyperbare zuurstoftherapie", 11),
("Nerve block", 11),
("Yoga", 12),
("Radiotherapie", 12),
("Endocriene Therapie", 12),
("Reiki", 12),
("Genezeologische Therapie", 13),
("Endocriene Therapie", 13),
("Reiki", 13),
("Yoga", 14),
("Reiki", 14),
("Radiotherapie", 15),
("Radiotherapie", 16),
("Endocriene Therapie", 16),
("Hyperbare zuurstoftherapie", 17),
("Nerve block", 17),
("Antibiotica therapie", 17),
("Art Therapie", 17),
("Yoga", 18),
("Genezeologische Therapie", 19),
("Genezeologische Therapie", 20),
("Yoga", 20),
("Reiki", 20),
("Endocriene Therapie", 20),
("Yoga", 21),
("Reiki", 21),
("Hyperbare zuurstoftherapie", 21),
("Nerve block", 21),
("Radiotherapie", 22),
("Yoga", 22),
("Reiki", 22),
("Genezeologische Therapie", 23),
("Endocriene Therapie", 23),
("Yoga", 23),
("Radiotherapie", 24),
("Genezeologische Therapie", 25),
("Radiotherapie", 26),
("Endocriene Therapie", 26),
("Reiki", 26),
("Yoga", 26),
("Endocriene Therapie", 27),
("Reiki", 27),
("Radiotherapie", 27),
("Genezeologische Therapie", 28),
("Radiotherapie", 28),
("Endocriene Therapie", 29),
("Reiki", 29),
("Yoga", 29),
("Endocriene Therapie", 30),
("Reiki", 30),
("Radiotherapie", 30),
("Hyperbare zuurstoftherapie", 30),
("Yoga", 31),
("Reiki", 31),
("Endocriene Therapie", 31),
("Radiotherapie", 31),
("Endocriene Therapie", 32),
("Reiki", 32),
("Hyperbare zuurstoftherapie", 32),
("Nerve block", 32),
("Genezeologische Therapie", 38),
("Radiotherapie", 38),
("Endocriene Therapie", 39),
("Radiotherapie", 39),
("Reiki", 39),
("Yoga", 39),
("Genezeologische Therapie", 41),
("Radiotherapie", 42),
("Reiki", 42),
("Endocriene Therapie", 43),
("Yoga", 43),
("Reiki", 43),
("Genezeologische Therapie", 45),
("Radiotherapie", 46),
("Reiki", 46),
("Endocriene Therapie", 46),
("Hyperbare zuurstoftherapie", 46),
("Endocriene Therapie", 47),
("Yoga", 48),
("Endocriene Therapie", 48),
("Radiotherapie", 50),
("Endocriene Therapie", 50),
("Reiki", 50),
("Yoga", 50),
("Endocriene Therapie", 51),
("Reiki", 51),
("Radiotherapie", 51),
("Yoga", 51),
("Radiotherapie", 52),
("Reiki", 52),
("Genezeologische Therapie", 53),
("Yoga", 53),
("Radiotherapie", 53),
("Endocriene Therapie", 53),
("Genezeologische Therapie", 54),
("Endocriene Therapie", 57),
("Reiki", 57),
("Radiotherapie", 57),
("Yoga", 58),
("Reiki", 58),
("Radiotherapie", 70),
("Reiki", 70),
("Yoga", 70),
("Yoga", 87),
("Endocriene Therapie", 87),
("Hyperbare zuurstoftherapie", 87),
("Radiotherapie", 88),
("Reiki", 88),
("Yoga", 88),
("Endocriene Therapie", 88),
("Yoga", 89),
("Reiki", 89),
("Endocriene Therapie", 89),
("Yoga", 94),
("Endocriene Therapie", 94),
("Genezeologische Therapie", 113),
("Yoga", 113),
("Reiki", 113),
("Endocriene Therapie", 113),
("Yoga", 195),
("Radiotherapie", 273),
("Endocriene Therapie", 273),
("Yoga", 273),
("Hyperbare zuurstoftherapie", 273),
