INSERT INTO Ziekte(ziekte_id, naam, beschrijving)
VALUES
(0, "Diabetes Mellitus", "Een chronische aandoening die de manier waarop het lichaam glucose gebruikt beïnvloedt."),
(1, "Hypertensie", "Een aandoening waarbij de bloeddruk in de slagaders chronisch verhoogd is."),
(2, "Astma", "Een chronische ontstekingsziekte van de luchtwegen die ademhaling bemoeilijkt."),
(3, "Reumatoïde Artritis", "Een auto-immuunziekte die gewrichten ontstoken en pijnlijk maakt."),
(4, "Kanker", "Een groep van ziekten gekenmerkt door oncontroleerbare celgroei en verspreiding."),
(5, "Depressie", "Een mentale gezondheidsstoornis gekenmerkt door aanhoudende gevoelens van verdriet en verlies van interesse."),
(6, "Multiple Sclerose", "Een auto-immuunziekte die de zenuwvezels in de hersenen en het ruggenmerg aantast."),
(7, "Hepatitis B", "Een infectieziekte die de lever aantast, veroorzaakt door het hepatitis B-virus."),
(8, "Osteoporose", "Een aandoening die de botdichtheid vermindert en het risico op breuken verhoogt."),
(9, "Alzheimer", "Een progressieve neurologische aandoening die geheugenverlies en cognitieve achteruitgang veroorzaakt."),
(10, "COPD (Chronische Obstructieve Longziekte)", "Een groep longziekten die ademhaling bemoeilijkt, waaronder emfyseem en chronische bronchitis."),
(11, "Parkinson", "Een neurodegeneratieve aandoening die beweging en coördinatie beïnvloedt."),
(12, "Schizofrenie", "Een ernstige mentale stoornis die denken, voelen en gedrag verstoort."),
(13, "Arteriële Atherosclerose", "Opbouw van vetachtige plaques in de slagaders, wat kan leiden tot hartaanvallen en beroertes."),
(14, "Leukemie", "Een type kanker dat het bloed en het beenmerg aantast."),
(15, "Tuberculose", "Een bacteriële infectie die meestal de longen aantast."),
(16, "Cystic Fibrosis", "Een erfelijke aandoening die longen en het spijsverteringsstelsel aantast."),
(17, "HIV/AIDS", "Een virusinfectie die het immuunsysteem verzwakt en leidt tot AIDS."),
(18, "Eczema", "Een ontstekingsaandoening van de huid die roodheid, jeuk en irritatie veroorzaakt."),
(19, "Migraine", "Een ernstige vorm van hoofdpijn die gepaard gaat met misselijkheid en gevoeligheid voor licht."),
(20, "Fibromyalgie", "Een chronische aandoening gekenmerkt door wijdverspreide pijn en vermoeidheid."),
(21, "Psoriasis", "Een auto-immuunziekte die snelle groei van huidcellen veroorzaakt, leidend tot schilferige plekken."),
(22, "Bipolaire Stoornis", "Een mentale aandoening gekenmerkt door extreme stemmingswisselingen tussen manie en depressie."),
(23, "Endometriose", "Een aandoening waarbij weefsel dat lijkt op baarmoederslijmvlies buiten de baarmoeder groeit."),
(24, "Gastritis", "Een ontsteking van het maagslijmvlies die maagpijn en spijsverteringsproblemen veroorzaakt."),
(25, "Bronchitis", "Ontsteking van de bronchiën in de longen, wat leidt tot hoesten en ademhalingsproblemen."),
(26, "Pneumonie", "Een infectie van de longen die koorts, hoesten en ademhalingsmoeilijkheden veroorzaakt."),
(27, "Anemie", "Een aandoening waarbij er een tekort is aan rode bloedcellen of hemoglobine."),
(28, "Thyreoïditis", "Ontsteking van de schildklier, wat leidt tot hormonale disbalans."),
(29, "Nierstenen", "Hard mineralen en zoutafzettingen die zich in de nieren vormen en hevige pijn veroorzaken."),
(30, "Hartaandoeningen", "Verschillende aandoeningen die het hart aantasten, waaronder coronaire hartziekte en hartfalen."),
(31, "Celiac Disease", "Een auto-immuunziekte waarbij de inname van gluten leidt tot beschadiging van de dunne darm."),
(32, "Alzheimer's Ziekte", "Een progressieve neurologische aandoening die geheugenverlies en cognitieve achteruitgang veroorzaakt."),
(38, "Hepatitis C", "Een virale infectie die de lever aantast en kan leiden tot ernstige leverziekten."),
(39, "Epilepsie", "Een neurologische aandoening gekenmerkt door terugkerende aanvallen."),
(41, "Hartaanval", "Een plotselinge blokkade van de bloedtoevoer naar het hart, wat schade aan de hartspier veroorzaakt."),
(42, "Borstkanker", "Een type kanker dat begint in de cellen van de borst."),
(43, "Prostaatkanker", "Een type kanker dat voorkomt in de prostaat, een klier bij mannen."),
(45, "Angina Pectoris", "Pijn of ongemak in de borst veroorzaakt door verminderde bloedtoevoer naar het hart."),
(46, "Leptomeningeomen", "Goedaardige tumoren die de hersenvliezen aantasten."),
(47, "Schildklierkanker", "Een type kanker dat begint in de schildklier, een klier in de hals."),
(48, "Amyotrofische Laterale Sclerose (ALS)", "Een progressieve neurodegeneratieve ziekte die zenuwcellen in de hersenen en het ruggenmerg aantast."),
(50, "Systemische Lupus Erythematosus (SLE)", "Een auto-immuunziekte die verschillende delen van het lichaam kan aantasten, waaronder huid, gewrichten en organen."),
(51, "Downsyndroom", "Een genetische aandoening veroorzaakt door een extra chromosoom 21, gekenmerkt door fysieke en mentale ontwikkelingsachterstanden."),
(52, "Cerebrale Parese", "Een groep van stoornissen die beweging en spierspanning beïnvloeden, veroorzaakt door hersenbeschadiging."),
(53, "Ebola", "Een ernstige virusinfectie die koorts, bloedingen en orgaanfalen veroorzaakt."),
(54, "Ziekte van Huntington", "Een erfelijke aandoening die de hersenen aantast en leidt tot ongecontroleerde bewegingen en mentale achteruitgang."),
(57, "Rheumatoïde Artritis", "Een auto-immuunziekte die gewrichten ontstoken en pijnlijk maakt."),
(58, "Hepatitis A", "Een leverontsteking veroorzaakt door het hepatitis A-virus, meestal via besmet voedsel of water."),
(70, "Ziekte van Parkinson", "Een neurodegeneratieve aandoening die beweging en coördinatie beïnvloedt."),
(87, "Diabetes Type 1", "Een auto-immuunziekte waarbij het lichaam insuline produceert niet kan produceren."),
(88, "Diabetes Type 2", "Een metabole aandoening waarbij het lichaam insuline niet effectief gebruikt."),
(89, "Kanker van de Dikke Darm", "Een type kanker dat begint in de dikke darm of endeldarm."),
(94, "Migrane", "Een ernstige vorm van hoofdpijn die gepaard gaat met misselijkheid en gevoeligheid voor licht."),
(113, "Cholesterol Metabolisme Storing", "Een aandoening waarbij het lichaam cholesterol niet goed kan verwerken, leidend tot hoge cholesterolwaarden."),
(195, "Schildklierfunctiestoornis", "Aandoeningen waarbij de schildklier te veel of te weinig hormonen produceert."),
(273, "Hiv/AIDS", "Een virusinfectie die het immuunsysteem verzwakt en leidt tot AIDS."),
